// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accounterrorhistory"
)

// AccountErrorHistoryCreate is the builder for creating a AccountErrorHistory entity.
type AccountErrorHistoryCreate struct {
	config
	mutation *AccountErrorHistoryMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAccountID sets the "account_id" field.
func (_c *AccountErrorHistoryCreate) SetAccountID(v int64) *AccountErrorHistoryCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *AccountErrorHistoryCreate) SetUserID(v int64) *AccountErrorHistoryCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *AccountErrorHistoryCreate) SetNillableUserID(v *int64) *AccountErrorHistoryCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetUserEmail sets the "user_email" field.
func (_c *AccountErrorHistoryCreate) SetUserEmail(v string) *AccountErrorHistoryCreate {
	_c.mutation.SetUserEmail(v)
	return _c
}

// SetNillableUserEmail sets the "user_email" field if the given value is not nil.
func (_c *AccountErrorHistoryCreate) SetNillableUserEmail(v *string) *AccountErrorHistoryCreate {
	if v != nil {
		_c.SetUserEmail(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *AccountErrorHistoryCreate) SetModel(v string) *AccountErrorHistoryCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *AccountErrorHistoryCreate) SetNillableModel(v *string) *AccountErrorHistoryCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetUpstreamStatusCode sets the "upstream_status_code" field.
func (_c *AccountErrorHistoryCreate) SetUpstreamStatusCode(v int) *AccountErrorHistoryCreate {
	_c.mutation.SetUpstreamStatusCode(v)
	return _c
}

// SetNillableUpstreamStatusCode sets the "upstream_status_code" field if the given value is not nil.
func (_c *AccountErrorHistoryCreate) SetNillableUpstreamStatusCode(v *int) *AccountErrorHistoryCreate {
	if v != nil {
		_c.SetUpstreamStatusCode(*v)
	}
	return _c
}

// SetSource sets the "source" field.
func (_c *AccountErrorHistoryCreate) SetSource(v accounterrorhistory.Source) *AccountErrorHistoryCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetMessage sets the "message" field.
func (_c *AccountErrorHistoryCreate) SetMessage(v string) *AccountErrorHistoryCreate {
	_c.mutation.SetMessage(v)
	return _c
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_c *AccountErrorHistoryCreate) SetNillableMessage(v *string) *AccountErrorHistoryCreate {
	if v != nil {
		_c.SetMessage(*v)
	}
	return _c
}

// SetFingerprint sets the "fingerprint" field.
func (_c *AccountErrorHistoryCreate) SetFingerprint(v string) *AccountErrorHistoryCreate {
	_c.mutation.SetFingerprint(v)
	return _c
}

// SetNillableFingerprint sets the "fingerprint" field if the given value is not nil.
func (_c *AccountErrorHistoryCreate) SetNillableFingerprint(v *string) *AccountErrorHistoryCreate {
	if v != nil {
		_c.SetFingerprint(*v)
	}
	return _c
}

// SetDupCount sets the "dup_count" field.
func (_c *AccountErrorHistoryCreate) SetDupCount(v int) *AccountErrorHistoryCreate {
	_c.mutation.SetDupCount(v)
	return _c
}

// SetNillableDupCount sets the "dup_count" field if the given value is not nil.
func (_c *AccountErrorHistoryCreate) SetNillableDupCount(v *int) *AccountErrorHistoryCreate {
	if v != nil {
		_c.SetDupCount(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccountErrorHistoryCreate) SetCreatedAt(v time.Time) *AccountErrorHistoryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AccountErrorHistoryCreate) SetNillableCreatedAt(v *time.Time) *AccountErrorHistoryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AccountErrorHistoryCreate) SetUpdatedAt(v time.Time) *AccountErrorHistoryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AccountErrorHistoryCreate) SetNillableUpdatedAt(v *time.Time) *AccountErrorHistoryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *AccountErrorHistoryCreate) SetAccount(v *Account) *AccountErrorHistoryCreate {
	return _c.SetAccountID(v.ID)
}

// Mutation returns the AccountErrorHistoryMutation object of the builder.
func (_c *AccountErrorHistoryCreate) Mutation() *AccountErrorHistoryMutation {
	return _c.mutation
}

// Save creates the AccountErrorHistory in the database.
func (_c *AccountErrorHistoryCreate) Save(ctx context.Context) (*AccountErrorHistory, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountErrorHistoryCreate) SaveX(ctx context.Context) *AccountErrorHistory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountErrorHistoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountErrorHistoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountErrorHistoryCreate) defaults() {
	if _, ok := _c.mutation.Message(); !ok {
		v := accounterrorhistory.DefaultMessage
		_c.mutation.SetMessage(v)
	}
	if _, ok := _c.mutation.Fingerprint(); !ok {
		v := accounterrorhistory.DefaultFingerprint
		_c.mutation.SetFingerprint(v)
	}
	if _, ok := _c.mutation.DupCount(); !ok {
		v := accounterrorhistory.DefaultDupCount
		_c.mutation.SetDupCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := accounterrorhistory.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := accounterrorhistory.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountErrorHistoryCreate) check() error {
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "AccountErrorHistory.account_id"`)}
	}
	if v, ok := _c.mutation.UserEmail(); ok {
		if err := accounterrorhistory.UserEmailValidator(v); err != nil {
			return &ValidationError{Name: "user_email", err: fmt.Errorf(`ent: validator failed for field "AccountErrorHistory.user_email": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := accounterrorhistory.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "AccountErrorHistory.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "AccountErrorHistory.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := accounterrorhistory.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "AccountErrorHistory.source": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Fingerprint(); ok {
		if err := accounterrorhistory.FingerprintValidator(v); err != nil {
			return &ValidationError{Name: "fingerprint", err: fmt.Errorf(`ent: validator failed for field "AccountErrorHistory.fingerprint": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DupCount(); !ok {
		return &ValidationError{Name: "dup_count", err: errors.New(`ent: missing required field "AccountErrorHistory.dup_count"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AccountErrorHistory.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AccountErrorHistory.updated_at"`)}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "AccountErrorHistory.account"`)}
	}
	return nil
}

func (_c *AccountErrorHistoryCreate) sqlSave(ctx context.Context) (*AccountErrorHistory, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccountErrorHistoryCreate) createSpec() (*AccountErrorHistory, *sqlgraph.CreateSpec) {
	var (
		_node = &AccountErrorHistory{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accounterrorhistory.Table, sqlgraph.NewFieldSpec(accounterrorhistory.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(accounterrorhistory.FieldUserID, field.TypeInt64, value)
		_node.UserID = &value
	}
	if value, ok := _c.mutation.UserEmail(); ok {
		_spec.SetField(accounterrorhistory.FieldUserEmail, field.TypeString, value)
		_node.UserEmail = &value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(accounterrorhistory.FieldModel, field.TypeString, value)
		_node.Model = &value
	}
	if value, ok := _c.mutation.UpstreamStatusCode(); ok {
		_spec.SetField(accounterrorhistory.FieldUpstreamStatusCode, field.TypeInt, value)
		_node.UpstreamStatusCode = &value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(accounterrorhistory.FieldSource, field.TypeEnum, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.Message(); ok {
		_spec.SetField(accounterrorhistory.FieldMessage, field.TypeString, value)
		_node.Message = value
	}
	if value, ok := _c.mutation.Fingerprint(); ok {
		_spec.SetField(accounterrorhistory.FieldFingerprint, field.TypeString, value)
		_node.Fingerprint = value
	}
	if value, ok := _c.mutation.DupCount(); ok {
		_spec.SetField(accounterrorhistory.FieldDupCount, field.TypeInt, value)
		_node.DupCount = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(accounterrorhistory.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(accounterrorhistory.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accounterrorhistory.AccountTable,
			Columns: []string{accounterrorhistory.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountErrorHistory.Create().
//		SetAccountID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountErrorHistoryUpsert) {
//			SetAccountID(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountErrorHistoryCreate) OnConflict(opts ...sql.ConflictOption) *AccountErrorHistoryUpsertOne {
	_c.conflict = opts
	return &AccountErrorHistoryUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountErrorHistory.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountErrorHistoryCreate) OnConflictColumns(columns ...string) *AccountErrorHistoryUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountErrorHistoryUpsertOne{
		create: _c,
	}
}

type (
	// AccountErrorHistoryUpsertOne is the builder for "upsert"-ing
	//  one AccountErrorHistory node.
	AccountErrorHistoryUpsertOne struct {
		create *AccountErrorHistoryCreate
	}

	// AccountErrorHistoryUpsert is the "OnConflict" setter.
	AccountErrorHistoryUpsert struct {
		*sql.UpdateSet
	}
)

// SetAccountID sets the "account_id" field.
func (u *AccountErrorHistoryUpsert) SetAccountID(v int64) *AccountErrorHistoryUpsert {
	u.Set(accounterrorhistory.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountErrorHistoryUpsert) UpdateAccountID() *AccountErrorHistoryUpsert {
	u.SetExcluded(accounterrorhistory.FieldAccountID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *AccountErrorHistoryUpsert) SetUserID(v int64) *AccountErrorHistoryUpsert {
	u.Set(accounterrorhistory.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AccountErrorHistoryUpsert) UpdateUserID() *AccountErrorHistoryUpsert {
	u.SetExcluded(accounterrorhistory.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *AccountErrorHistoryUpsert) AddUserID(v int64) *AccountErrorHistoryUpsert {
	u.Add(accounterrorhistory.FieldUserID, v)
	return u
}

// ClearUserID clears the value of the "user_id" field.
func (u *AccountErrorHistoryUpsert) ClearUserID() *AccountErrorHistoryUpsert {
	u.SetNull(accounterrorhistory.FieldUserID)
	return u
}

// SetUserEmail sets the "user_email" field.
func (u *AccountErrorHistoryUpsert) SetUserEmail(v string) *AccountErrorHistoryUpsert {
	u.Set(accounterrorhistory.FieldUserEmail, v)
	return u
}

// UpdateUserEmail sets the "user_email" field to the value that was provided on create.
func (u *AccountErrorHistoryUpsert) UpdateUserEmail() *AccountErrorHistoryUpsert {
	u.SetExcluded(accounterrorhistory.FieldUserEmail)
	return u
}

// ClearUserEmail clears the value of the "user_email" field.
func (u *AccountErrorHistoryUpsert) ClearUserEmail() *AccountErrorHistoryUpsert {
	u.SetNull(accounterrorhistory.FieldUserEmail)
	return u
}

// SetModel sets the "model" field.
func (u *AccountErrorHistoryUpsert) SetModel(v string) *AccountErrorHistoryUpsert {
	u.Set(accounterrorhistory.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *AccountErrorHistoryUpsert) UpdateModel() *AccountErrorHistoryUpsert {
	u.SetExcluded(accounterrorhistory.FieldModel)
	return u
}

// ClearModel clears the value of the "model" field.
func (u *AccountErrorHistoryUpsert) ClearModel() *AccountErrorHistoryUpsert {
	u.SetNull(accounterrorhistory.FieldModel)
	return u
}

// SetUpstreamStatusCode sets the "upstream_status_code" field.
func (u *AccountErrorHistoryUpsert) SetUpstreamStatusCode(v int) *AccountErrorHistoryUpsert {
	u.Set(accounterrorhistory.FieldUpstreamStatusCode, v)
	return u
}

// UpdateUpstreamStatusCode sets the "upstream_status_code" field to the value that was provided on create.
func (u *AccountErrorHistoryUpsert) UpdateUpstreamStatusCode() *AccountErrorHistoryUpsert {
	u.SetExcluded(accounterrorhistory.FieldUpstreamStatusCode)
	return u
}

// AddUpstreamStatusCode adds v to the "upstream_status_code" field.
func (u *AccountErrorHistoryUpsert) AddUpstreamStatusCode(v int) *AccountErrorHistoryUpsert {
	u.Add(accounterrorhistory.FieldUpstreamStatusCode, v)
	return u
}

// ClearUpstreamStatusCode clears the value of the "upstream_status_code" field.
func (u *AccountErrorHistoryUpsert) ClearUpstreamStatusCode() *AccountErrorHistoryUpsert {
	u.SetNull(accounterrorhistory.FieldUpstreamStatusCode)
	return u
}

// SetSource sets the "source" field.
func (u *AccountErrorHistoryUpsert) SetSource(v accounterrorhistory.Source) *AccountErrorHistoryUpsert {
	u.Set(accounterrorhistory.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *AccountErrorHistoryUpsert) UpdateSource() *AccountErrorHistoryUpsert {
	u.SetExcluded(accounterrorhistory.FieldSource)
	return u
}

// SetMessage sets the "message" field.
func (u *AccountErrorHistoryUpsert) SetMessage(v string) *AccountErrorHistoryUpsert {
	u.Set(accounterrorhistory.FieldMessage, v)
	return u
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *AccountErrorHistoryUpsert) UpdateMessage() *AccountErrorHistoryUpsert {
	u.SetExcluded(accounterrorhistory.FieldMessage)
	return u
}

// ClearMessage clears the value of the "message" field.
func (u *AccountErrorHistoryUpsert) ClearMessage() *AccountErrorHistoryUpsert {
	u.SetNull(accounterrorhistory.FieldMessage)
	return u
}

// SetFingerprint sets the "fingerprint" field.
func (u *AccountErrorHistoryUpsert) SetFingerprint(v string) *AccountErrorHistoryUpsert {
	u.Set(accounterrorhistory.FieldFingerprint, v)
	return u
}

// UpdateFingerprint sets the "fingerprint" field to the value that was provided on create.
func (u *AccountErrorHistoryUpsert) UpdateFingerprint() *AccountErrorHistoryUpsert {
	u.SetExcluded(accounterrorhistory.FieldFingerprint)
	return u
}

// ClearFingerprint clears the value of the "fingerprint" field.
func (u *AccountErrorHistoryUpsert) ClearFingerprint() *AccountErrorHistoryUpsert {
	u.SetNull(accounterrorhistory.FieldFingerprint)
	return u
}

// SetDupCount sets the "dup_count" field.
func (u *AccountErrorHistoryUpsert) SetDupCount(v int) *AccountErrorHistoryUpsert {
	u.Set(accounterrorhistory.FieldDupCount, v)
	return u
}

// UpdateDupCount sets the "dup_count" field to the value that was provided on create.
func (u *AccountErrorHistoryUpsert) UpdateDupCount() *AccountErrorHistoryUpsert {
	u.SetExcluded(accounterrorhistory.FieldDupCount)
	return u
}

// AddDupCount adds v to the "dup_count" field.
func (u *AccountErrorHistoryUpsert) AddDupCount(v int) *AccountErrorHistoryUpsert {
	u.Add(accounterrorhistory.FieldDupCount, v)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *AccountErrorHistoryUpsert) SetCreatedAt(v time.Time) *AccountErrorHistoryUpsert {
	u.Set(accounterrorhistory.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *AccountErrorHistoryUpsert) UpdateCreatedAt() *AccountErrorHistoryUpsert {
	u.SetExcluded(accounterrorhistory.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountErrorHistoryUpsert) SetUpdatedAt(v time.Time) *AccountErrorHistoryUpsert {
	u.Set(accounterrorhistory.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountErrorHistoryUpsert) UpdateUpdatedAt() *AccountErrorHistoryUpsert {
	u.SetExcluded(accounterrorhistory.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AccountErrorHistory.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountErrorHistoryUpsertOne) UpdateNewValues() *AccountErrorHistoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountErrorHistory.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccountErrorHistoryUpsertOne) Ignore() *AccountErrorHistoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountErrorHistoryUpsertOne) DoNothing() *AccountErrorHistoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountErrorHistoryCreate.OnConflict
// documentation for more info.
func (u *AccountErrorHistoryUpsertOne) Update(set func(*AccountErrorHistoryUpsert)) *AccountErrorHistoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountErrorHistoryUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *AccountErrorHistoryUpsertOne) SetAccountID(v int64) *AccountErrorHistoryUpsertOne {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountErrorHistoryUpsertOne) UpdateAccountID() *AccountErrorHistoryUpsertOne {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.UpdateAccountID()
	})
}

// SetUserID sets the "user_id" field.
func (u *AccountErrorHistoryUpsertOne) SetUserID(v int64) *AccountErrorHistoryUpsertOne {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *AccountErrorHistoryUpsertOne) AddUserID(v int64) *AccountErrorHistoryUpsertOne {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AccountErrorHistoryUpsertOne) UpdateUserID() *AccountErrorHistoryUpsertOne {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *AccountErrorHistoryUpsertOne) ClearUserID() *AccountErrorHistoryUpsertOne {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.ClearUserID()
	})
}

// SetUserEmail sets the "user_email" field.
func (u *AccountErrorHistoryUpsertOne) SetUserEmail(v string) *AccountErrorHistoryUpsertOne {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.SetUserEmail(v)
	})
}

// UpdateUserEmail sets the "user_email" field to the value that was provided on create.
func (u *AccountErrorHistoryUpsertOne) UpdateUserEmail() *AccountErrorHistoryUpsertOne {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.UpdateUserEmail()
	})
}

// ClearUserEmail clears the value of the "user_email" field.
func (u *AccountErrorHistoryUpsertOne) ClearUserEmail() *AccountErrorHistoryUpsertOne {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.ClearUserEmail()
	})
}

// SetModel sets the "model" field.
func (u *AccountErrorHistoryUpsertOne) SetModel(v string) *AccountErrorHistoryUpsertOne {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *AccountErrorHistoryUpsertOne) UpdateModel() *AccountErrorHistoryUpsertOne {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.UpdateModel()
	})
}

// ClearModel clears the value of the "model" field.
func (u *AccountErrorHistoryUpsertOne) ClearModel() *AccountErrorHistoryUpsertOne {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.ClearModel()
	})
}

// SetUpstreamStatusCode sets the "upstream_status_code" field.
func (u *AccountErrorHistoryUpsertOne) SetUpstreamStatusCode(v int) *AccountErrorHistoryUpsertOne {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.SetUpstreamStatusCode(v)
	})
}

// AddUpstreamStatusCode adds v to the "upstream_status_code" field.
func (u *AccountErrorHistoryUpsertOne) AddUpstreamStatusCode(v int) *AccountErrorHistoryUpsertOne {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.AddUpstreamStatusCode(v)
	})
}

// UpdateUpstreamStatusCode sets the "upstream_status_code" field to the value that was provided on create.
func (u *AccountErrorHistoryUpsertOne) UpdateUpstreamStatusCode() *AccountErrorHistoryUpsertOne {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.UpdateUpstreamStatusCode()
	})
}

// ClearUpstreamStatusCode clears the value of the "upstream_status_code" field.
func (u *AccountErrorHistoryUpsertOne) ClearUpstreamStatusCode() *AccountErrorHistoryUpsertOne {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.ClearUpstreamStatusCode()
	})
}

// SetSource sets the "source" field.
func (u *AccountErrorHistoryUpsertOne) SetSource(v accounterrorhistory.Source) *AccountErrorHistoryUpsertOne {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *AccountErrorHistoryUpsertOne) UpdateSource() *AccountErrorHistoryUpsertOne {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.UpdateSource()
	})
}

// SetMessage sets the "message" field.
func (u *AccountErrorHistoryUpsertOne) SetMessage(v string) *AccountErrorHistoryUpsertOne {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.SetMessage(v)
	})
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *AccountErrorHistoryUpsertOne) UpdateMessage() *AccountErrorHistoryUpsertOne {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.UpdateMessage()
	})
}

// ClearMessage clears the value of the "message" field.
func (u *AccountErrorHistoryUpsertOne) ClearMessage() *AccountErrorHistoryUpsertOne {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.ClearMessage()
	})
}

// SetFingerprint sets the "fingerprint" field.
func (u *AccountErrorHistoryUpsertOne) SetFingerprint(v string) *AccountErrorHistoryUpsertOne {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.SetFingerprint(v)
	})
}

// UpdateFingerprint sets the "fingerprint" field to the value that was provided on create.
func (u *AccountErrorHistoryUpsertOne) UpdateFingerprint() *AccountErrorHistoryUpsertOne {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.UpdateFingerprint()
	})
}

// ClearFingerprint clears the value of the "fingerprint" field.
func (u *AccountErrorHistoryUpsertOne) ClearFingerprint() *AccountErrorHistoryUpsertOne {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.ClearFingerprint()
	})
}

// SetDupCount sets the "dup_count" field.
func (u *AccountErrorHistoryUpsertOne) SetDupCount(v int) *AccountErrorHistoryUpsertOne {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.SetDupCount(v)
	})
}

// AddDupCount adds v to the "dup_count" field.
func (u *AccountErrorHistoryUpsertOne) AddDupCount(v int) *AccountErrorHistoryUpsertOne {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.AddDupCount(v)
	})
}

// UpdateDupCount sets the "dup_count" field to the value that was provided on create.
func (u *AccountErrorHistoryUpsertOne) UpdateDupCount() *AccountErrorHistoryUpsertOne {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.UpdateDupCount()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *AccountErrorHistoryUpsertOne) SetCreatedAt(v time.Time) *AccountErrorHistoryUpsertOne {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *AccountErrorHistoryUpsertOne) UpdateCreatedAt() *AccountErrorHistoryUpsertOne {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountErrorHistoryUpsertOne) SetUpdatedAt(v time.Time) *AccountErrorHistoryUpsertOne {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountErrorHistoryUpsertOne) UpdateUpdatedAt() *AccountErrorHistoryUpsertOne {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *AccountErrorHistoryUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountErrorHistoryCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountErrorHistoryUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AccountErrorHistoryUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AccountErrorHistoryUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AccountErrorHistoryCreateBulk is the builder for creating many AccountErrorHistory entities in bulk.
type AccountErrorHistoryCreateBulk struct {
	config
	err      error
	builders []*AccountErrorHistoryCreate
	conflict []sql.ConflictOption
}

// Save creates the AccountErrorHistory entities in the database.
func (_c *AccountErrorHistoryCreateBulk) Save(ctx context.Context) ([]*AccountErrorHistory, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccountErrorHistory, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountErrorHistoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountErrorHistoryCreateBulk) SaveX(ctx context.Context) []*AccountErrorHistory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountErrorHistoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountErrorHistoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountErrorHistory.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountErrorHistoryUpsert) {
//			SetAccountID(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountErrorHistoryCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccountErrorHistoryUpsertBulk {
	_c.conflict = opts
	return &AccountErrorHistoryUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountErrorHistory.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountErrorHistoryCreateBulk) OnConflictColumns(columns ...string) *AccountErrorHistoryUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountErrorHistoryUpsertBulk{
		create: _c,
	}
}

// AccountErrorHistoryUpsertBulk is the builder for "upsert"-ing
// a bulk of AccountErrorHistory nodes.
type AccountErrorHistoryUpsertBulk struct {
	create *AccountErrorHistoryCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AccountErrorHistory.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountErrorHistoryUpsertBulk) UpdateNewValues() *AccountErrorHistoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountErrorHistory.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccountErrorHistoryUpsertBulk) Ignore() *AccountErrorHistoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountErrorHistoryUpsertBulk) DoNothing() *AccountErrorHistoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountErrorHistoryCreateBulk.OnConflict
// documentation for more info.
func (u *AccountErrorHistoryUpsertBulk) Update(set func(*AccountErrorHistoryUpsert)) *AccountErrorHistoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountErrorHistoryUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *AccountErrorHistoryUpsertBulk) SetAccountID(v int64) *AccountErrorHistoryUpsertBulk {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountErrorHistoryUpsertBulk) UpdateAccountID() *AccountErrorHistoryUpsertBulk {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.UpdateAccountID()
	})
}

// SetUserID sets the "user_id" field.
func (u *AccountErrorHistoryUpsertBulk) SetUserID(v int64) *AccountErrorHistoryUpsertBulk {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *AccountErrorHistoryUpsertBulk) AddUserID(v int64) *AccountErrorHistoryUpsertBulk {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AccountErrorHistoryUpsertBulk) UpdateUserID() *AccountErrorHistoryUpsertBulk {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *AccountErrorHistoryUpsertBulk) ClearUserID() *AccountErrorHistoryUpsertBulk {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.ClearUserID()
	})
}

// SetUserEmail sets the "user_email" field.
func (u *AccountErrorHistoryUpsertBulk) SetUserEmail(v string) *AccountErrorHistoryUpsertBulk {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.SetUserEmail(v)
	})
}

// UpdateUserEmail sets the "user_email" field to the value that was provided on create.
func (u *AccountErrorHistoryUpsertBulk) UpdateUserEmail() *AccountErrorHistoryUpsertBulk {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.UpdateUserEmail()
	})
}

// ClearUserEmail clears the value of the "user_email" field.
func (u *AccountErrorHistoryUpsertBulk) ClearUserEmail() *AccountErrorHistoryUpsertBulk {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.ClearUserEmail()
	})
}

// SetModel sets the "model" field.
func (u *AccountErrorHistoryUpsertBulk) SetModel(v string) *AccountErrorHistoryUpsertBulk {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *AccountErrorHistoryUpsertBulk) UpdateModel() *AccountErrorHistoryUpsertBulk {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.UpdateModel()
	})
}

// ClearModel clears the value of the "model" field.
func (u *AccountErrorHistoryUpsertBulk) ClearModel() *AccountErrorHistoryUpsertBulk {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.ClearModel()
	})
}

// SetUpstreamStatusCode sets the "upstream_status_code" field.
func (u *AccountErrorHistoryUpsertBulk) SetUpstreamStatusCode(v int) *AccountErrorHistoryUpsertBulk {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.SetUpstreamStatusCode(v)
	})
}

// AddUpstreamStatusCode adds v to the "upstream_status_code" field.
func (u *AccountErrorHistoryUpsertBulk) AddUpstreamStatusCode(v int) *AccountErrorHistoryUpsertBulk {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.AddUpstreamStatusCode(v)
	})
}

// UpdateUpstreamStatusCode sets the "upstream_status_code" field to the value that was provided on create.
func (u *AccountErrorHistoryUpsertBulk) UpdateUpstreamStatusCode() *AccountErrorHistoryUpsertBulk {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.UpdateUpstreamStatusCode()
	})
}

// ClearUpstreamStatusCode clears the value of the "upstream_status_code" field.
func (u *AccountErrorHistoryUpsertBulk) ClearUpstreamStatusCode() *AccountErrorHistoryUpsertBulk {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.ClearUpstreamStatusCode()
	})
}

// SetSource sets the "source" field.
func (u *AccountErrorHistoryUpsertBulk) SetSource(v accounterrorhistory.Source) *AccountErrorHistoryUpsertBulk {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *AccountErrorHistoryUpsertBulk) UpdateSource() *AccountErrorHistoryUpsertBulk {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.UpdateSource()
	})
}

// SetMessage sets the "message" field.
func (u *AccountErrorHistoryUpsertBulk) SetMessage(v string) *AccountErrorHistoryUpsertBulk {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.SetMessage(v)
	})
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *AccountErrorHistoryUpsertBulk) UpdateMessage() *AccountErrorHistoryUpsertBulk {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.UpdateMessage()
	})
}

// ClearMessage clears the value of the "message" field.
func (u *AccountErrorHistoryUpsertBulk) ClearMessage() *AccountErrorHistoryUpsertBulk {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.ClearMessage()
	})
}

// SetFingerprint sets the "fingerprint" field.
func (u *AccountErrorHistoryUpsertBulk) SetFingerprint(v string) *AccountErrorHistoryUpsertBulk {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.SetFingerprint(v)
	})
}

// UpdateFingerprint sets the "fingerprint" field to the value that was provided on create.
func (u *AccountErrorHistoryUpsertBulk) UpdateFingerprint() *AccountErrorHistoryUpsertBulk {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.UpdateFingerprint()
	})
}

// ClearFingerprint clears the value of the "fingerprint" field.
func (u *AccountErrorHistoryUpsertBulk) ClearFingerprint() *AccountErrorHistoryUpsertBulk {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.ClearFingerprint()
	})
}

// SetDupCount sets the "dup_count" field.
func (u *AccountErrorHistoryUpsertBulk) SetDupCount(v int) *AccountErrorHistoryUpsertBulk {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.SetDupCount(v)
	})
}

// AddDupCount adds v to the "dup_count" field.
func (u *AccountErrorHistoryUpsertBulk) AddDupCount(v int) *AccountErrorHistoryUpsertBulk {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.AddDupCount(v)
	})
}

// UpdateDupCount sets the "dup_count" field to the value that was provided on create.
func (u *AccountErrorHistoryUpsertBulk) UpdateDupCount() *AccountErrorHistoryUpsertBulk {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.UpdateDupCount()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *AccountErrorHistoryUpsertBulk) SetCreatedAt(v time.Time) *AccountErrorHistoryUpsertBulk {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *AccountErrorHistoryUpsertBulk) UpdateCreatedAt() *AccountErrorHistoryUpsertBulk {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountErrorHistoryUpsertBulk) SetUpdatedAt(v time.Time) *AccountErrorHistoryUpsertBulk {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountErrorHistoryUpsertBulk) UpdateUpdatedAt() *AccountErrorHistoryUpsertBulk {
	return u.Update(func(s *AccountErrorHistoryUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *AccountErrorHistoryUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccountErrorHistoryCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountErrorHistoryCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountErrorHistoryUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
