// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accounterrorhistory"
)

// AccountErrorHistory is the model entity for the AccountErrorHistory schema.
type AccountErrorHistory struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID *int64 `json:"user_id,omitempty"`
	// UserEmail holds the value of the "user_email" field.
	UserEmail *string `json:"user_email,omitempty"`
	// Model holds the value of the "model" field.
	Model *string `json:"model,omitempty"`
	// UpstreamStatusCode holds the value of the "upstream_status_code" field.
	UpstreamStatusCode *int `json:"upstream_status_code,omitempty"`
	// Source holds the value of the "source" field.
	Source accounterrorhistory.Source `json:"source,omitempty"`
	// Message holds the value of the "message" field.
	Message string `json:"message,omitempty"`
	// Fingerprint holds the value of the "fingerprint" field.
	Fingerprint string `json:"fingerprint,omitempty"`
	// DupCount holds the value of the "dup_count" field.
	DupCount int `json:"dup_count,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AccountErrorHistoryQuery when eager-loading is set.
	Edges        AccountErrorHistoryEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AccountErrorHistoryEdges holds the relations/edges for other nodes in the graph.
type AccountErrorHistoryEdges struct {
	// Account holds the value of the account edge.
	Account *Account `json:"account,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AccountErrorHistoryEdges) AccountOrErr() (*Account, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccountErrorHistory) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accounterrorhistory.FieldID, accounterrorhistory.FieldAccountID, accounterrorhistory.FieldUserID, accounterrorhistory.FieldUpstreamStatusCode, accounterrorhistory.FieldDupCount:
			values[i] = new(sql.NullInt64)
		case accounterrorhistory.FieldUserEmail, accounterrorhistory.FieldModel, accounterrorhistory.FieldSource, accounterrorhistory.FieldMessage, accounterrorhistory.FieldFingerprint:
			values[i] = new(sql.NullString)
		case accounterrorhistory.FieldCreatedAt, accounterrorhistory.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccountErrorHistory fields.
func (_m *AccountErrorHistory) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accounterrorhistory.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case accounterrorhistory.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case accounterrorhistory.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = new(int64)
				*_m.UserID = value.Int64
			}
		case accounterrorhistory.FieldUserEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_email", values[i])
			} else if value.Valid {
				_m.UserEmail = new(string)
				*_m.UserEmail = value.String
			}
		case accounterrorhistory.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = new(string)
				*_m.Model = value.String
			}
		case accounterrorhistory.FieldUpstreamStatusCode:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_status_code", values[i])
			} else if value.Valid {
				_m.UpstreamStatusCode = new(int)
				*_m.UpstreamStatusCode = int(value.Int64)
			}
		case accounterrorhistory.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = accounterrorhistory.Source(value.String)
			}
		case accounterrorhistory.FieldMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message", values[i])
			} else if value.Valid {
				_m.Message = value.String
			}
		case accounterrorhistory.FieldFingerprint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field fingerprint", values[i])
			} else if value.Valid {
				_m.Fingerprint = value.String
			}
		case accounterrorhistory.FieldDupCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field dup_count", values[i])
			} else if value.Valid {
				_m.DupCount = int(value.Int64)
			}
		case accounterrorhistory.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case accounterrorhistory.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AccountErrorHistory.
// This includes values selected through modifiers, order, etc.
func (_m *AccountErrorHistory) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAccount queries the "account" edge of the AccountErrorHistory entity.
func (_m *AccountErrorHistory) QueryAccount() *AccountQuery {
	return NewAccountErrorHistoryClient(_m.config).QueryAccount(_m)
}

// Update returns a builder for updating this AccountErrorHistory.
// Note that you need to call AccountErrorHistory.Unwrap() before calling this method if this AccountErrorHistory
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AccountErrorHistory) Update() *AccountErrorHistoryUpdateOne {
	return NewAccountErrorHistoryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AccountErrorHistory entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AccountErrorHistory) Unwrap() *AccountErrorHistory {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AccountErrorHistory is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AccountErrorHistory) String() string {
	var builder strings.Builder
	builder.WriteString("AccountErrorHistory(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	if v := _m.UserID; v != nil {
		builder.WriteString("user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UserEmail; v != nil {
		builder.WriteString("user_email=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Model; v != nil {
		builder.WriteString("model=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.UpstreamStatusCode; v != nil {
		builder.WriteString("upstream_status_code=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(fmt.Sprintf("%v", _m.Source))
	builder.WriteString(", ")
	builder.WriteString("message=")
	builder.WriteString(_m.Message)
	builder.WriteString(", ")
	builder.WriteString("fingerprint=")
	builder.WriteString(_m.Fingerprint)
	builder.WriteString(", ")
	builder.WriteString("dup_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.DupCount))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AccountErrorHistories is a parsable slice of AccountErrorHistory.
type AccountErrorHistories []*AccountErrorHistory
