// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accounterrorhistory"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AccountErrorHistoryDelete is the builder for deleting a AccountErrorHistory entity.
type AccountErrorHistoryDelete struct {
	config
	hooks    []Hook
	mutation *AccountErrorHistoryMutation
}

// Where appends a list predicates to the AccountErrorHistoryDelete builder.
func (_d *AccountErrorHistoryDelete) Where(ps ...predicate.AccountErrorHistory) *AccountErrorHistoryDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AccountErrorHistoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccountErrorHistoryDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AccountErrorHistoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(accounterrorhistory.Table, sqlgraph.NewFieldSpec(accounterrorhistory.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AccountErrorHistoryDeleteOne is the builder for deleting a single AccountErrorHistory entity.
type AccountErrorHistoryDeleteOne struct {
	_d *AccountErrorHistoryDelete
}

// Where appends a list predicates to the AccountErrorHistoryDelete builder.
func (_d *AccountErrorHistoryDeleteOne) Where(ps ...predicate.AccountErrorHistory) *AccountErrorHistoryDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AccountErrorHistoryDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{accounterrorhistory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccountErrorHistoryDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
