// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/balancedebitclient"
)

// BalanceDebitClient is the model entity for the BalanceDebitClient schema.
type BalanceDebitClient struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ClientID holds the value of the "client_id" field.
	ClientID string `json:"client_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// SecretHash holds the value of the "secret_hash" field.
	SecretHash string `json:"secret_hash,omitempty"`
	// SecretPrefix holds the value of the "secret_prefix" field.
	SecretPrefix string `json:"secret_prefix,omitempty"`
	// AllowedPurposes holds the value of the "allowed_purposes" field.
	AllowedPurposes []string `json:"allowed_purposes,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// LastUsedAt holds the value of the "last_used_at" field.
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BalanceDebitClientQuery when eager-loading is set.
	Edges        BalanceDebitClientEdges `json:"edges"`
	selectValues sql.SelectValues
}

// BalanceDebitClientEdges holds the relations/edges for other nodes in the graph.
type BalanceDebitClientEdges struct {
	// Transactions holds the value of the transactions edge.
	Transactions []*BalanceDebitTransaction `json:"transactions,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TransactionsOrErr returns the Transactions value or an error if the edge
// was not loaded in eager-loading.
func (e BalanceDebitClientEdges) TransactionsOrErr() ([]*BalanceDebitTransaction, error) {
	if e.loadedTypes[0] {
		return e.Transactions, nil
	}
	return nil, &NotLoadedError{edge: "transactions"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BalanceDebitClient) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case balancedebitclient.FieldAllowedPurposes:
			values[i] = new([]byte)
		case balancedebitclient.FieldID:
			values[i] = new(sql.NullInt64)
		case balancedebitclient.FieldClientID, balancedebitclient.FieldName, balancedebitclient.FieldSecretHash, balancedebitclient.FieldSecretPrefix, balancedebitclient.FieldStatus:
			values[i] = new(sql.NullString)
		case balancedebitclient.FieldCreatedAt, balancedebitclient.FieldUpdatedAt, balancedebitclient.FieldLastUsedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BalanceDebitClient fields.
func (_m *BalanceDebitClient) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case balancedebitclient.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case balancedebitclient.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case balancedebitclient.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case balancedebitclient.FieldClientID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_id", values[i])
			} else if value.Valid {
				_m.ClientID = value.String
			}
		case balancedebitclient.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case balancedebitclient.FieldSecretHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field secret_hash", values[i])
			} else if value.Valid {
				_m.SecretHash = value.String
			}
		case balancedebitclient.FieldSecretPrefix:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field secret_prefix", values[i])
			} else if value.Valid {
				_m.SecretPrefix = value.String
			}
		case balancedebitclient.FieldAllowedPurposes:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field allowed_purposes", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.AllowedPurposes); err != nil {
					return fmt.Errorf("unmarshal field allowed_purposes: %w", err)
				}
			}
		case balancedebitclient.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case balancedebitclient.FieldLastUsedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_used_at", values[i])
			} else if value.Valid {
				_m.LastUsedAt = new(time.Time)
				*_m.LastUsedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BalanceDebitClient.
// This includes values selected through modifiers, order, etc.
func (_m *BalanceDebitClient) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTransactions queries the "transactions" edge of the BalanceDebitClient entity.
func (_m *BalanceDebitClient) QueryTransactions() *BalanceDebitTransactionQuery {
	return NewBalanceDebitClientClient(_m.config).QueryTransactions(_m)
}

// Update returns a builder for updating this BalanceDebitClient.
// Note that you need to call BalanceDebitClient.Unwrap() before calling this method if this BalanceDebitClient
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BalanceDebitClient) Update() *BalanceDebitClientUpdateOne {
	return NewBalanceDebitClientClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BalanceDebitClient entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BalanceDebitClient) Unwrap() *BalanceDebitClient {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BalanceDebitClient is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BalanceDebitClient) String() string {
	var builder strings.Builder
	builder.WriteString("BalanceDebitClient(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("client_id=")
	builder.WriteString(_m.ClientID)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("secret_hash=")
	builder.WriteString(_m.SecretHash)
	builder.WriteString(", ")
	builder.WriteString("secret_prefix=")
	builder.WriteString(_m.SecretPrefix)
	builder.WriteString(", ")
	builder.WriteString("allowed_purposes=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllowedPurposes))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.LastUsedAt; v != nil {
		builder.WriteString("last_used_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// BalanceDebitClients is a parsable slice of BalanceDebitClient.
type BalanceDebitClients []*BalanceDebitClient
