// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/balancedebitclient"
	"github.com/Wei-Shaw/sub2api/ent/balancedebittransaction"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// BalanceDebitTransactionUpdate is the builder for updating BalanceDebitTransaction entities.
type BalanceDebitTransactionUpdate struct {
	config
	hooks    []Hook
	mutation *BalanceDebitTransactionMutation
}

// Where appends a list predicates to the BalanceDebitTransactionUpdate builder.
func (_u *BalanceDebitTransactionUpdate) Where(ps ...predicate.BalanceDebitTransaction) *BalanceDebitTransactionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTxnID sets the "txn_id" field.
func (_u *BalanceDebitTransactionUpdate) SetTxnID(v string) *BalanceDebitTransactionUpdate {
	_u.mutation.SetTxnID(v)
	return _u
}

// SetNillableTxnID sets the "txn_id" field if the given value is not nil.
func (_u *BalanceDebitTransactionUpdate) SetNillableTxnID(v *string) *BalanceDebitTransactionUpdate {
	if v != nil {
		_u.SetTxnID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *BalanceDebitTransactionUpdate) SetUserID(v int64) *BalanceDebitTransactionUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *BalanceDebitTransactionUpdate) SetNillableUserID(v *int64) *BalanceDebitTransactionUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *BalanceDebitTransactionUpdate) AddUserID(v int64) *BalanceDebitTransactionUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetBalanceClientID sets the "balance_client_id" field.
func (_u *BalanceDebitTransactionUpdate) SetBalanceClientID(v int64) *BalanceDebitTransactionUpdate {
	_u.mutation.SetBalanceClientID(v)
	return _u
}

// SetNillableBalanceClientID sets the "balance_client_id" field if the given value is not nil.
func (_u *BalanceDebitTransactionUpdate) SetNillableBalanceClientID(v *int64) *BalanceDebitTransactionUpdate {
	if v != nil {
		_u.SetBalanceClientID(*v)
	}
	return _u
}

// SetIdempotencyKeyHash sets the "idempotency_key_hash" field.
func (_u *BalanceDebitTransactionUpdate) SetIdempotencyKeyHash(v string) *BalanceDebitTransactionUpdate {
	_u.mutation.SetIdempotencyKeyHash(v)
	return _u
}

// SetNillableIdempotencyKeyHash sets the "idempotency_key_hash" field if the given value is not nil.
func (_u *BalanceDebitTransactionUpdate) SetNillableIdempotencyKeyHash(v *string) *BalanceDebitTransactionUpdate {
	if v != nil {
		_u.SetIdempotencyKeyHash(*v)
	}
	return _u
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (_u *BalanceDebitTransactionUpdate) SetRequestFingerprint(v string) *BalanceDebitTransactionUpdate {
	_u.mutation.SetRequestFingerprint(v)
	return _u
}

// SetNillableRequestFingerprint sets the "request_fingerprint" field if the given value is not nil.
func (_u *BalanceDebitTransactionUpdate) SetNillableRequestFingerprint(v *string) *BalanceDebitTransactionUpdate {
	if v != nil {
		_u.SetRequestFingerprint(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *BalanceDebitTransactionUpdate) SetAmount(v float64) *BalanceDebitTransactionUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *BalanceDebitTransactionUpdate) SetNillableAmount(v *float64) *BalanceDebitTransactionUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *BalanceDebitTransactionUpdate) AddAmount(v float64) *BalanceDebitTransactionUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *BalanceDebitTransactionUpdate) SetCurrency(v string) *BalanceDebitTransactionUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *BalanceDebitTransactionUpdate) SetNillableCurrency(v *string) *BalanceDebitTransactionUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetPurpose sets the "purpose" field.
func (_u *BalanceDebitTransactionUpdate) SetPurpose(v string) *BalanceDebitTransactionUpdate {
	_u.mutation.SetPurpose(v)
	return _u
}

// SetNillablePurpose sets the "purpose" field if the given value is not nil.
func (_u *BalanceDebitTransactionUpdate) SetNillablePurpose(v *string) *BalanceDebitTransactionUpdate {
	if v != nil {
		_u.SetPurpose(*v)
	}
	return _u
}

// SetRef sets the "ref" field.
func (_u *BalanceDebitTransactionUpdate) SetRef(v string) *BalanceDebitTransactionUpdate {
	_u.mutation.SetRef(v)
	return _u
}

// SetNillableRef sets the "ref" field if the given value is not nil.
func (_u *BalanceDebitTransactionUpdate) SetNillableRef(v *string) *BalanceDebitTransactionUpdate {
	if v != nil {
		_u.SetRef(*v)
	}
	return _u
}

// SetBalanceBefore sets the "balance_before" field.
func (_u *BalanceDebitTransactionUpdate) SetBalanceBefore(v float64) *BalanceDebitTransactionUpdate {
	_u.mutation.ResetBalanceBefore()
	_u.mutation.SetBalanceBefore(v)
	return _u
}

// SetNillableBalanceBefore sets the "balance_before" field if the given value is not nil.
func (_u *BalanceDebitTransactionUpdate) SetNillableBalanceBefore(v *float64) *BalanceDebitTransactionUpdate {
	if v != nil {
		_u.SetBalanceBefore(*v)
	}
	return _u
}

// AddBalanceBefore adds value to the "balance_before" field.
func (_u *BalanceDebitTransactionUpdate) AddBalanceBefore(v float64) *BalanceDebitTransactionUpdate {
	_u.mutation.AddBalanceBefore(v)
	return _u
}

// SetBalanceAfter sets the "balance_after" field.
func (_u *BalanceDebitTransactionUpdate) SetBalanceAfter(v float64) *BalanceDebitTransactionUpdate {
	_u.mutation.ResetBalanceAfter()
	_u.mutation.SetBalanceAfter(v)
	return _u
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_u *BalanceDebitTransactionUpdate) SetNillableBalanceAfter(v *float64) *BalanceDebitTransactionUpdate {
	if v != nil {
		_u.SetBalanceAfter(*v)
	}
	return _u
}

// AddBalanceAfter adds value to the "balance_after" field.
func (_u *BalanceDebitTransactionUpdate) AddBalanceAfter(v float64) *BalanceDebitTransactionUpdate {
	_u.mutation.AddBalanceAfter(v)
	return _u
}

// SetClientID sets the "client" edge to the BalanceDebitClient entity by ID.
func (_u *BalanceDebitTransactionUpdate) SetClientID(id int64) *BalanceDebitTransactionUpdate {
	_u.mutation.SetClientID(id)
	return _u
}

// SetClient sets the "client" edge to the BalanceDebitClient entity.
func (_u *BalanceDebitTransactionUpdate) SetClient(v *BalanceDebitClient) *BalanceDebitTransactionUpdate {
	return _u.SetClientID(v.ID)
}

// Mutation returns the BalanceDebitTransactionMutation object of the builder.
func (_u *BalanceDebitTransactionUpdate) Mutation() *BalanceDebitTransactionMutation {
	return _u.mutation
}

// ClearClient clears the "client" edge to the BalanceDebitClient entity.
func (_u *BalanceDebitTransactionUpdate) ClearClient() *BalanceDebitTransactionUpdate {
	_u.mutation.ClearClient()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BalanceDebitTransactionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BalanceDebitTransactionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BalanceDebitTransactionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BalanceDebitTransactionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BalanceDebitTransactionUpdate) check() error {
	if v, ok := _u.mutation.IdempotencyKeyHash(); ok {
		if err := balancedebittransaction.IdempotencyKeyHashValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key_hash", err: fmt.Errorf(`ent: validator failed for field "BalanceDebitTransaction.idempotency_key_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestFingerprint(); ok {
		if err := balancedebittransaction.RequestFingerprintValidator(v); err != nil {
			return &ValidationError{Name: "request_fingerprint", err: fmt.Errorf(`ent: validator failed for field "BalanceDebitTransaction.request_fingerprint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := balancedebittransaction.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "BalanceDebitTransaction.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Purpose(); ok {
		if err := balancedebittransaction.PurposeValidator(v); err != nil {
			return &ValidationError{Name: "purpose", err: fmt.Errorf(`ent: validator failed for field "BalanceDebitTransaction.purpose": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Ref(); ok {
		if err := balancedebittransaction.RefValidator(v); err != nil {
			return &ValidationError{Name: "ref", err: fmt.Errorf(`ent: validator failed for field "BalanceDebitTransaction.ref": %w`, err)}
		}
	}
	if _u.mutation.ClientCleared() && len(_u.mutation.ClientIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BalanceDebitTransaction.client"`)
	}
	return nil
}

func (_u *BalanceDebitTransactionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(balancedebittransaction.Table, balancedebittransaction.Columns, sqlgraph.NewFieldSpec(balancedebittransaction.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TxnID(); ok {
		_spec.SetField(balancedebittransaction.FieldTxnID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(balancedebittransaction.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(balancedebittransaction.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.IdempotencyKeyHash(); ok {
		_spec.SetField(balancedebittransaction.FieldIdempotencyKeyHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestFingerprint(); ok {
		_spec.SetField(balancedebittransaction.FieldRequestFingerprint, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(balancedebittransaction.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(balancedebittransaction.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(balancedebittransaction.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Purpose(); ok {
		_spec.SetField(balancedebittransaction.FieldPurpose, field.TypeString, value)
	}
	if value, ok := _u.mutation.Ref(); ok {
		_spec.SetField(balancedebittransaction.FieldRef, field.TypeString, value)
	}
	if value, ok := _u.mutation.BalanceBefore(); ok {
		_spec.SetField(balancedebittransaction.FieldBalanceBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceBefore(); ok {
		_spec.AddField(balancedebittransaction.FieldBalanceBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceAfter(); ok {
		_spec.SetField(balancedebittransaction.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfter(); ok {
		_spec.AddField(balancedebittransaction.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if _u.mutation.ClientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   balancedebittransaction.ClientTable,
			Columns: []string{balancedebittransaction.ClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(balancedebitclient.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   balancedebittransaction.ClientTable,
			Columns: []string{balancedebittransaction.ClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(balancedebitclient.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{balancedebittransaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BalanceDebitTransactionUpdateOne is the builder for updating a single BalanceDebitTransaction entity.
type BalanceDebitTransactionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BalanceDebitTransactionMutation
}

// SetTxnID sets the "txn_id" field.
func (_u *BalanceDebitTransactionUpdateOne) SetTxnID(v string) *BalanceDebitTransactionUpdateOne {
	_u.mutation.SetTxnID(v)
	return _u
}

// SetNillableTxnID sets the "txn_id" field if the given value is not nil.
func (_u *BalanceDebitTransactionUpdateOne) SetNillableTxnID(v *string) *BalanceDebitTransactionUpdateOne {
	if v != nil {
		_u.SetTxnID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *BalanceDebitTransactionUpdateOne) SetUserID(v int64) *BalanceDebitTransactionUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *BalanceDebitTransactionUpdateOne) SetNillableUserID(v *int64) *BalanceDebitTransactionUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *BalanceDebitTransactionUpdateOne) AddUserID(v int64) *BalanceDebitTransactionUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetBalanceClientID sets the "balance_client_id" field.
func (_u *BalanceDebitTransactionUpdateOne) SetBalanceClientID(v int64) *BalanceDebitTransactionUpdateOne {
	_u.mutation.SetBalanceClientID(v)
	return _u
}

// SetNillableBalanceClientID sets the "balance_client_id" field if the given value is not nil.
func (_u *BalanceDebitTransactionUpdateOne) SetNillableBalanceClientID(v *int64) *BalanceDebitTransactionUpdateOne {
	if v != nil {
		_u.SetBalanceClientID(*v)
	}
	return _u
}

// SetIdempotencyKeyHash sets the "idempotency_key_hash" field.
func (_u *BalanceDebitTransactionUpdateOne) SetIdempotencyKeyHash(v string) *BalanceDebitTransactionUpdateOne {
	_u.mutation.SetIdempotencyKeyHash(v)
	return _u
}

// SetNillableIdempotencyKeyHash sets the "idempotency_key_hash" field if the given value is not nil.
func (_u *BalanceDebitTransactionUpdateOne) SetNillableIdempotencyKeyHash(v *string) *BalanceDebitTransactionUpdateOne {
	if v != nil {
		_u.SetIdempotencyKeyHash(*v)
	}
	return _u
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (_u *BalanceDebitTransactionUpdateOne) SetRequestFingerprint(v string) *BalanceDebitTransactionUpdateOne {
	_u.mutation.SetRequestFingerprint(v)
	return _u
}

// SetNillableRequestFingerprint sets the "request_fingerprint" field if the given value is not nil.
func (_u *BalanceDebitTransactionUpdateOne) SetNillableRequestFingerprint(v *string) *BalanceDebitTransactionUpdateOne {
	if v != nil {
		_u.SetRequestFingerprint(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *BalanceDebitTransactionUpdateOne) SetAmount(v float64) *BalanceDebitTransactionUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *BalanceDebitTransactionUpdateOne) SetNillableAmount(v *float64) *BalanceDebitTransactionUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *BalanceDebitTransactionUpdateOne) AddAmount(v float64) *BalanceDebitTransactionUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *BalanceDebitTransactionUpdateOne) SetCurrency(v string) *BalanceDebitTransactionUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *BalanceDebitTransactionUpdateOne) SetNillableCurrency(v *string) *BalanceDebitTransactionUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetPurpose sets the "purpose" field.
func (_u *BalanceDebitTransactionUpdateOne) SetPurpose(v string) *BalanceDebitTransactionUpdateOne {
	_u.mutation.SetPurpose(v)
	return _u
}

// SetNillablePurpose sets the "purpose" field if the given value is not nil.
func (_u *BalanceDebitTransactionUpdateOne) SetNillablePurpose(v *string) *BalanceDebitTransactionUpdateOne {
	if v != nil {
		_u.SetPurpose(*v)
	}
	return _u
}

// SetRef sets the "ref" field.
func (_u *BalanceDebitTransactionUpdateOne) SetRef(v string) *BalanceDebitTransactionUpdateOne {
	_u.mutation.SetRef(v)
	return _u
}

// SetNillableRef sets the "ref" field if the given value is not nil.
func (_u *BalanceDebitTransactionUpdateOne) SetNillableRef(v *string) *BalanceDebitTransactionUpdateOne {
	if v != nil {
		_u.SetRef(*v)
	}
	return _u
}

// SetBalanceBefore sets the "balance_before" field.
func (_u *BalanceDebitTransactionUpdateOne) SetBalanceBefore(v float64) *BalanceDebitTransactionUpdateOne {
	_u.mutation.ResetBalanceBefore()
	_u.mutation.SetBalanceBefore(v)
	return _u
}

// SetNillableBalanceBefore sets the "balance_before" field if the given value is not nil.
func (_u *BalanceDebitTransactionUpdateOne) SetNillableBalanceBefore(v *float64) *BalanceDebitTransactionUpdateOne {
	if v != nil {
		_u.SetBalanceBefore(*v)
	}
	return _u
}

// AddBalanceBefore adds value to the "balance_before" field.
func (_u *BalanceDebitTransactionUpdateOne) AddBalanceBefore(v float64) *BalanceDebitTransactionUpdateOne {
	_u.mutation.AddBalanceBefore(v)
	return _u
}

// SetBalanceAfter sets the "balance_after" field.
func (_u *BalanceDebitTransactionUpdateOne) SetBalanceAfter(v float64) *BalanceDebitTransactionUpdateOne {
	_u.mutation.ResetBalanceAfter()
	_u.mutation.SetBalanceAfter(v)
	return _u
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_u *BalanceDebitTransactionUpdateOne) SetNillableBalanceAfter(v *float64) *BalanceDebitTransactionUpdateOne {
	if v != nil {
		_u.SetBalanceAfter(*v)
	}
	return _u
}

// AddBalanceAfter adds value to the "balance_after" field.
func (_u *BalanceDebitTransactionUpdateOne) AddBalanceAfter(v float64) *BalanceDebitTransactionUpdateOne {
	_u.mutation.AddBalanceAfter(v)
	return _u
}

// SetClientID sets the "client" edge to the BalanceDebitClient entity by ID.
func (_u *BalanceDebitTransactionUpdateOne) SetClientID(id int64) *BalanceDebitTransactionUpdateOne {
	_u.mutation.SetClientID(id)
	return _u
}

// SetClient sets the "client" edge to the BalanceDebitClient entity.
func (_u *BalanceDebitTransactionUpdateOne) SetClient(v *BalanceDebitClient) *BalanceDebitTransactionUpdateOne {
	return _u.SetClientID(v.ID)
}

// Mutation returns the BalanceDebitTransactionMutation object of the builder.
func (_u *BalanceDebitTransactionUpdateOne) Mutation() *BalanceDebitTransactionMutation {
	return _u.mutation
}

// ClearClient clears the "client" edge to the BalanceDebitClient entity.
func (_u *BalanceDebitTransactionUpdateOne) ClearClient() *BalanceDebitTransactionUpdateOne {
	_u.mutation.ClearClient()
	return _u
}

// Where appends a list predicates to the BalanceDebitTransactionUpdate builder.
func (_u *BalanceDebitTransactionUpdateOne) Where(ps ...predicate.BalanceDebitTransaction) *BalanceDebitTransactionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BalanceDebitTransactionUpdateOne) Select(field string, fields ...string) *BalanceDebitTransactionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BalanceDebitTransaction entity.
func (_u *BalanceDebitTransactionUpdateOne) Save(ctx context.Context) (*BalanceDebitTransaction, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BalanceDebitTransactionUpdateOne) SaveX(ctx context.Context) *BalanceDebitTransaction {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BalanceDebitTransactionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BalanceDebitTransactionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BalanceDebitTransactionUpdateOne) check() error {
	if v, ok := _u.mutation.IdempotencyKeyHash(); ok {
		if err := balancedebittransaction.IdempotencyKeyHashValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key_hash", err: fmt.Errorf(`ent: validator failed for field "BalanceDebitTransaction.idempotency_key_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestFingerprint(); ok {
		if err := balancedebittransaction.RequestFingerprintValidator(v); err != nil {
			return &ValidationError{Name: "request_fingerprint", err: fmt.Errorf(`ent: validator failed for field "BalanceDebitTransaction.request_fingerprint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := balancedebittransaction.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "BalanceDebitTransaction.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Purpose(); ok {
		if err := balancedebittransaction.PurposeValidator(v); err != nil {
			return &ValidationError{Name: "purpose", err: fmt.Errorf(`ent: validator failed for field "BalanceDebitTransaction.purpose": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Ref(); ok {
		if err := balancedebittransaction.RefValidator(v); err != nil {
			return &ValidationError{Name: "ref", err: fmt.Errorf(`ent: validator failed for field "BalanceDebitTransaction.ref": %w`, err)}
		}
	}
	if _u.mutation.ClientCleared() && len(_u.mutation.ClientIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BalanceDebitTransaction.client"`)
	}
	return nil
}

func (_u *BalanceDebitTransactionUpdateOne) sqlSave(ctx context.Context) (_node *BalanceDebitTransaction, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(balancedebittransaction.Table, balancedebittransaction.Columns, sqlgraph.NewFieldSpec(balancedebittransaction.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BalanceDebitTransaction.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, balancedebittransaction.FieldID)
		for _, f := range fields {
			if !balancedebittransaction.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != balancedebittransaction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TxnID(); ok {
		_spec.SetField(balancedebittransaction.FieldTxnID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(balancedebittransaction.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(balancedebittransaction.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.IdempotencyKeyHash(); ok {
		_spec.SetField(balancedebittransaction.FieldIdempotencyKeyHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestFingerprint(); ok {
		_spec.SetField(balancedebittransaction.FieldRequestFingerprint, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(balancedebittransaction.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(balancedebittransaction.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(balancedebittransaction.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Purpose(); ok {
		_spec.SetField(balancedebittransaction.FieldPurpose, field.TypeString, value)
	}
	if value, ok := _u.mutation.Ref(); ok {
		_spec.SetField(balancedebittransaction.FieldRef, field.TypeString, value)
	}
	if value, ok := _u.mutation.BalanceBefore(); ok {
		_spec.SetField(balancedebittransaction.FieldBalanceBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceBefore(); ok {
		_spec.AddField(balancedebittransaction.FieldBalanceBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceAfter(); ok {
		_spec.SetField(balancedebittransaction.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfter(); ok {
		_spec.AddField(balancedebittransaction.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if _u.mutation.ClientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   balancedebittransaction.ClientTable,
			Columns: []string{balancedebittransaction.ClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(balancedebitclient.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   balancedebittransaction.ClientTable,
			Columns: []string{balancedebittransaction.ClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(balancedebitclient.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &BalanceDebitTransaction{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{balancedebittransaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
