// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/balancedebitclient"
	"github.com/Wei-Shaw/sub2api/ent/balancedebittransaction"
)

// BalanceDebitTransactionCreate is the builder for creating a BalanceDebitTransaction entity.
type BalanceDebitTransactionCreate struct {
	config
	mutation *BalanceDebitTransactionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTxnID sets the "txn_id" field.
func (_c *BalanceDebitTransactionCreate) SetTxnID(v string) *BalanceDebitTransactionCreate {
	_c.mutation.SetTxnID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *BalanceDebitTransactionCreate) SetUserID(v int64) *BalanceDebitTransactionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetBalanceClientID sets the "balance_client_id" field.
func (_c *BalanceDebitTransactionCreate) SetBalanceClientID(v int64) *BalanceDebitTransactionCreate {
	_c.mutation.SetBalanceClientID(v)
	return _c
}

// SetIdempotencyKeyHash sets the "idempotency_key_hash" field.
func (_c *BalanceDebitTransactionCreate) SetIdempotencyKeyHash(v string) *BalanceDebitTransactionCreate {
	_c.mutation.SetIdempotencyKeyHash(v)
	return _c
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (_c *BalanceDebitTransactionCreate) SetRequestFingerprint(v string) *BalanceDebitTransactionCreate {
	_c.mutation.SetRequestFingerprint(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *BalanceDebitTransactionCreate) SetAmount(v float64) *BalanceDebitTransactionCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *BalanceDebitTransactionCreate) SetCurrency(v string) *BalanceDebitTransactionCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetPurpose sets the "purpose" field.
func (_c *BalanceDebitTransactionCreate) SetPurpose(v string) *BalanceDebitTransactionCreate {
	_c.mutation.SetPurpose(v)
	return _c
}

// SetRef sets the "ref" field.
func (_c *BalanceDebitTransactionCreate) SetRef(v string) *BalanceDebitTransactionCreate {
	_c.mutation.SetRef(v)
	return _c
}

// SetBalanceBefore sets the "balance_before" field.
func (_c *BalanceDebitTransactionCreate) SetBalanceBefore(v float64) *BalanceDebitTransactionCreate {
	_c.mutation.SetBalanceBefore(v)
	return _c
}

// SetBalanceAfter sets the "balance_after" field.
func (_c *BalanceDebitTransactionCreate) SetBalanceAfter(v float64) *BalanceDebitTransactionCreate {
	_c.mutation.SetBalanceAfter(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *BalanceDebitTransactionCreate) SetCreatedAt(v time.Time) *BalanceDebitTransactionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BalanceDebitTransactionCreate) SetNillableCreatedAt(v *time.Time) *BalanceDebitTransactionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetClientID sets the "client" edge to the BalanceDebitClient entity by ID.
func (_c *BalanceDebitTransactionCreate) SetClientID(id int64) *BalanceDebitTransactionCreate {
	_c.mutation.SetClientID(id)
	return _c
}

// SetClient sets the "client" edge to the BalanceDebitClient entity.
func (_c *BalanceDebitTransactionCreate) SetClient(v *BalanceDebitClient) *BalanceDebitTransactionCreate {
	return _c.SetClientID(v.ID)
}

// Mutation returns the BalanceDebitTransactionMutation object of the builder.
func (_c *BalanceDebitTransactionCreate) Mutation() *BalanceDebitTransactionMutation {
	return _c.mutation
}

// Save creates the BalanceDebitTransaction in the database.
func (_c *BalanceDebitTransactionCreate) Save(ctx context.Context) (*BalanceDebitTransaction, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BalanceDebitTransactionCreate) SaveX(ctx context.Context) *BalanceDebitTransaction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BalanceDebitTransactionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BalanceDebitTransactionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BalanceDebitTransactionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := balancedebittransaction.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BalanceDebitTransactionCreate) check() error {
	if _, ok := _c.mutation.TxnID(); !ok {
		return &ValidationError{Name: "txn_id", err: errors.New(`ent: missing required field "BalanceDebitTransaction.txn_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "BalanceDebitTransaction.user_id"`)}
	}
	if _, ok := _c.mutation.BalanceClientID(); !ok {
		return &ValidationError{Name: "balance_client_id", err: errors.New(`ent: missing required field "BalanceDebitTransaction.balance_client_id"`)}
	}
	if _, ok := _c.mutation.IdempotencyKeyHash(); !ok {
		return &ValidationError{Name: "idempotency_key_hash", err: errors.New(`ent: missing required field "BalanceDebitTransaction.idempotency_key_hash"`)}
	}
	if v, ok := _c.mutation.IdempotencyKeyHash(); ok {
		if err := balancedebittransaction.IdempotencyKeyHashValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key_hash", err: fmt.Errorf(`ent: validator failed for field "BalanceDebitTransaction.idempotency_key_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequestFingerprint(); !ok {
		return &ValidationError{Name: "request_fingerprint", err: errors.New(`ent: missing required field "BalanceDebitTransaction.request_fingerprint"`)}
	}
	if v, ok := _c.mutation.RequestFingerprint(); ok {
		if err := balancedebittransaction.RequestFingerprintValidator(v); err != nil {
			return &ValidationError{Name: "request_fingerprint", err: fmt.Errorf(`ent: validator failed for field "BalanceDebitTransaction.request_fingerprint": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "BalanceDebitTransaction.amount"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "BalanceDebitTransaction.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := balancedebittransaction.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "BalanceDebitTransaction.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Purpose(); !ok {
		return &ValidationError{Name: "purpose", err: errors.New(`ent: missing required field "BalanceDebitTransaction.purpose"`)}
	}
	if v, ok := _c.mutation.Purpose(); ok {
		if err := balancedebittransaction.PurposeValidator(v); err != nil {
			return &ValidationError{Name: "purpose", err: fmt.Errorf(`ent: validator failed for field "BalanceDebitTransaction.purpose": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Ref(); !ok {
		return &ValidationError{Name: "ref", err: errors.New(`ent: missing required field "BalanceDebitTransaction.ref"`)}
	}
	if v, ok := _c.mutation.Ref(); ok {
		if err := balancedebittransaction.RefValidator(v); err != nil {
			return &ValidationError{Name: "ref", err: fmt.Errorf(`ent: validator failed for field "BalanceDebitTransaction.ref": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BalanceBefore(); !ok {
		return &ValidationError{Name: "balance_before", err: errors.New(`ent: missing required field "BalanceDebitTransaction.balance_before"`)}
	}
	if _, ok := _c.mutation.BalanceAfter(); !ok {
		return &ValidationError{Name: "balance_after", err: errors.New(`ent: missing required field "BalanceDebitTransaction.balance_after"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BalanceDebitTransaction.created_at"`)}
	}
	if len(_c.mutation.ClientIDs()) == 0 {
		return &ValidationError{Name: "client", err: errors.New(`ent: missing required edge "BalanceDebitTransaction.client"`)}
	}
	return nil
}

func (_c *BalanceDebitTransactionCreate) sqlSave(ctx context.Context) (*BalanceDebitTransaction, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BalanceDebitTransactionCreate) createSpec() (*BalanceDebitTransaction, *sqlgraph.CreateSpec) {
	var (
		_node = &BalanceDebitTransaction{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(balancedebittransaction.Table, sqlgraph.NewFieldSpec(balancedebittransaction.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.TxnID(); ok {
		_spec.SetField(balancedebittransaction.FieldTxnID, field.TypeString, value)
		_node.TxnID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(balancedebittransaction.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.IdempotencyKeyHash(); ok {
		_spec.SetField(balancedebittransaction.FieldIdempotencyKeyHash, field.TypeString, value)
		_node.IdempotencyKeyHash = value
	}
	if value, ok := _c.mutation.RequestFingerprint(); ok {
		_spec.SetField(balancedebittransaction.FieldRequestFingerprint, field.TypeString, value)
		_node.RequestFingerprint = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(balancedebittransaction.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(balancedebittransaction.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.Purpose(); ok {
		_spec.SetField(balancedebittransaction.FieldPurpose, field.TypeString, value)
		_node.Purpose = value
	}
	if value, ok := _c.mutation.Ref(); ok {
		_spec.SetField(balancedebittransaction.FieldRef, field.TypeString, value)
		_node.Ref = value
	}
	if value, ok := _c.mutation.BalanceBefore(); ok {
		_spec.SetField(balancedebittransaction.FieldBalanceBefore, field.TypeFloat64, value)
		_node.BalanceBefore = value
	}
	if value, ok := _c.mutation.BalanceAfter(); ok {
		_spec.SetField(balancedebittransaction.FieldBalanceAfter, field.TypeFloat64, value)
		_node.BalanceAfter = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(balancedebittransaction.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.ClientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   balancedebittransaction.ClientTable,
			Columns: []string{balancedebittransaction.ClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(balancedebitclient.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.BalanceClientID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BalanceDebitTransaction.Create().
//		SetTxnID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BalanceDebitTransactionUpsert) {
//			SetTxnID(v+v).
//		}).
//		Exec(ctx)
func (_c *BalanceDebitTransactionCreate) OnConflict(opts ...sql.ConflictOption) *BalanceDebitTransactionUpsertOne {
	_c.conflict = opts
	return &BalanceDebitTransactionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BalanceDebitTransaction.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BalanceDebitTransactionCreate) OnConflictColumns(columns ...string) *BalanceDebitTransactionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BalanceDebitTransactionUpsertOne{
		create: _c,
	}
}

type (
	// BalanceDebitTransactionUpsertOne is the builder for "upsert"-ing
	//  one BalanceDebitTransaction node.
	BalanceDebitTransactionUpsertOne struct {
		create *BalanceDebitTransactionCreate
	}

	// BalanceDebitTransactionUpsert is the "OnConflict" setter.
	BalanceDebitTransactionUpsert struct {
		*sql.UpdateSet
	}
)

// SetTxnID sets the "txn_id" field.
func (u *BalanceDebitTransactionUpsert) SetTxnID(v string) *BalanceDebitTransactionUpsert {
	u.Set(balancedebittransaction.FieldTxnID, v)
	return u
}

// UpdateTxnID sets the "txn_id" field to the value that was provided on create.
func (u *BalanceDebitTransactionUpsert) UpdateTxnID() *BalanceDebitTransactionUpsert {
	u.SetExcluded(balancedebittransaction.FieldTxnID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *BalanceDebitTransactionUpsert) SetUserID(v int64) *BalanceDebitTransactionUpsert {
	u.Set(balancedebittransaction.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *BalanceDebitTransactionUpsert) UpdateUserID() *BalanceDebitTransactionUpsert {
	u.SetExcluded(balancedebittransaction.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *BalanceDebitTransactionUpsert) AddUserID(v int64) *BalanceDebitTransactionUpsert {
	u.Add(balancedebittransaction.FieldUserID, v)
	return u
}

// SetBalanceClientID sets the "balance_client_id" field.
func (u *BalanceDebitTransactionUpsert) SetBalanceClientID(v int64) *BalanceDebitTransactionUpsert {
	u.Set(balancedebittransaction.FieldBalanceClientID, v)
	return u
}

// UpdateBalanceClientID sets the "balance_client_id" field to the value that was provided on create.
func (u *BalanceDebitTransactionUpsert) UpdateBalanceClientID() *BalanceDebitTransactionUpsert {
	u.SetExcluded(balancedebittransaction.FieldBalanceClientID)
	return u
}

// SetIdempotencyKeyHash sets the "idempotency_key_hash" field.
func (u *BalanceDebitTransactionUpsert) SetIdempotencyKeyHash(v string) *BalanceDebitTransactionUpsert {
	u.Set(balancedebittransaction.FieldIdempotencyKeyHash, v)
	return u
}

// UpdateIdempotencyKeyHash sets the "idempotency_key_hash" field to the value that was provided on create.
func (u *BalanceDebitTransactionUpsert) UpdateIdempotencyKeyHash() *BalanceDebitTransactionUpsert {
	u.SetExcluded(balancedebittransaction.FieldIdempotencyKeyHash)
	return u
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (u *BalanceDebitTransactionUpsert) SetRequestFingerprint(v string) *BalanceDebitTransactionUpsert {
	u.Set(balancedebittransaction.FieldRequestFingerprint, v)
	return u
}

// UpdateRequestFingerprint sets the "request_fingerprint" field to the value that was provided on create.
func (u *BalanceDebitTransactionUpsert) UpdateRequestFingerprint() *BalanceDebitTransactionUpsert {
	u.SetExcluded(balancedebittransaction.FieldRequestFingerprint)
	return u
}

// SetAmount sets the "amount" field.
func (u *BalanceDebitTransactionUpsert) SetAmount(v float64) *BalanceDebitTransactionUpsert {
	u.Set(balancedebittransaction.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *BalanceDebitTransactionUpsert) UpdateAmount() *BalanceDebitTransactionUpsert {
	u.SetExcluded(balancedebittransaction.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *BalanceDebitTransactionUpsert) AddAmount(v float64) *BalanceDebitTransactionUpsert {
	u.Add(balancedebittransaction.FieldAmount, v)
	return u
}

// SetCurrency sets the "currency" field.
func (u *BalanceDebitTransactionUpsert) SetCurrency(v string) *BalanceDebitTransactionUpsert {
	u.Set(balancedebittransaction.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *BalanceDebitTransactionUpsert) UpdateCurrency() *BalanceDebitTransactionUpsert {
	u.SetExcluded(balancedebittransaction.FieldCurrency)
	return u
}

// SetPurpose sets the "purpose" field.
func (u *BalanceDebitTransactionUpsert) SetPurpose(v string) *BalanceDebitTransactionUpsert {
	u.Set(balancedebittransaction.FieldPurpose, v)
	return u
}

// UpdatePurpose sets the "purpose" field to the value that was provided on create.
func (u *BalanceDebitTransactionUpsert) UpdatePurpose() *BalanceDebitTransactionUpsert {
	u.SetExcluded(balancedebittransaction.FieldPurpose)
	return u
}

// SetRef sets the "ref" field.
func (u *BalanceDebitTransactionUpsert) SetRef(v string) *BalanceDebitTransactionUpsert {
	u.Set(balancedebittransaction.FieldRef, v)
	return u
}

// UpdateRef sets the "ref" field to the value that was provided on create.
func (u *BalanceDebitTransactionUpsert) UpdateRef() *BalanceDebitTransactionUpsert {
	u.SetExcluded(balancedebittransaction.FieldRef)
	return u
}

// SetBalanceBefore sets the "balance_before" field.
func (u *BalanceDebitTransactionUpsert) SetBalanceBefore(v float64) *BalanceDebitTransactionUpsert {
	u.Set(balancedebittransaction.FieldBalanceBefore, v)
	return u
}

// UpdateBalanceBefore sets the "balance_before" field to the value that was provided on create.
func (u *BalanceDebitTransactionUpsert) UpdateBalanceBefore() *BalanceDebitTransactionUpsert {
	u.SetExcluded(balancedebittransaction.FieldBalanceBefore)
	return u
}

// AddBalanceBefore adds v to the "balance_before" field.
func (u *BalanceDebitTransactionUpsert) AddBalanceBefore(v float64) *BalanceDebitTransactionUpsert {
	u.Add(balancedebittransaction.FieldBalanceBefore, v)
	return u
}

// SetBalanceAfter sets the "balance_after" field.
func (u *BalanceDebitTransactionUpsert) SetBalanceAfter(v float64) *BalanceDebitTransactionUpsert {
	u.Set(balancedebittransaction.FieldBalanceAfter, v)
	return u
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *BalanceDebitTransactionUpsert) UpdateBalanceAfter() *BalanceDebitTransactionUpsert {
	u.SetExcluded(balancedebittransaction.FieldBalanceAfter)
	return u
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *BalanceDebitTransactionUpsert) AddBalanceAfter(v float64) *BalanceDebitTransactionUpsert {
	u.Add(balancedebittransaction.FieldBalanceAfter, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.BalanceDebitTransaction.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BalanceDebitTransactionUpsertOne) UpdateNewValues() *BalanceDebitTransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(balancedebittransaction.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BalanceDebitTransaction.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BalanceDebitTransactionUpsertOne) Ignore() *BalanceDebitTransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BalanceDebitTransactionUpsertOne) DoNothing() *BalanceDebitTransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BalanceDebitTransactionCreate.OnConflict
// documentation for more info.
func (u *BalanceDebitTransactionUpsertOne) Update(set func(*BalanceDebitTransactionUpsert)) *BalanceDebitTransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BalanceDebitTransactionUpsert{UpdateSet: update})
	}))
	return u
}

// SetTxnID sets the "txn_id" field.
func (u *BalanceDebitTransactionUpsertOne) SetTxnID(v string) *BalanceDebitTransactionUpsertOne {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.SetTxnID(v)
	})
}

// UpdateTxnID sets the "txn_id" field to the value that was provided on create.
func (u *BalanceDebitTransactionUpsertOne) UpdateTxnID() *BalanceDebitTransactionUpsertOne {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.UpdateTxnID()
	})
}

// SetUserID sets the "user_id" field.
func (u *BalanceDebitTransactionUpsertOne) SetUserID(v int64) *BalanceDebitTransactionUpsertOne {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *BalanceDebitTransactionUpsertOne) AddUserID(v int64) *BalanceDebitTransactionUpsertOne {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *BalanceDebitTransactionUpsertOne) UpdateUserID() *BalanceDebitTransactionUpsertOne {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.UpdateUserID()
	})
}

// SetBalanceClientID sets the "balance_client_id" field.
func (u *BalanceDebitTransactionUpsertOne) SetBalanceClientID(v int64) *BalanceDebitTransactionUpsertOne {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.SetBalanceClientID(v)
	})
}

// UpdateBalanceClientID sets the "balance_client_id" field to the value that was provided on create.
func (u *BalanceDebitTransactionUpsertOne) UpdateBalanceClientID() *BalanceDebitTransactionUpsertOne {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.UpdateBalanceClientID()
	})
}

// SetIdempotencyKeyHash sets the "idempotency_key_hash" field.
func (u *BalanceDebitTransactionUpsertOne) SetIdempotencyKeyHash(v string) *BalanceDebitTransactionUpsertOne {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.SetIdempotencyKeyHash(v)
	})
}

// UpdateIdempotencyKeyHash sets the "idempotency_key_hash" field to the value that was provided on create.
func (u *BalanceDebitTransactionUpsertOne) UpdateIdempotencyKeyHash() *BalanceDebitTransactionUpsertOne {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.UpdateIdempotencyKeyHash()
	})
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (u *BalanceDebitTransactionUpsertOne) SetRequestFingerprint(v string) *BalanceDebitTransactionUpsertOne {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.SetRequestFingerprint(v)
	})
}

// UpdateRequestFingerprint sets the "request_fingerprint" field to the value that was provided on create.
func (u *BalanceDebitTransactionUpsertOne) UpdateRequestFingerprint() *BalanceDebitTransactionUpsertOne {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.UpdateRequestFingerprint()
	})
}

// SetAmount sets the "amount" field.
func (u *BalanceDebitTransactionUpsertOne) SetAmount(v float64) *BalanceDebitTransactionUpsertOne {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *BalanceDebitTransactionUpsertOne) AddAmount(v float64) *BalanceDebitTransactionUpsertOne {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *BalanceDebitTransactionUpsertOne) UpdateAmount() *BalanceDebitTransactionUpsertOne {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.UpdateAmount()
	})
}

// SetCurrency sets the "currency" field.
func (u *BalanceDebitTransactionUpsertOne) SetCurrency(v string) *BalanceDebitTransactionUpsertOne {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *BalanceDebitTransactionUpsertOne) UpdateCurrency() *BalanceDebitTransactionUpsertOne {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.UpdateCurrency()
	})
}

// SetPurpose sets the "purpose" field.
func (u *BalanceDebitTransactionUpsertOne) SetPurpose(v string) *BalanceDebitTransactionUpsertOne {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.SetPurpose(v)
	})
}

// UpdatePurpose sets the "purpose" field to the value that was provided on create.
func (u *BalanceDebitTransactionUpsertOne) UpdatePurpose() *BalanceDebitTransactionUpsertOne {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.UpdatePurpose()
	})
}

// SetRef sets the "ref" field.
func (u *BalanceDebitTransactionUpsertOne) SetRef(v string) *BalanceDebitTransactionUpsertOne {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.SetRef(v)
	})
}

// UpdateRef sets the "ref" field to the value that was provided on create.
func (u *BalanceDebitTransactionUpsertOne) UpdateRef() *BalanceDebitTransactionUpsertOne {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.UpdateRef()
	})
}

// SetBalanceBefore sets the "balance_before" field.
func (u *BalanceDebitTransactionUpsertOne) SetBalanceBefore(v float64) *BalanceDebitTransactionUpsertOne {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.SetBalanceBefore(v)
	})
}

// AddBalanceBefore adds v to the "balance_before" field.
func (u *BalanceDebitTransactionUpsertOne) AddBalanceBefore(v float64) *BalanceDebitTransactionUpsertOne {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.AddBalanceBefore(v)
	})
}

// UpdateBalanceBefore sets the "balance_before" field to the value that was provided on create.
func (u *BalanceDebitTransactionUpsertOne) UpdateBalanceBefore() *BalanceDebitTransactionUpsertOne {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.UpdateBalanceBefore()
	})
}

// SetBalanceAfter sets the "balance_after" field.
func (u *BalanceDebitTransactionUpsertOne) SetBalanceAfter(v float64) *BalanceDebitTransactionUpsertOne {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.SetBalanceAfter(v)
	})
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *BalanceDebitTransactionUpsertOne) AddBalanceAfter(v float64) *BalanceDebitTransactionUpsertOne {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.AddBalanceAfter(v)
	})
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *BalanceDebitTransactionUpsertOne) UpdateBalanceAfter() *BalanceDebitTransactionUpsertOne {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.UpdateBalanceAfter()
	})
}

// Exec executes the query.
func (u *BalanceDebitTransactionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BalanceDebitTransactionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BalanceDebitTransactionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BalanceDebitTransactionUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BalanceDebitTransactionUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BalanceDebitTransactionCreateBulk is the builder for creating many BalanceDebitTransaction entities in bulk.
type BalanceDebitTransactionCreateBulk struct {
	config
	err      error
	builders []*BalanceDebitTransactionCreate
	conflict []sql.ConflictOption
}

// Save creates the BalanceDebitTransaction entities in the database.
func (_c *BalanceDebitTransactionCreateBulk) Save(ctx context.Context) ([]*BalanceDebitTransaction, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BalanceDebitTransaction, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BalanceDebitTransactionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BalanceDebitTransactionCreateBulk) SaveX(ctx context.Context) []*BalanceDebitTransaction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BalanceDebitTransactionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BalanceDebitTransactionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BalanceDebitTransaction.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BalanceDebitTransactionUpsert) {
//			SetTxnID(v+v).
//		}).
//		Exec(ctx)
func (_c *BalanceDebitTransactionCreateBulk) OnConflict(opts ...sql.ConflictOption) *BalanceDebitTransactionUpsertBulk {
	_c.conflict = opts
	return &BalanceDebitTransactionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BalanceDebitTransaction.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BalanceDebitTransactionCreateBulk) OnConflictColumns(columns ...string) *BalanceDebitTransactionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BalanceDebitTransactionUpsertBulk{
		create: _c,
	}
}

// BalanceDebitTransactionUpsertBulk is the builder for "upsert"-ing
// a bulk of BalanceDebitTransaction nodes.
type BalanceDebitTransactionUpsertBulk struct {
	create *BalanceDebitTransactionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.BalanceDebitTransaction.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *BalanceDebitTransactionUpsertBulk) UpdateNewValues() *BalanceDebitTransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(balancedebittransaction.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BalanceDebitTransaction.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BalanceDebitTransactionUpsertBulk) Ignore() *BalanceDebitTransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BalanceDebitTransactionUpsertBulk) DoNothing() *BalanceDebitTransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BalanceDebitTransactionCreateBulk.OnConflict
// documentation for more info.
func (u *BalanceDebitTransactionUpsertBulk) Update(set func(*BalanceDebitTransactionUpsert)) *BalanceDebitTransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BalanceDebitTransactionUpsert{UpdateSet: update})
	}))
	return u
}

// SetTxnID sets the "txn_id" field.
func (u *BalanceDebitTransactionUpsertBulk) SetTxnID(v string) *BalanceDebitTransactionUpsertBulk {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.SetTxnID(v)
	})
}

// UpdateTxnID sets the "txn_id" field to the value that was provided on create.
func (u *BalanceDebitTransactionUpsertBulk) UpdateTxnID() *BalanceDebitTransactionUpsertBulk {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.UpdateTxnID()
	})
}

// SetUserID sets the "user_id" field.
func (u *BalanceDebitTransactionUpsertBulk) SetUserID(v int64) *BalanceDebitTransactionUpsertBulk {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *BalanceDebitTransactionUpsertBulk) AddUserID(v int64) *BalanceDebitTransactionUpsertBulk {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *BalanceDebitTransactionUpsertBulk) UpdateUserID() *BalanceDebitTransactionUpsertBulk {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.UpdateUserID()
	})
}

// SetBalanceClientID sets the "balance_client_id" field.
func (u *BalanceDebitTransactionUpsertBulk) SetBalanceClientID(v int64) *BalanceDebitTransactionUpsertBulk {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.SetBalanceClientID(v)
	})
}

// UpdateBalanceClientID sets the "balance_client_id" field to the value that was provided on create.
func (u *BalanceDebitTransactionUpsertBulk) UpdateBalanceClientID() *BalanceDebitTransactionUpsertBulk {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.UpdateBalanceClientID()
	})
}

// SetIdempotencyKeyHash sets the "idempotency_key_hash" field.
func (u *BalanceDebitTransactionUpsertBulk) SetIdempotencyKeyHash(v string) *BalanceDebitTransactionUpsertBulk {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.SetIdempotencyKeyHash(v)
	})
}

// UpdateIdempotencyKeyHash sets the "idempotency_key_hash" field to the value that was provided on create.
func (u *BalanceDebitTransactionUpsertBulk) UpdateIdempotencyKeyHash() *BalanceDebitTransactionUpsertBulk {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.UpdateIdempotencyKeyHash()
	})
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (u *BalanceDebitTransactionUpsertBulk) SetRequestFingerprint(v string) *BalanceDebitTransactionUpsertBulk {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.SetRequestFingerprint(v)
	})
}

// UpdateRequestFingerprint sets the "request_fingerprint" field to the value that was provided on create.
func (u *BalanceDebitTransactionUpsertBulk) UpdateRequestFingerprint() *BalanceDebitTransactionUpsertBulk {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.UpdateRequestFingerprint()
	})
}

// SetAmount sets the "amount" field.
func (u *BalanceDebitTransactionUpsertBulk) SetAmount(v float64) *BalanceDebitTransactionUpsertBulk {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *BalanceDebitTransactionUpsertBulk) AddAmount(v float64) *BalanceDebitTransactionUpsertBulk {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *BalanceDebitTransactionUpsertBulk) UpdateAmount() *BalanceDebitTransactionUpsertBulk {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.UpdateAmount()
	})
}

// SetCurrency sets the "currency" field.
func (u *BalanceDebitTransactionUpsertBulk) SetCurrency(v string) *BalanceDebitTransactionUpsertBulk {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *BalanceDebitTransactionUpsertBulk) UpdateCurrency() *BalanceDebitTransactionUpsertBulk {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.UpdateCurrency()
	})
}

// SetPurpose sets the "purpose" field.
func (u *BalanceDebitTransactionUpsertBulk) SetPurpose(v string) *BalanceDebitTransactionUpsertBulk {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.SetPurpose(v)
	})
}

// UpdatePurpose sets the "purpose" field to the value that was provided on create.
func (u *BalanceDebitTransactionUpsertBulk) UpdatePurpose() *BalanceDebitTransactionUpsertBulk {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.UpdatePurpose()
	})
}

// SetRef sets the "ref" field.
func (u *BalanceDebitTransactionUpsertBulk) SetRef(v string) *BalanceDebitTransactionUpsertBulk {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.SetRef(v)
	})
}

// UpdateRef sets the "ref" field to the value that was provided on create.
func (u *BalanceDebitTransactionUpsertBulk) UpdateRef() *BalanceDebitTransactionUpsertBulk {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.UpdateRef()
	})
}

// SetBalanceBefore sets the "balance_before" field.
func (u *BalanceDebitTransactionUpsertBulk) SetBalanceBefore(v float64) *BalanceDebitTransactionUpsertBulk {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.SetBalanceBefore(v)
	})
}

// AddBalanceBefore adds v to the "balance_before" field.
func (u *BalanceDebitTransactionUpsertBulk) AddBalanceBefore(v float64) *BalanceDebitTransactionUpsertBulk {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.AddBalanceBefore(v)
	})
}

// UpdateBalanceBefore sets the "balance_before" field to the value that was provided on create.
func (u *BalanceDebitTransactionUpsertBulk) UpdateBalanceBefore() *BalanceDebitTransactionUpsertBulk {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.UpdateBalanceBefore()
	})
}

// SetBalanceAfter sets the "balance_after" field.
func (u *BalanceDebitTransactionUpsertBulk) SetBalanceAfter(v float64) *BalanceDebitTransactionUpsertBulk {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.SetBalanceAfter(v)
	})
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *BalanceDebitTransactionUpsertBulk) AddBalanceAfter(v float64) *BalanceDebitTransactionUpsertBulk {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.AddBalanceAfter(v)
	})
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *BalanceDebitTransactionUpsertBulk) UpdateBalanceAfter() *BalanceDebitTransactionUpsertBulk {
	return u.Update(func(s *BalanceDebitTransactionUpsert) {
		s.UpdateBalanceAfter()
	})
}

// Exec executes the query.
func (u *BalanceDebitTransactionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BalanceDebitTransactionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BalanceDebitTransactionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BalanceDebitTransactionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
