// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/lotterycode"
)

// LotteryCodeCreate is the builder for creating a LotteryCode entity.
type LotteryCodeCreate struct {
	config
	mutation *LotteryCodeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCampaignID sets the "campaign_id" field.
func (_c *LotteryCodeCreate) SetCampaignID(v int64) *LotteryCodeCreate {
	_c.mutation.SetCampaignID(v)
	return _c
}

// SetCode sets the "code" field.
func (_c *LotteryCodeCreate) SetCode(v string) *LotteryCodeCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetAssignedUserID sets the "assigned_user_id" field.
func (_c *LotteryCodeCreate) SetAssignedUserID(v int64) *LotteryCodeCreate {
	_c.mutation.SetAssignedUserID(v)
	return _c
}

// SetNillableAssignedUserID sets the "assigned_user_id" field if the given value is not nil.
func (_c *LotteryCodeCreate) SetNillableAssignedUserID(v *int64) *LotteryCodeCreate {
	if v != nil {
		_c.SetAssignedUserID(*v)
	}
	return _c
}

// SetAssignedDrawID sets the "assigned_draw_id" field.
func (_c *LotteryCodeCreate) SetAssignedDrawID(v int64) *LotteryCodeCreate {
	_c.mutation.SetAssignedDrawID(v)
	return _c
}

// SetNillableAssignedDrawID sets the "assigned_draw_id" field if the given value is not nil.
func (_c *LotteryCodeCreate) SetNillableAssignedDrawID(v *int64) *LotteryCodeCreate {
	if v != nil {
		_c.SetAssignedDrawID(*v)
	}
	return _c
}

// SetAssignedAt sets the "assigned_at" field.
func (_c *LotteryCodeCreate) SetAssignedAt(v time.Time) *LotteryCodeCreate {
	_c.mutation.SetAssignedAt(v)
	return _c
}

// SetNillableAssignedAt sets the "assigned_at" field if the given value is not nil.
func (_c *LotteryCodeCreate) SetNillableAssignedAt(v *time.Time) *LotteryCodeCreate {
	if v != nil {
		_c.SetAssignedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *LotteryCodeCreate) SetCreatedAt(v time.Time) *LotteryCodeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LotteryCodeCreate) SetNillableCreatedAt(v *time.Time) *LotteryCodeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *LotteryCodeCreate) SetUpdatedAt(v time.Time) *LotteryCodeCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *LotteryCodeCreate) SetNillableUpdatedAt(v *time.Time) *LotteryCodeCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the LotteryCodeMutation object of the builder.
func (_c *LotteryCodeCreate) Mutation() *LotteryCodeMutation {
	return _c.mutation
}

// Save creates the LotteryCode in the database.
func (_c *LotteryCodeCreate) Save(ctx context.Context) (*LotteryCode, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LotteryCodeCreate) SaveX(ctx context.Context) *LotteryCode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LotteryCodeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LotteryCodeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LotteryCodeCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := lotterycode.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := lotterycode.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LotteryCodeCreate) check() error {
	if _, ok := _c.mutation.CampaignID(); !ok {
		return &ValidationError{Name: "campaign_id", err: errors.New(`ent: missing required field "LotteryCode.campaign_id"`)}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "LotteryCode.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := lotterycode.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "LotteryCode.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LotteryCode.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "LotteryCode.updated_at"`)}
	}
	return nil
}

func (_c *LotteryCodeCreate) sqlSave(ctx context.Context) (*LotteryCode, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LotteryCodeCreate) createSpec() (*LotteryCode, *sqlgraph.CreateSpec) {
	var (
		_node = &LotteryCode{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(lotterycode.Table, sqlgraph.NewFieldSpec(lotterycode.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CampaignID(); ok {
		_spec.SetField(lotterycode.FieldCampaignID, field.TypeInt64, value)
		_node.CampaignID = value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(lotterycode.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.AssignedUserID(); ok {
		_spec.SetField(lotterycode.FieldAssignedUserID, field.TypeInt64, value)
		_node.AssignedUserID = &value
	}
	if value, ok := _c.mutation.AssignedDrawID(); ok {
		_spec.SetField(lotterycode.FieldAssignedDrawID, field.TypeInt64, value)
		_node.AssignedDrawID = &value
	}
	if value, ok := _c.mutation.AssignedAt(); ok {
		_spec.SetField(lotterycode.FieldAssignedAt, field.TypeTime, value)
		_node.AssignedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(lotterycode.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(lotterycode.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LotteryCode.Create().
//		SetCampaignID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LotteryCodeUpsert) {
//			SetCampaignID(v+v).
//		}).
//		Exec(ctx)
func (_c *LotteryCodeCreate) OnConflict(opts ...sql.ConflictOption) *LotteryCodeUpsertOne {
	_c.conflict = opts
	return &LotteryCodeUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LotteryCode.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LotteryCodeCreate) OnConflictColumns(columns ...string) *LotteryCodeUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LotteryCodeUpsertOne{
		create: _c,
	}
}

type (
	// LotteryCodeUpsertOne is the builder for "upsert"-ing
	//  one LotteryCode node.
	LotteryCodeUpsertOne struct {
		create *LotteryCodeCreate
	}

	// LotteryCodeUpsert is the "OnConflict" setter.
	LotteryCodeUpsert struct {
		*sql.UpdateSet
	}
)

// SetCampaignID sets the "campaign_id" field.
func (u *LotteryCodeUpsert) SetCampaignID(v int64) *LotteryCodeUpsert {
	u.Set(lotterycode.FieldCampaignID, v)
	return u
}

// UpdateCampaignID sets the "campaign_id" field to the value that was provided on create.
func (u *LotteryCodeUpsert) UpdateCampaignID() *LotteryCodeUpsert {
	u.SetExcluded(lotterycode.FieldCampaignID)
	return u
}

// AddCampaignID adds v to the "campaign_id" field.
func (u *LotteryCodeUpsert) AddCampaignID(v int64) *LotteryCodeUpsert {
	u.Add(lotterycode.FieldCampaignID, v)
	return u
}

// SetCode sets the "code" field.
func (u *LotteryCodeUpsert) SetCode(v string) *LotteryCodeUpsert {
	u.Set(lotterycode.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *LotteryCodeUpsert) UpdateCode() *LotteryCodeUpsert {
	u.SetExcluded(lotterycode.FieldCode)
	return u
}

// SetAssignedUserID sets the "assigned_user_id" field.
func (u *LotteryCodeUpsert) SetAssignedUserID(v int64) *LotteryCodeUpsert {
	u.Set(lotterycode.FieldAssignedUserID, v)
	return u
}

// UpdateAssignedUserID sets the "assigned_user_id" field to the value that was provided on create.
func (u *LotteryCodeUpsert) UpdateAssignedUserID() *LotteryCodeUpsert {
	u.SetExcluded(lotterycode.FieldAssignedUserID)
	return u
}

// AddAssignedUserID adds v to the "assigned_user_id" field.
func (u *LotteryCodeUpsert) AddAssignedUserID(v int64) *LotteryCodeUpsert {
	u.Add(lotterycode.FieldAssignedUserID, v)
	return u
}

// ClearAssignedUserID clears the value of the "assigned_user_id" field.
func (u *LotteryCodeUpsert) ClearAssignedUserID() *LotteryCodeUpsert {
	u.SetNull(lotterycode.FieldAssignedUserID)
	return u
}

// SetAssignedDrawID sets the "assigned_draw_id" field.
func (u *LotteryCodeUpsert) SetAssignedDrawID(v int64) *LotteryCodeUpsert {
	u.Set(lotterycode.FieldAssignedDrawID, v)
	return u
}

// UpdateAssignedDrawID sets the "assigned_draw_id" field to the value that was provided on create.
func (u *LotteryCodeUpsert) UpdateAssignedDrawID() *LotteryCodeUpsert {
	u.SetExcluded(lotterycode.FieldAssignedDrawID)
	return u
}

// AddAssignedDrawID adds v to the "assigned_draw_id" field.
func (u *LotteryCodeUpsert) AddAssignedDrawID(v int64) *LotteryCodeUpsert {
	u.Add(lotterycode.FieldAssignedDrawID, v)
	return u
}

// ClearAssignedDrawID clears the value of the "assigned_draw_id" field.
func (u *LotteryCodeUpsert) ClearAssignedDrawID() *LotteryCodeUpsert {
	u.SetNull(lotterycode.FieldAssignedDrawID)
	return u
}

// SetAssignedAt sets the "assigned_at" field.
func (u *LotteryCodeUpsert) SetAssignedAt(v time.Time) *LotteryCodeUpsert {
	u.Set(lotterycode.FieldAssignedAt, v)
	return u
}

// UpdateAssignedAt sets the "assigned_at" field to the value that was provided on create.
func (u *LotteryCodeUpsert) UpdateAssignedAt() *LotteryCodeUpsert {
	u.SetExcluded(lotterycode.FieldAssignedAt)
	return u
}

// ClearAssignedAt clears the value of the "assigned_at" field.
func (u *LotteryCodeUpsert) ClearAssignedAt() *LotteryCodeUpsert {
	u.SetNull(lotterycode.FieldAssignedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LotteryCodeUpsert) SetUpdatedAt(v time.Time) *LotteryCodeUpsert {
	u.Set(lotterycode.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LotteryCodeUpsert) UpdateUpdatedAt() *LotteryCodeUpsert {
	u.SetExcluded(lotterycode.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.LotteryCode.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LotteryCodeUpsertOne) UpdateNewValues() *LotteryCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(lotterycode.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LotteryCode.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LotteryCodeUpsertOne) Ignore() *LotteryCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LotteryCodeUpsertOne) DoNothing() *LotteryCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LotteryCodeCreate.OnConflict
// documentation for more info.
func (u *LotteryCodeUpsertOne) Update(set func(*LotteryCodeUpsert)) *LotteryCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LotteryCodeUpsert{UpdateSet: update})
	}))
	return u
}

// SetCampaignID sets the "campaign_id" field.
func (u *LotteryCodeUpsertOne) SetCampaignID(v int64) *LotteryCodeUpsertOne {
	return u.Update(func(s *LotteryCodeUpsert) {
		s.SetCampaignID(v)
	})
}

// AddCampaignID adds v to the "campaign_id" field.
func (u *LotteryCodeUpsertOne) AddCampaignID(v int64) *LotteryCodeUpsertOne {
	return u.Update(func(s *LotteryCodeUpsert) {
		s.AddCampaignID(v)
	})
}

// UpdateCampaignID sets the "campaign_id" field to the value that was provided on create.
func (u *LotteryCodeUpsertOne) UpdateCampaignID() *LotteryCodeUpsertOne {
	return u.Update(func(s *LotteryCodeUpsert) {
		s.UpdateCampaignID()
	})
}

// SetCode sets the "code" field.
func (u *LotteryCodeUpsertOne) SetCode(v string) *LotteryCodeUpsertOne {
	return u.Update(func(s *LotteryCodeUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *LotteryCodeUpsertOne) UpdateCode() *LotteryCodeUpsertOne {
	return u.Update(func(s *LotteryCodeUpsert) {
		s.UpdateCode()
	})
}

// SetAssignedUserID sets the "assigned_user_id" field.
func (u *LotteryCodeUpsertOne) SetAssignedUserID(v int64) *LotteryCodeUpsertOne {
	return u.Update(func(s *LotteryCodeUpsert) {
		s.SetAssignedUserID(v)
	})
}

// AddAssignedUserID adds v to the "assigned_user_id" field.
func (u *LotteryCodeUpsertOne) AddAssignedUserID(v int64) *LotteryCodeUpsertOne {
	return u.Update(func(s *LotteryCodeUpsert) {
		s.AddAssignedUserID(v)
	})
}

// UpdateAssignedUserID sets the "assigned_user_id" field to the value that was provided on create.
func (u *LotteryCodeUpsertOne) UpdateAssignedUserID() *LotteryCodeUpsertOne {
	return u.Update(func(s *LotteryCodeUpsert) {
		s.UpdateAssignedUserID()
	})
}

// ClearAssignedUserID clears the value of the "assigned_user_id" field.
func (u *LotteryCodeUpsertOne) ClearAssignedUserID() *LotteryCodeUpsertOne {
	return u.Update(func(s *LotteryCodeUpsert) {
		s.ClearAssignedUserID()
	})
}

// SetAssignedDrawID sets the "assigned_draw_id" field.
func (u *LotteryCodeUpsertOne) SetAssignedDrawID(v int64) *LotteryCodeUpsertOne {
	return u.Update(func(s *LotteryCodeUpsert) {
		s.SetAssignedDrawID(v)
	})
}

// AddAssignedDrawID adds v to the "assigned_draw_id" field.
func (u *LotteryCodeUpsertOne) AddAssignedDrawID(v int64) *LotteryCodeUpsertOne {
	return u.Update(func(s *LotteryCodeUpsert) {
		s.AddAssignedDrawID(v)
	})
}

// UpdateAssignedDrawID sets the "assigned_draw_id" field to the value that was provided on create.
func (u *LotteryCodeUpsertOne) UpdateAssignedDrawID() *LotteryCodeUpsertOne {
	return u.Update(func(s *LotteryCodeUpsert) {
		s.UpdateAssignedDrawID()
	})
}

// ClearAssignedDrawID clears the value of the "assigned_draw_id" field.
func (u *LotteryCodeUpsertOne) ClearAssignedDrawID() *LotteryCodeUpsertOne {
	return u.Update(func(s *LotteryCodeUpsert) {
		s.ClearAssignedDrawID()
	})
}

// SetAssignedAt sets the "assigned_at" field.
func (u *LotteryCodeUpsertOne) SetAssignedAt(v time.Time) *LotteryCodeUpsertOne {
	return u.Update(func(s *LotteryCodeUpsert) {
		s.SetAssignedAt(v)
	})
}

// UpdateAssignedAt sets the "assigned_at" field to the value that was provided on create.
func (u *LotteryCodeUpsertOne) UpdateAssignedAt() *LotteryCodeUpsertOne {
	return u.Update(func(s *LotteryCodeUpsert) {
		s.UpdateAssignedAt()
	})
}

// ClearAssignedAt clears the value of the "assigned_at" field.
func (u *LotteryCodeUpsertOne) ClearAssignedAt() *LotteryCodeUpsertOne {
	return u.Update(func(s *LotteryCodeUpsert) {
		s.ClearAssignedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LotteryCodeUpsertOne) SetUpdatedAt(v time.Time) *LotteryCodeUpsertOne {
	return u.Update(func(s *LotteryCodeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LotteryCodeUpsertOne) UpdateUpdatedAt() *LotteryCodeUpsertOne {
	return u.Update(func(s *LotteryCodeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *LotteryCodeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LotteryCodeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LotteryCodeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LotteryCodeUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LotteryCodeUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LotteryCodeCreateBulk is the builder for creating many LotteryCode entities in bulk.
type LotteryCodeCreateBulk struct {
	config
	err      error
	builders []*LotteryCodeCreate
	conflict []sql.ConflictOption
}

// Save creates the LotteryCode entities in the database.
func (_c *LotteryCodeCreateBulk) Save(ctx context.Context) ([]*LotteryCode, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LotteryCode, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LotteryCodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LotteryCodeCreateBulk) SaveX(ctx context.Context) []*LotteryCode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LotteryCodeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LotteryCodeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LotteryCode.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LotteryCodeUpsert) {
//			SetCampaignID(v+v).
//		}).
//		Exec(ctx)
func (_c *LotteryCodeCreateBulk) OnConflict(opts ...sql.ConflictOption) *LotteryCodeUpsertBulk {
	_c.conflict = opts
	return &LotteryCodeUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LotteryCode.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LotteryCodeCreateBulk) OnConflictColumns(columns ...string) *LotteryCodeUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LotteryCodeUpsertBulk{
		create: _c,
	}
}

// LotteryCodeUpsertBulk is the builder for "upsert"-ing
// a bulk of LotteryCode nodes.
type LotteryCodeUpsertBulk struct {
	create *LotteryCodeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.LotteryCode.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LotteryCodeUpsertBulk) UpdateNewValues() *LotteryCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(lotterycode.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LotteryCode.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LotteryCodeUpsertBulk) Ignore() *LotteryCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LotteryCodeUpsertBulk) DoNothing() *LotteryCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LotteryCodeCreateBulk.OnConflict
// documentation for more info.
func (u *LotteryCodeUpsertBulk) Update(set func(*LotteryCodeUpsert)) *LotteryCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LotteryCodeUpsert{UpdateSet: update})
	}))
	return u
}

// SetCampaignID sets the "campaign_id" field.
func (u *LotteryCodeUpsertBulk) SetCampaignID(v int64) *LotteryCodeUpsertBulk {
	return u.Update(func(s *LotteryCodeUpsert) {
		s.SetCampaignID(v)
	})
}

// AddCampaignID adds v to the "campaign_id" field.
func (u *LotteryCodeUpsertBulk) AddCampaignID(v int64) *LotteryCodeUpsertBulk {
	return u.Update(func(s *LotteryCodeUpsert) {
		s.AddCampaignID(v)
	})
}

// UpdateCampaignID sets the "campaign_id" field to the value that was provided on create.
func (u *LotteryCodeUpsertBulk) UpdateCampaignID() *LotteryCodeUpsertBulk {
	return u.Update(func(s *LotteryCodeUpsert) {
		s.UpdateCampaignID()
	})
}

// SetCode sets the "code" field.
func (u *LotteryCodeUpsertBulk) SetCode(v string) *LotteryCodeUpsertBulk {
	return u.Update(func(s *LotteryCodeUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *LotteryCodeUpsertBulk) UpdateCode() *LotteryCodeUpsertBulk {
	return u.Update(func(s *LotteryCodeUpsert) {
		s.UpdateCode()
	})
}

// SetAssignedUserID sets the "assigned_user_id" field.
func (u *LotteryCodeUpsertBulk) SetAssignedUserID(v int64) *LotteryCodeUpsertBulk {
	return u.Update(func(s *LotteryCodeUpsert) {
		s.SetAssignedUserID(v)
	})
}

// AddAssignedUserID adds v to the "assigned_user_id" field.
func (u *LotteryCodeUpsertBulk) AddAssignedUserID(v int64) *LotteryCodeUpsertBulk {
	return u.Update(func(s *LotteryCodeUpsert) {
		s.AddAssignedUserID(v)
	})
}

// UpdateAssignedUserID sets the "assigned_user_id" field to the value that was provided on create.
func (u *LotteryCodeUpsertBulk) UpdateAssignedUserID() *LotteryCodeUpsertBulk {
	return u.Update(func(s *LotteryCodeUpsert) {
		s.UpdateAssignedUserID()
	})
}

// ClearAssignedUserID clears the value of the "assigned_user_id" field.
func (u *LotteryCodeUpsertBulk) ClearAssignedUserID() *LotteryCodeUpsertBulk {
	return u.Update(func(s *LotteryCodeUpsert) {
		s.ClearAssignedUserID()
	})
}

// SetAssignedDrawID sets the "assigned_draw_id" field.
func (u *LotteryCodeUpsertBulk) SetAssignedDrawID(v int64) *LotteryCodeUpsertBulk {
	return u.Update(func(s *LotteryCodeUpsert) {
		s.SetAssignedDrawID(v)
	})
}

// AddAssignedDrawID adds v to the "assigned_draw_id" field.
func (u *LotteryCodeUpsertBulk) AddAssignedDrawID(v int64) *LotteryCodeUpsertBulk {
	return u.Update(func(s *LotteryCodeUpsert) {
		s.AddAssignedDrawID(v)
	})
}

// UpdateAssignedDrawID sets the "assigned_draw_id" field to the value that was provided on create.
func (u *LotteryCodeUpsertBulk) UpdateAssignedDrawID() *LotteryCodeUpsertBulk {
	return u.Update(func(s *LotteryCodeUpsert) {
		s.UpdateAssignedDrawID()
	})
}

// ClearAssignedDrawID clears the value of the "assigned_draw_id" field.
func (u *LotteryCodeUpsertBulk) ClearAssignedDrawID() *LotteryCodeUpsertBulk {
	return u.Update(func(s *LotteryCodeUpsert) {
		s.ClearAssignedDrawID()
	})
}

// SetAssignedAt sets the "assigned_at" field.
func (u *LotteryCodeUpsertBulk) SetAssignedAt(v time.Time) *LotteryCodeUpsertBulk {
	return u.Update(func(s *LotteryCodeUpsert) {
		s.SetAssignedAt(v)
	})
}

// UpdateAssignedAt sets the "assigned_at" field to the value that was provided on create.
func (u *LotteryCodeUpsertBulk) UpdateAssignedAt() *LotteryCodeUpsertBulk {
	return u.Update(func(s *LotteryCodeUpsert) {
		s.UpdateAssignedAt()
	})
}

// ClearAssignedAt clears the value of the "assigned_at" field.
func (u *LotteryCodeUpsertBulk) ClearAssignedAt() *LotteryCodeUpsertBulk {
	return u.Update(func(s *LotteryCodeUpsert) {
		s.ClearAssignedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LotteryCodeUpsertBulk) SetUpdatedAt(v time.Time) *LotteryCodeUpsertBulk {
	return u.Update(func(s *LotteryCodeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LotteryCodeUpsertBulk) UpdateUpdatedAt() *LotteryCodeUpsertBulk {
	return u.Update(func(s *LotteryCodeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *LotteryCodeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LotteryCodeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LotteryCodeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LotteryCodeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
