// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/lotterycampaign"
)

// LotteryCampaign is the model entity for the LotteryCampaign schema.
type LotteryCampaign struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Subtitle holds the value of the "subtitle" field.
	Subtitle string `json:"subtitle,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// PrizeCount holds the value of the "prize_count" field.
	PrizeCount int `json:"prize_count,omitempty"`
	// MaxParticipants holds the value of the "max_participants" field.
	MaxParticipants int `json:"max_participants,omitempty"`
	// JoinedCount holds the value of the "joined_count" field.
	JoinedCount int `json:"joined_count,omitempty"`
	// WinnerCount holds the value of the "winner_count" field.
	WinnerCount int `json:"winner_count,omitempty"`
	// EarlyBoostParticipantPercent holds the value of the "early_boost_participant_percent" field.
	EarlyBoostParticipantPercent int `json:"early_boost_participant_percent,omitempty"`
	// RechargeBoostCapPercent holds the value of the "recharge_boost_cap_percent" field.
	RechargeBoostCapPercent int `json:"recharge_boost_cap_percent,omitempty"`
	// PromoText holds the value of the "promo_text" field.
	PromoText string `json:"promo_text,omitempty"`
	// PromoImageURL holds the value of the "promo_image_url" field.
	PromoImageURL string `json:"promo_image_url,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy int64 `json:"created_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// FinishedAt holds the value of the "finished_at" field.
	FinishedAt   *time.Time `json:"finished_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LotteryCampaign) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case lotterycampaign.FieldID, lotterycampaign.FieldPrizeCount, lotterycampaign.FieldMaxParticipants, lotterycampaign.FieldJoinedCount, lotterycampaign.FieldWinnerCount, lotterycampaign.FieldEarlyBoostParticipantPercent, lotterycampaign.FieldRechargeBoostCapPercent, lotterycampaign.FieldCreatedBy:
			values[i] = new(sql.NullInt64)
		case lotterycampaign.FieldName, lotterycampaign.FieldSubtitle, lotterycampaign.FieldStatus, lotterycampaign.FieldPromoText, lotterycampaign.FieldPromoImageURL:
			values[i] = new(sql.NullString)
		case lotterycampaign.FieldCreatedAt, lotterycampaign.FieldUpdatedAt, lotterycampaign.FieldFinishedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LotteryCampaign fields.
func (_m *LotteryCampaign) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case lotterycampaign.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case lotterycampaign.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case lotterycampaign.FieldSubtitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subtitle", values[i])
			} else if value.Valid {
				_m.Subtitle = value.String
			}
		case lotterycampaign.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case lotterycampaign.FieldPrizeCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field prize_count", values[i])
			} else if value.Valid {
				_m.PrizeCount = int(value.Int64)
			}
		case lotterycampaign.FieldMaxParticipants:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_participants", values[i])
			} else if value.Valid {
				_m.MaxParticipants = int(value.Int64)
			}
		case lotterycampaign.FieldJoinedCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field joined_count", values[i])
			} else if value.Valid {
				_m.JoinedCount = int(value.Int64)
			}
		case lotterycampaign.FieldWinnerCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field winner_count", values[i])
			} else if value.Valid {
				_m.WinnerCount = int(value.Int64)
			}
		case lotterycampaign.FieldEarlyBoostParticipantPercent:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field early_boost_participant_percent", values[i])
			} else if value.Valid {
				_m.EarlyBoostParticipantPercent = int(value.Int64)
			}
		case lotterycampaign.FieldRechargeBoostCapPercent:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field recharge_boost_cap_percent", values[i])
			} else if value.Valid {
				_m.RechargeBoostCapPercent = int(value.Int64)
			}
		case lotterycampaign.FieldPromoText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field promo_text", values[i])
			} else if value.Valid {
				_m.PromoText = value.String
			}
		case lotterycampaign.FieldPromoImageURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field promo_image_url", values[i])
			} else if value.Valid {
				_m.PromoImageURL = value.String
			}
		case lotterycampaign.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.Int64
			}
		case lotterycampaign.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case lotterycampaign.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case lotterycampaign.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				_m.FinishedAt = new(time.Time)
				*_m.FinishedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LotteryCampaign.
// This includes values selected through modifiers, order, etc.
func (_m *LotteryCampaign) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this LotteryCampaign.
// Note that you need to call LotteryCampaign.Unwrap() before calling this method if this LotteryCampaign
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *LotteryCampaign) Update() *LotteryCampaignUpdateOne {
	return NewLotteryCampaignClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the LotteryCampaign entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *LotteryCampaign) Unwrap() *LotteryCampaign {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: LotteryCampaign is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *LotteryCampaign) String() string {
	var builder strings.Builder
	builder.WriteString("LotteryCampaign(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("subtitle=")
	builder.WriteString(_m.Subtitle)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("prize_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.PrizeCount))
	builder.WriteString(", ")
	builder.WriteString("max_participants=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxParticipants))
	builder.WriteString(", ")
	builder.WriteString("joined_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.JoinedCount))
	builder.WriteString(", ")
	builder.WriteString("winner_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.WinnerCount))
	builder.WriteString(", ")
	builder.WriteString("early_boost_participant_percent=")
	builder.WriteString(fmt.Sprintf("%v", _m.EarlyBoostParticipantPercent))
	builder.WriteString(", ")
	builder.WriteString("recharge_boost_cap_percent=")
	builder.WriteString(fmt.Sprintf("%v", _m.RechargeBoostCapPercent))
	builder.WriteString(", ")
	builder.WriteString("promo_text=")
	builder.WriteString(_m.PromoText)
	builder.WriteString(", ")
	builder.WriteString("promo_image_url=")
	builder.WriteString(_m.PromoImageURL)
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedBy))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.FinishedAt; v != nil {
		builder.WriteString("finished_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// LotteryCampaigns is a parsable slice of LotteryCampaign.
type LotteryCampaigns []*LotteryCampaign
