// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/lotterycode"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// LotteryCodeUpdate is the builder for updating LotteryCode entities.
type LotteryCodeUpdate struct {
	config
	hooks    []Hook
	mutation *LotteryCodeMutation
}

// Where appends a list predicates to the LotteryCodeUpdate builder.
func (_u *LotteryCodeUpdate) Where(ps ...predicate.LotteryCode) *LotteryCodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCampaignID sets the "campaign_id" field.
func (_u *LotteryCodeUpdate) SetCampaignID(v int64) *LotteryCodeUpdate {
	_u.mutation.ResetCampaignID()
	_u.mutation.SetCampaignID(v)
	return _u
}

// SetNillableCampaignID sets the "campaign_id" field if the given value is not nil.
func (_u *LotteryCodeUpdate) SetNillableCampaignID(v *int64) *LotteryCodeUpdate {
	if v != nil {
		_u.SetCampaignID(*v)
	}
	return _u
}

// AddCampaignID adds value to the "campaign_id" field.
func (_u *LotteryCodeUpdate) AddCampaignID(v int64) *LotteryCodeUpdate {
	_u.mutation.AddCampaignID(v)
	return _u
}

// SetCode sets the "code" field.
func (_u *LotteryCodeUpdate) SetCode(v string) *LotteryCodeUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *LotteryCodeUpdate) SetNillableCode(v *string) *LotteryCodeUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetAssignedUserID sets the "assigned_user_id" field.
func (_u *LotteryCodeUpdate) SetAssignedUserID(v int64) *LotteryCodeUpdate {
	_u.mutation.ResetAssignedUserID()
	_u.mutation.SetAssignedUserID(v)
	return _u
}

// SetNillableAssignedUserID sets the "assigned_user_id" field if the given value is not nil.
func (_u *LotteryCodeUpdate) SetNillableAssignedUserID(v *int64) *LotteryCodeUpdate {
	if v != nil {
		_u.SetAssignedUserID(*v)
	}
	return _u
}

// AddAssignedUserID adds value to the "assigned_user_id" field.
func (_u *LotteryCodeUpdate) AddAssignedUserID(v int64) *LotteryCodeUpdate {
	_u.mutation.AddAssignedUserID(v)
	return _u
}

// ClearAssignedUserID clears the value of the "assigned_user_id" field.
func (_u *LotteryCodeUpdate) ClearAssignedUserID() *LotteryCodeUpdate {
	_u.mutation.ClearAssignedUserID()
	return _u
}

// SetAssignedDrawID sets the "assigned_draw_id" field.
func (_u *LotteryCodeUpdate) SetAssignedDrawID(v int64) *LotteryCodeUpdate {
	_u.mutation.ResetAssignedDrawID()
	_u.mutation.SetAssignedDrawID(v)
	return _u
}

// SetNillableAssignedDrawID sets the "assigned_draw_id" field if the given value is not nil.
func (_u *LotteryCodeUpdate) SetNillableAssignedDrawID(v *int64) *LotteryCodeUpdate {
	if v != nil {
		_u.SetAssignedDrawID(*v)
	}
	return _u
}

// AddAssignedDrawID adds value to the "assigned_draw_id" field.
func (_u *LotteryCodeUpdate) AddAssignedDrawID(v int64) *LotteryCodeUpdate {
	_u.mutation.AddAssignedDrawID(v)
	return _u
}

// ClearAssignedDrawID clears the value of the "assigned_draw_id" field.
func (_u *LotteryCodeUpdate) ClearAssignedDrawID() *LotteryCodeUpdate {
	_u.mutation.ClearAssignedDrawID()
	return _u
}

// SetAssignedAt sets the "assigned_at" field.
func (_u *LotteryCodeUpdate) SetAssignedAt(v time.Time) *LotteryCodeUpdate {
	_u.mutation.SetAssignedAt(v)
	return _u
}

// SetNillableAssignedAt sets the "assigned_at" field if the given value is not nil.
func (_u *LotteryCodeUpdate) SetNillableAssignedAt(v *time.Time) *LotteryCodeUpdate {
	if v != nil {
		_u.SetAssignedAt(*v)
	}
	return _u
}

// ClearAssignedAt clears the value of the "assigned_at" field.
func (_u *LotteryCodeUpdate) ClearAssignedAt() *LotteryCodeUpdate {
	_u.mutation.ClearAssignedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LotteryCodeUpdate) SetUpdatedAt(v time.Time) *LotteryCodeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the LotteryCodeMutation object of the builder.
func (_u *LotteryCodeUpdate) Mutation() *LotteryCodeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LotteryCodeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LotteryCodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LotteryCodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LotteryCodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LotteryCodeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := lotterycode.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LotteryCodeUpdate) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := lotterycode.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "LotteryCode.code": %w`, err)}
		}
	}
	return nil
}

func (_u *LotteryCodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(lotterycode.Table, lotterycode.Columns, sqlgraph.NewFieldSpec(lotterycode.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CampaignID(); ok {
		_spec.SetField(lotterycode.FieldCampaignID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCampaignID(); ok {
		_spec.AddField(lotterycode.FieldCampaignID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(lotterycode.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.AssignedUserID(); ok {
		_spec.SetField(lotterycode.FieldAssignedUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAssignedUserID(); ok {
		_spec.AddField(lotterycode.FieldAssignedUserID, field.TypeInt64, value)
	}
	if _u.mutation.AssignedUserIDCleared() {
		_spec.ClearField(lotterycode.FieldAssignedUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AssignedDrawID(); ok {
		_spec.SetField(lotterycode.FieldAssignedDrawID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAssignedDrawID(); ok {
		_spec.AddField(lotterycode.FieldAssignedDrawID, field.TypeInt64, value)
	}
	if _u.mutation.AssignedDrawIDCleared() {
		_spec.ClearField(lotterycode.FieldAssignedDrawID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AssignedAt(); ok {
		_spec.SetField(lotterycode.FieldAssignedAt, field.TypeTime, value)
	}
	if _u.mutation.AssignedAtCleared() {
		_spec.ClearField(lotterycode.FieldAssignedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(lotterycode.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lotterycode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LotteryCodeUpdateOne is the builder for updating a single LotteryCode entity.
type LotteryCodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LotteryCodeMutation
}

// SetCampaignID sets the "campaign_id" field.
func (_u *LotteryCodeUpdateOne) SetCampaignID(v int64) *LotteryCodeUpdateOne {
	_u.mutation.ResetCampaignID()
	_u.mutation.SetCampaignID(v)
	return _u
}

// SetNillableCampaignID sets the "campaign_id" field if the given value is not nil.
func (_u *LotteryCodeUpdateOne) SetNillableCampaignID(v *int64) *LotteryCodeUpdateOne {
	if v != nil {
		_u.SetCampaignID(*v)
	}
	return _u
}

// AddCampaignID adds value to the "campaign_id" field.
func (_u *LotteryCodeUpdateOne) AddCampaignID(v int64) *LotteryCodeUpdateOne {
	_u.mutation.AddCampaignID(v)
	return _u
}

// SetCode sets the "code" field.
func (_u *LotteryCodeUpdateOne) SetCode(v string) *LotteryCodeUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *LotteryCodeUpdateOne) SetNillableCode(v *string) *LotteryCodeUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetAssignedUserID sets the "assigned_user_id" field.
func (_u *LotteryCodeUpdateOne) SetAssignedUserID(v int64) *LotteryCodeUpdateOne {
	_u.mutation.ResetAssignedUserID()
	_u.mutation.SetAssignedUserID(v)
	return _u
}

// SetNillableAssignedUserID sets the "assigned_user_id" field if the given value is not nil.
func (_u *LotteryCodeUpdateOne) SetNillableAssignedUserID(v *int64) *LotteryCodeUpdateOne {
	if v != nil {
		_u.SetAssignedUserID(*v)
	}
	return _u
}

// AddAssignedUserID adds value to the "assigned_user_id" field.
func (_u *LotteryCodeUpdateOne) AddAssignedUserID(v int64) *LotteryCodeUpdateOne {
	_u.mutation.AddAssignedUserID(v)
	return _u
}

// ClearAssignedUserID clears the value of the "assigned_user_id" field.
func (_u *LotteryCodeUpdateOne) ClearAssignedUserID() *LotteryCodeUpdateOne {
	_u.mutation.ClearAssignedUserID()
	return _u
}

// SetAssignedDrawID sets the "assigned_draw_id" field.
func (_u *LotteryCodeUpdateOne) SetAssignedDrawID(v int64) *LotteryCodeUpdateOne {
	_u.mutation.ResetAssignedDrawID()
	_u.mutation.SetAssignedDrawID(v)
	return _u
}

// SetNillableAssignedDrawID sets the "assigned_draw_id" field if the given value is not nil.
func (_u *LotteryCodeUpdateOne) SetNillableAssignedDrawID(v *int64) *LotteryCodeUpdateOne {
	if v != nil {
		_u.SetAssignedDrawID(*v)
	}
	return _u
}

// AddAssignedDrawID adds value to the "assigned_draw_id" field.
func (_u *LotteryCodeUpdateOne) AddAssignedDrawID(v int64) *LotteryCodeUpdateOne {
	_u.mutation.AddAssignedDrawID(v)
	return _u
}

// ClearAssignedDrawID clears the value of the "assigned_draw_id" field.
func (_u *LotteryCodeUpdateOne) ClearAssignedDrawID() *LotteryCodeUpdateOne {
	_u.mutation.ClearAssignedDrawID()
	return _u
}

// SetAssignedAt sets the "assigned_at" field.
func (_u *LotteryCodeUpdateOne) SetAssignedAt(v time.Time) *LotteryCodeUpdateOne {
	_u.mutation.SetAssignedAt(v)
	return _u
}

// SetNillableAssignedAt sets the "assigned_at" field if the given value is not nil.
func (_u *LotteryCodeUpdateOne) SetNillableAssignedAt(v *time.Time) *LotteryCodeUpdateOne {
	if v != nil {
		_u.SetAssignedAt(*v)
	}
	return _u
}

// ClearAssignedAt clears the value of the "assigned_at" field.
func (_u *LotteryCodeUpdateOne) ClearAssignedAt() *LotteryCodeUpdateOne {
	_u.mutation.ClearAssignedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LotteryCodeUpdateOne) SetUpdatedAt(v time.Time) *LotteryCodeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the LotteryCodeMutation object of the builder.
func (_u *LotteryCodeUpdateOne) Mutation() *LotteryCodeMutation {
	return _u.mutation
}

// Where appends a list predicates to the LotteryCodeUpdate builder.
func (_u *LotteryCodeUpdateOne) Where(ps ...predicate.LotteryCode) *LotteryCodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LotteryCodeUpdateOne) Select(field string, fields ...string) *LotteryCodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LotteryCode entity.
func (_u *LotteryCodeUpdateOne) Save(ctx context.Context) (*LotteryCode, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LotteryCodeUpdateOne) SaveX(ctx context.Context) *LotteryCode {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LotteryCodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LotteryCodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LotteryCodeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := lotterycode.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LotteryCodeUpdateOne) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := lotterycode.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "LotteryCode.code": %w`, err)}
		}
	}
	return nil
}

func (_u *LotteryCodeUpdateOne) sqlSave(ctx context.Context) (_node *LotteryCode, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(lotterycode.Table, lotterycode.Columns, sqlgraph.NewFieldSpec(lotterycode.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LotteryCode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lotterycode.FieldID)
		for _, f := range fields {
			if !lotterycode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != lotterycode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CampaignID(); ok {
		_spec.SetField(lotterycode.FieldCampaignID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCampaignID(); ok {
		_spec.AddField(lotterycode.FieldCampaignID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(lotterycode.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.AssignedUserID(); ok {
		_spec.SetField(lotterycode.FieldAssignedUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAssignedUserID(); ok {
		_spec.AddField(lotterycode.FieldAssignedUserID, field.TypeInt64, value)
	}
	if _u.mutation.AssignedUserIDCleared() {
		_spec.ClearField(lotterycode.FieldAssignedUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AssignedDrawID(); ok {
		_spec.SetField(lotterycode.FieldAssignedDrawID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAssignedDrawID(); ok {
		_spec.AddField(lotterycode.FieldAssignedDrawID, field.TypeInt64, value)
	}
	if _u.mutation.AssignedDrawIDCleared() {
		_spec.ClearField(lotterycode.FieldAssignedDrawID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AssignedAt(); ok {
		_spec.SetField(lotterycode.FieldAssignedAt, field.TypeTime, value)
	}
	if _u.mutation.AssignedAtCleared() {
		_spec.ClearField(lotterycode.FieldAssignedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(lotterycode.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &LotteryCode{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lotterycode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
