// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/lotterycampaign"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// LotteryCampaignUpdate is the builder for updating LotteryCampaign entities.
type LotteryCampaignUpdate struct {
	config
	hooks    []Hook
	mutation *LotteryCampaignMutation
}

// Where appends a list predicates to the LotteryCampaignUpdate builder.
func (_u *LotteryCampaignUpdate) Where(ps ...predicate.LotteryCampaign) *LotteryCampaignUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *LotteryCampaignUpdate) SetName(v string) *LotteryCampaignUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *LotteryCampaignUpdate) SetNillableName(v *string) *LotteryCampaignUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSubtitle sets the "subtitle" field.
func (_u *LotteryCampaignUpdate) SetSubtitle(v string) *LotteryCampaignUpdate {
	_u.mutation.SetSubtitle(v)
	return _u
}

// SetNillableSubtitle sets the "subtitle" field if the given value is not nil.
func (_u *LotteryCampaignUpdate) SetNillableSubtitle(v *string) *LotteryCampaignUpdate {
	if v != nil {
		_u.SetSubtitle(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *LotteryCampaignUpdate) SetStatus(v string) *LotteryCampaignUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *LotteryCampaignUpdate) SetNillableStatus(v *string) *LotteryCampaignUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPrizeCount sets the "prize_count" field.
func (_u *LotteryCampaignUpdate) SetPrizeCount(v int) *LotteryCampaignUpdate {
	_u.mutation.ResetPrizeCount()
	_u.mutation.SetPrizeCount(v)
	return _u
}

// SetNillablePrizeCount sets the "prize_count" field if the given value is not nil.
func (_u *LotteryCampaignUpdate) SetNillablePrizeCount(v *int) *LotteryCampaignUpdate {
	if v != nil {
		_u.SetPrizeCount(*v)
	}
	return _u
}

// AddPrizeCount adds value to the "prize_count" field.
func (_u *LotteryCampaignUpdate) AddPrizeCount(v int) *LotteryCampaignUpdate {
	_u.mutation.AddPrizeCount(v)
	return _u
}

// SetMaxParticipants sets the "max_participants" field.
func (_u *LotteryCampaignUpdate) SetMaxParticipants(v int) *LotteryCampaignUpdate {
	_u.mutation.ResetMaxParticipants()
	_u.mutation.SetMaxParticipants(v)
	return _u
}

// SetNillableMaxParticipants sets the "max_participants" field if the given value is not nil.
func (_u *LotteryCampaignUpdate) SetNillableMaxParticipants(v *int) *LotteryCampaignUpdate {
	if v != nil {
		_u.SetMaxParticipants(*v)
	}
	return _u
}

// AddMaxParticipants adds value to the "max_participants" field.
func (_u *LotteryCampaignUpdate) AddMaxParticipants(v int) *LotteryCampaignUpdate {
	_u.mutation.AddMaxParticipants(v)
	return _u
}

// SetJoinedCount sets the "joined_count" field.
func (_u *LotteryCampaignUpdate) SetJoinedCount(v int) *LotteryCampaignUpdate {
	_u.mutation.ResetJoinedCount()
	_u.mutation.SetJoinedCount(v)
	return _u
}

// SetNillableJoinedCount sets the "joined_count" field if the given value is not nil.
func (_u *LotteryCampaignUpdate) SetNillableJoinedCount(v *int) *LotteryCampaignUpdate {
	if v != nil {
		_u.SetJoinedCount(*v)
	}
	return _u
}

// AddJoinedCount adds value to the "joined_count" field.
func (_u *LotteryCampaignUpdate) AddJoinedCount(v int) *LotteryCampaignUpdate {
	_u.mutation.AddJoinedCount(v)
	return _u
}

// SetWinnerCount sets the "winner_count" field.
func (_u *LotteryCampaignUpdate) SetWinnerCount(v int) *LotteryCampaignUpdate {
	_u.mutation.ResetWinnerCount()
	_u.mutation.SetWinnerCount(v)
	return _u
}

// SetNillableWinnerCount sets the "winner_count" field if the given value is not nil.
func (_u *LotteryCampaignUpdate) SetNillableWinnerCount(v *int) *LotteryCampaignUpdate {
	if v != nil {
		_u.SetWinnerCount(*v)
	}
	return _u
}

// AddWinnerCount adds value to the "winner_count" field.
func (_u *LotteryCampaignUpdate) AddWinnerCount(v int) *LotteryCampaignUpdate {
	_u.mutation.AddWinnerCount(v)
	return _u
}

// SetEarlyBoostParticipantPercent sets the "early_boost_participant_percent" field.
func (_u *LotteryCampaignUpdate) SetEarlyBoostParticipantPercent(v int) *LotteryCampaignUpdate {
	_u.mutation.ResetEarlyBoostParticipantPercent()
	_u.mutation.SetEarlyBoostParticipantPercent(v)
	return _u
}

// SetNillableEarlyBoostParticipantPercent sets the "early_boost_participant_percent" field if the given value is not nil.
func (_u *LotteryCampaignUpdate) SetNillableEarlyBoostParticipantPercent(v *int) *LotteryCampaignUpdate {
	if v != nil {
		_u.SetEarlyBoostParticipantPercent(*v)
	}
	return _u
}

// AddEarlyBoostParticipantPercent adds value to the "early_boost_participant_percent" field.
func (_u *LotteryCampaignUpdate) AddEarlyBoostParticipantPercent(v int) *LotteryCampaignUpdate {
	_u.mutation.AddEarlyBoostParticipantPercent(v)
	return _u
}

// SetRechargeBoostCapPercent sets the "recharge_boost_cap_percent" field.
func (_u *LotteryCampaignUpdate) SetRechargeBoostCapPercent(v int) *LotteryCampaignUpdate {
	_u.mutation.ResetRechargeBoostCapPercent()
	_u.mutation.SetRechargeBoostCapPercent(v)
	return _u
}

// SetNillableRechargeBoostCapPercent sets the "recharge_boost_cap_percent" field if the given value is not nil.
func (_u *LotteryCampaignUpdate) SetNillableRechargeBoostCapPercent(v *int) *LotteryCampaignUpdate {
	if v != nil {
		_u.SetRechargeBoostCapPercent(*v)
	}
	return _u
}

// AddRechargeBoostCapPercent adds value to the "recharge_boost_cap_percent" field.
func (_u *LotteryCampaignUpdate) AddRechargeBoostCapPercent(v int) *LotteryCampaignUpdate {
	_u.mutation.AddRechargeBoostCapPercent(v)
	return _u
}

// SetPromoText sets the "promo_text" field.
func (_u *LotteryCampaignUpdate) SetPromoText(v string) *LotteryCampaignUpdate {
	_u.mutation.SetPromoText(v)
	return _u
}

// SetNillablePromoText sets the "promo_text" field if the given value is not nil.
func (_u *LotteryCampaignUpdate) SetNillablePromoText(v *string) *LotteryCampaignUpdate {
	if v != nil {
		_u.SetPromoText(*v)
	}
	return _u
}

// SetPromoImageURL sets the "promo_image_url" field.
func (_u *LotteryCampaignUpdate) SetPromoImageURL(v string) *LotteryCampaignUpdate {
	_u.mutation.SetPromoImageURL(v)
	return _u
}

// SetNillablePromoImageURL sets the "promo_image_url" field if the given value is not nil.
func (_u *LotteryCampaignUpdate) SetNillablePromoImageURL(v *string) *LotteryCampaignUpdate {
	if v != nil {
		_u.SetPromoImageURL(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *LotteryCampaignUpdate) SetCreatedBy(v int64) *LotteryCampaignUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *LotteryCampaignUpdate) SetNillableCreatedBy(v *int64) *LotteryCampaignUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *LotteryCampaignUpdate) AddCreatedBy(v int64) *LotteryCampaignUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LotteryCampaignUpdate) SetUpdatedAt(v time.Time) *LotteryCampaignUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *LotteryCampaignUpdate) SetFinishedAt(v time.Time) *LotteryCampaignUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *LotteryCampaignUpdate) SetNillableFinishedAt(v *time.Time) *LotteryCampaignUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *LotteryCampaignUpdate) ClearFinishedAt() *LotteryCampaignUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// Mutation returns the LotteryCampaignMutation object of the builder.
func (_u *LotteryCampaignUpdate) Mutation() *LotteryCampaignMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LotteryCampaignUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LotteryCampaignUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LotteryCampaignUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LotteryCampaignUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LotteryCampaignUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := lotterycampaign.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LotteryCampaignUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := lotterycampaign.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "LotteryCampaign.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Subtitle(); ok {
		if err := lotterycampaign.SubtitleValidator(v); err != nil {
			return &ValidationError{Name: "subtitle", err: fmt.Errorf(`ent: validator failed for field "LotteryCampaign.subtitle": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := lotterycampaign.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "LotteryCampaign.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PrizeCount(); ok {
		if err := lotterycampaign.PrizeCountValidator(v); err != nil {
			return &ValidationError{Name: "prize_count", err: fmt.Errorf(`ent: validator failed for field "LotteryCampaign.prize_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxParticipants(); ok {
		if err := lotterycampaign.MaxParticipantsValidator(v); err != nil {
			return &ValidationError{Name: "max_participants", err: fmt.Errorf(`ent: validator failed for field "LotteryCampaign.max_participants": %w`, err)}
		}
	}
	if v, ok := _u.mutation.JoinedCount(); ok {
		if err := lotterycampaign.JoinedCountValidator(v); err != nil {
			return &ValidationError{Name: "joined_count", err: fmt.Errorf(`ent: validator failed for field "LotteryCampaign.joined_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WinnerCount(); ok {
		if err := lotterycampaign.WinnerCountValidator(v); err != nil {
			return &ValidationError{Name: "winner_count", err: fmt.Errorf(`ent: validator failed for field "LotteryCampaign.winner_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EarlyBoostParticipantPercent(); ok {
		if err := lotterycampaign.EarlyBoostParticipantPercentValidator(v); err != nil {
			return &ValidationError{Name: "early_boost_participant_percent", err: fmt.Errorf(`ent: validator failed for field "LotteryCampaign.early_boost_participant_percent": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RechargeBoostCapPercent(); ok {
		if err := lotterycampaign.RechargeBoostCapPercentValidator(v); err != nil {
			return &ValidationError{Name: "recharge_boost_cap_percent", err: fmt.Errorf(`ent: validator failed for field "LotteryCampaign.recharge_boost_cap_percent": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PromoText(); ok {
		if err := lotterycampaign.PromoTextValidator(v); err != nil {
			return &ValidationError{Name: "promo_text", err: fmt.Errorf(`ent: validator failed for field "LotteryCampaign.promo_text": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PromoImageURL(); ok {
		if err := lotterycampaign.PromoImageURLValidator(v); err != nil {
			return &ValidationError{Name: "promo_image_url", err: fmt.Errorf(`ent: validator failed for field "LotteryCampaign.promo_image_url": %w`, err)}
		}
	}
	return nil
}

func (_u *LotteryCampaignUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(lotterycampaign.Table, lotterycampaign.Columns, sqlgraph.NewFieldSpec(lotterycampaign.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(lotterycampaign.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subtitle(); ok {
		_spec.SetField(lotterycampaign.FieldSubtitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(lotterycampaign.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.PrizeCount(); ok {
		_spec.SetField(lotterycampaign.FieldPrizeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPrizeCount(); ok {
		_spec.AddField(lotterycampaign.FieldPrizeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxParticipants(); ok {
		_spec.SetField(lotterycampaign.FieldMaxParticipants, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxParticipants(); ok {
		_spec.AddField(lotterycampaign.FieldMaxParticipants, field.TypeInt, value)
	}
	if value, ok := _u.mutation.JoinedCount(); ok {
		_spec.SetField(lotterycampaign.FieldJoinedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedJoinedCount(); ok {
		_spec.AddField(lotterycampaign.FieldJoinedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.WinnerCount(); ok {
		_spec.SetField(lotterycampaign.FieldWinnerCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWinnerCount(); ok {
		_spec.AddField(lotterycampaign.FieldWinnerCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EarlyBoostParticipantPercent(); ok {
		_spec.SetField(lotterycampaign.FieldEarlyBoostParticipantPercent, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEarlyBoostParticipantPercent(); ok {
		_spec.AddField(lotterycampaign.FieldEarlyBoostParticipantPercent, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RechargeBoostCapPercent(); ok {
		_spec.SetField(lotterycampaign.FieldRechargeBoostCapPercent, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRechargeBoostCapPercent(); ok {
		_spec.AddField(lotterycampaign.FieldRechargeBoostCapPercent, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PromoText(); ok {
		_spec.SetField(lotterycampaign.FieldPromoText, field.TypeString, value)
	}
	if value, ok := _u.mutation.PromoImageURL(); ok {
		_spec.SetField(lotterycampaign.FieldPromoImageURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(lotterycampaign.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(lotterycampaign.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(lotterycampaign.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(lotterycampaign.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(lotterycampaign.FieldFinishedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lotterycampaign.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LotteryCampaignUpdateOne is the builder for updating a single LotteryCampaign entity.
type LotteryCampaignUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LotteryCampaignMutation
}

// SetName sets the "name" field.
func (_u *LotteryCampaignUpdateOne) SetName(v string) *LotteryCampaignUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *LotteryCampaignUpdateOne) SetNillableName(v *string) *LotteryCampaignUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSubtitle sets the "subtitle" field.
func (_u *LotteryCampaignUpdateOne) SetSubtitle(v string) *LotteryCampaignUpdateOne {
	_u.mutation.SetSubtitle(v)
	return _u
}

// SetNillableSubtitle sets the "subtitle" field if the given value is not nil.
func (_u *LotteryCampaignUpdateOne) SetNillableSubtitle(v *string) *LotteryCampaignUpdateOne {
	if v != nil {
		_u.SetSubtitle(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *LotteryCampaignUpdateOne) SetStatus(v string) *LotteryCampaignUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *LotteryCampaignUpdateOne) SetNillableStatus(v *string) *LotteryCampaignUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPrizeCount sets the "prize_count" field.
func (_u *LotteryCampaignUpdateOne) SetPrizeCount(v int) *LotteryCampaignUpdateOne {
	_u.mutation.ResetPrizeCount()
	_u.mutation.SetPrizeCount(v)
	return _u
}

// SetNillablePrizeCount sets the "prize_count" field if the given value is not nil.
func (_u *LotteryCampaignUpdateOne) SetNillablePrizeCount(v *int) *LotteryCampaignUpdateOne {
	if v != nil {
		_u.SetPrizeCount(*v)
	}
	return _u
}

// AddPrizeCount adds value to the "prize_count" field.
func (_u *LotteryCampaignUpdateOne) AddPrizeCount(v int) *LotteryCampaignUpdateOne {
	_u.mutation.AddPrizeCount(v)
	return _u
}

// SetMaxParticipants sets the "max_participants" field.
func (_u *LotteryCampaignUpdateOne) SetMaxParticipants(v int) *LotteryCampaignUpdateOne {
	_u.mutation.ResetMaxParticipants()
	_u.mutation.SetMaxParticipants(v)
	return _u
}

// SetNillableMaxParticipants sets the "max_participants" field if the given value is not nil.
func (_u *LotteryCampaignUpdateOne) SetNillableMaxParticipants(v *int) *LotteryCampaignUpdateOne {
	if v != nil {
		_u.SetMaxParticipants(*v)
	}
	return _u
}

// AddMaxParticipants adds value to the "max_participants" field.
func (_u *LotteryCampaignUpdateOne) AddMaxParticipants(v int) *LotteryCampaignUpdateOne {
	_u.mutation.AddMaxParticipants(v)
	return _u
}

// SetJoinedCount sets the "joined_count" field.
func (_u *LotteryCampaignUpdateOne) SetJoinedCount(v int) *LotteryCampaignUpdateOne {
	_u.mutation.ResetJoinedCount()
	_u.mutation.SetJoinedCount(v)
	return _u
}

// SetNillableJoinedCount sets the "joined_count" field if the given value is not nil.
func (_u *LotteryCampaignUpdateOne) SetNillableJoinedCount(v *int) *LotteryCampaignUpdateOne {
	if v != nil {
		_u.SetJoinedCount(*v)
	}
	return _u
}

// AddJoinedCount adds value to the "joined_count" field.
func (_u *LotteryCampaignUpdateOne) AddJoinedCount(v int) *LotteryCampaignUpdateOne {
	_u.mutation.AddJoinedCount(v)
	return _u
}

// SetWinnerCount sets the "winner_count" field.
func (_u *LotteryCampaignUpdateOne) SetWinnerCount(v int) *LotteryCampaignUpdateOne {
	_u.mutation.ResetWinnerCount()
	_u.mutation.SetWinnerCount(v)
	return _u
}

// SetNillableWinnerCount sets the "winner_count" field if the given value is not nil.
func (_u *LotteryCampaignUpdateOne) SetNillableWinnerCount(v *int) *LotteryCampaignUpdateOne {
	if v != nil {
		_u.SetWinnerCount(*v)
	}
	return _u
}

// AddWinnerCount adds value to the "winner_count" field.
func (_u *LotteryCampaignUpdateOne) AddWinnerCount(v int) *LotteryCampaignUpdateOne {
	_u.mutation.AddWinnerCount(v)
	return _u
}

// SetEarlyBoostParticipantPercent sets the "early_boost_participant_percent" field.
func (_u *LotteryCampaignUpdateOne) SetEarlyBoostParticipantPercent(v int) *LotteryCampaignUpdateOne {
	_u.mutation.ResetEarlyBoostParticipantPercent()
	_u.mutation.SetEarlyBoostParticipantPercent(v)
	return _u
}

// SetNillableEarlyBoostParticipantPercent sets the "early_boost_participant_percent" field if the given value is not nil.
func (_u *LotteryCampaignUpdateOne) SetNillableEarlyBoostParticipantPercent(v *int) *LotteryCampaignUpdateOne {
	if v != nil {
		_u.SetEarlyBoostParticipantPercent(*v)
	}
	return _u
}

// AddEarlyBoostParticipantPercent adds value to the "early_boost_participant_percent" field.
func (_u *LotteryCampaignUpdateOne) AddEarlyBoostParticipantPercent(v int) *LotteryCampaignUpdateOne {
	_u.mutation.AddEarlyBoostParticipantPercent(v)
	return _u
}

// SetRechargeBoostCapPercent sets the "recharge_boost_cap_percent" field.
func (_u *LotteryCampaignUpdateOne) SetRechargeBoostCapPercent(v int) *LotteryCampaignUpdateOne {
	_u.mutation.ResetRechargeBoostCapPercent()
	_u.mutation.SetRechargeBoostCapPercent(v)
	return _u
}

// SetNillableRechargeBoostCapPercent sets the "recharge_boost_cap_percent" field if the given value is not nil.
func (_u *LotteryCampaignUpdateOne) SetNillableRechargeBoostCapPercent(v *int) *LotteryCampaignUpdateOne {
	if v != nil {
		_u.SetRechargeBoostCapPercent(*v)
	}
	return _u
}

// AddRechargeBoostCapPercent adds value to the "recharge_boost_cap_percent" field.
func (_u *LotteryCampaignUpdateOne) AddRechargeBoostCapPercent(v int) *LotteryCampaignUpdateOne {
	_u.mutation.AddRechargeBoostCapPercent(v)
	return _u
}

// SetPromoText sets the "promo_text" field.
func (_u *LotteryCampaignUpdateOne) SetPromoText(v string) *LotteryCampaignUpdateOne {
	_u.mutation.SetPromoText(v)
	return _u
}

// SetNillablePromoText sets the "promo_text" field if the given value is not nil.
func (_u *LotteryCampaignUpdateOne) SetNillablePromoText(v *string) *LotteryCampaignUpdateOne {
	if v != nil {
		_u.SetPromoText(*v)
	}
	return _u
}

// SetPromoImageURL sets the "promo_image_url" field.
func (_u *LotteryCampaignUpdateOne) SetPromoImageURL(v string) *LotteryCampaignUpdateOne {
	_u.mutation.SetPromoImageURL(v)
	return _u
}

// SetNillablePromoImageURL sets the "promo_image_url" field if the given value is not nil.
func (_u *LotteryCampaignUpdateOne) SetNillablePromoImageURL(v *string) *LotteryCampaignUpdateOne {
	if v != nil {
		_u.SetPromoImageURL(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *LotteryCampaignUpdateOne) SetCreatedBy(v int64) *LotteryCampaignUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *LotteryCampaignUpdateOne) SetNillableCreatedBy(v *int64) *LotteryCampaignUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *LotteryCampaignUpdateOne) AddCreatedBy(v int64) *LotteryCampaignUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LotteryCampaignUpdateOne) SetUpdatedAt(v time.Time) *LotteryCampaignUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *LotteryCampaignUpdateOne) SetFinishedAt(v time.Time) *LotteryCampaignUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *LotteryCampaignUpdateOne) SetNillableFinishedAt(v *time.Time) *LotteryCampaignUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *LotteryCampaignUpdateOne) ClearFinishedAt() *LotteryCampaignUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// Mutation returns the LotteryCampaignMutation object of the builder.
func (_u *LotteryCampaignUpdateOne) Mutation() *LotteryCampaignMutation {
	return _u.mutation
}

// Where appends a list predicates to the LotteryCampaignUpdate builder.
func (_u *LotteryCampaignUpdateOne) Where(ps ...predicate.LotteryCampaign) *LotteryCampaignUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LotteryCampaignUpdateOne) Select(field string, fields ...string) *LotteryCampaignUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LotteryCampaign entity.
func (_u *LotteryCampaignUpdateOne) Save(ctx context.Context) (*LotteryCampaign, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LotteryCampaignUpdateOne) SaveX(ctx context.Context) *LotteryCampaign {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LotteryCampaignUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LotteryCampaignUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LotteryCampaignUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := lotterycampaign.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LotteryCampaignUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := lotterycampaign.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "LotteryCampaign.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Subtitle(); ok {
		if err := lotterycampaign.SubtitleValidator(v); err != nil {
			return &ValidationError{Name: "subtitle", err: fmt.Errorf(`ent: validator failed for field "LotteryCampaign.subtitle": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := lotterycampaign.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "LotteryCampaign.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PrizeCount(); ok {
		if err := lotterycampaign.PrizeCountValidator(v); err != nil {
			return &ValidationError{Name: "prize_count", err: fmt.Errorf(`ent: validator failed for field "LotteryCampaign.prize_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxParticipants(); ok {
		if err := lotterycampaign.MaxParticipantsValidator(v); err != nil {
			return &ValidationError{Name: "max_participants", err: fmt.Errorf(`ent: validator failed for field "LotteryCampaign.max_participants": %w`, err)}
		}
	}
	if v, ok := _u.mutation.JoinedCount(); ok {
		if err := lotterycampaign.JoinedCountValidator(v); err != nil {
			return &ValidationError{Name: "joined_count", err: fmt.Errorf(`ent: validator failed for field "LotteryCampaign.joined_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WinnerCount(); ok {
		if err := lotterycampaign.WinnerCountValidator(v); err != nil {
			return &ValidationError{Name: "winner_count", err: fmt.Errorf(`ent: validator failed for field "LotteryCampaign.winner_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EarlyBoostParticipantPercent(); ok {
		if err := lotterycampaign.EarlyBoostParticipantPercentValidator(v); err != nil {
			return &ValidationError{Name: "early_boost_participant_percent", err: fmt.Errorf(`ent: validator failed for field "LotteryCampaign.early_boost_participant_percent": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RechargeBoostCapPercent(); ok {
		if err := lotterycampaign.RechargeBoostCapPercentValidator(v); err != nil {
			return &ValidationError{Name: "recharge_boost_cap_percent", err: fmt.Errorf(`ent: validator failed for field "LotteryCampaign.recharge_boost_cap_percent": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PromoText(); ok {
		if err := lotterycampaign.PromoTextValidator(v); err != nil {
			return &ValidationError{Name: "promo_text", err: fmt.Errorf(`ent: validator failed for field "LotteryCampaign.promo_text": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PromoImageURL(); ok {
		if err := lotterycampaign.PromoImageURLValidator(v); err != nil {
			return &ValidationError{Name: "promo_image_url", err: fmt.Errorf(`ent: validator failed for field "LotteryCampaign.promo_image_url": %w`, err)}
		}
	}
	return nil
}

func (_u *LotteryCampaignUpdateOne) sqlSave(ctx context.Context) (_node *LotteryCampaign, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(lotterycampaign.Table, lotterycampaign.Columns, sqlgraph.NewFieldSpec(lotterycampaign.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LotteryCampaign.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lotterycampaign.FieldID)
		for _, f := range fields {
			if !lotterycampaign.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != lotterycampaign.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(lotterycampaign.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subtitle(); ok {
		_spec.SetField(lotterycampaign.FieldSubtitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(lotterycampaign.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.PrizeCount(); ok {
		_spec.SetField(lotterycampaign.FieldPrizeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPrizeCount(); ok {
		_spec.AddField(lotterycampaign.FieldPrizeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxParticipants(); ok {
		_spec.SetField(lotterycampaign.FieldMaxParticipants, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxParticipants(); ok {
		_spec.AddField(lotterycampaign.FieldMaxParticipants, field.TypeInt, value)
	}
	if value, ok := _u.mutation.JoinedCount(); ok {
		_spec.SetField(lotterycampaign.FieldJoinedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedJoinedCount(); ok {
		_spec.AddField(lotterycampaign.FieldJoinedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.WinnerCount(); ok {
		_spec.SetField(lotterycampaign.FieldWinnerCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWinnerCount(); ok {
		_spec.AddField(lotterycampaign.FieldWinnerCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EarlyBoostParticipantPercent(); ok {
		_spec.SetField(lotterycampaign.FieldEarlyBoostParticipantPercent, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEarlyBoostParticipantPercent(); ok {
		_spec.AddField(lotterycampaign.FieldEarlyBoostParticipantPercent, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RechargeBoostCapPercent(); ok {
		_spec.SetField(lotterycampaign.FieldRechargeBoostCapPercent, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRechargeBoostCapPercent(); ok {
		_spec.AddField(lotterycampaign.FieldRechargeBoostCapPercent, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PromoText(); ok {
		_spec.SetField(lotterycampaign.FieldPromoText, field.TypeString, value)
	}
	if value, ok := _u.mutation.PromoImageURL(); ok {
		_spec.SetField(lotterycampaign.FieldPromoImageURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(lotterycampaign.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(lotterycampaign.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(lotterycampaign.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(lotterycampaign.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(lotterycampaign.FieldFinishedAt, field.TypeTime)
	}
	_node = &LotteryCampaign{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lotterycampaign.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
