// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/lotterydraw"
)

// LotteryDraw is the model entity for the LotteryDraw schema.
type LotteryDraw struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CampaignID holds the value of the "campaign_id" field.
	CampaignID int64 `json:"campaign_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Won holds the value of the "won" field.
	Won bool `json:"won,omitempty"`
	// LotteryCodeID holds the value of the "lottery_code_id" field.
	LotteryCodeID *int64 `json:"lottery_code_id,omitempty"`
	// SiteMessageID holds the value of the "site_message_id" field.
	SiteMessageID *int64 `json:"site_message_id,omitempty"`
	// ResultLabel holds the value of the "result_label" field.
	ResultLabel string `json:"result_label,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LotteryDraw) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case lotterydraw.FieldWon:
			values[i] = new(sql.NullBool)
		case lotterydraw.FieldID, lotterydraw.FieldCampaignID, lotterydraw.FieldUserID, lotterydraw.FieldLotteryCodeID, lotterydraw.FieldSiteMessageID:
			values[i] = new(sql.NullInt64)
		case lotterydraw.FieldResultLabel:
			values[i] = new(sql.NullString)
		case lotterydraw.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LotteryDraw fields.
func (_m *LotteryDraw) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case lotterydraw.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case lotterydraw.FieldCampaignID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field campaign_id", values[i])
			} else if value.Valid {
				_m.CampaignID = value.Int64
			}
		case lotterydraw.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case lotterydraw.FieldWon:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field won", values[i])
			} else if value.Valid {
				_m.Won = value.Bool
			}
		case lotterydraw.FieldLotteryCodeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field lottery_code_id", values[i])
			} else if value.Valid {
				_m.LotteryCodeID = new(int64)
				*_m.LotteryCodeID = value.Int64
			}
		case lotterydraw.FieldSiteMessageID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field site_message_id", values[i])
			} else if value.Valid {
				_m.SiteMessageID = new(int64)
				*_m.SiteMessageID = value.Int64
			}
		case lotterydraw.FieldResultLabel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field result_label", values[i])
			} else if value.Valid {
				_m.ResultLabel = value.String
			}
		case lotterydraw.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LotteryDraw.
// This includes values selected through modifiers, order, etc.
func (_m *LotteryDraw) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this LotteryDraw.
// Note that you need to call LotteryDraw.Unwrap() before calling this method if this LotteryDraw
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *LotteryDraw) Update() *LotteryDrawUpdateOne {
	return NewLotteryDrawClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the LotteryDraw entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *LotteryDraw) Unwrap() *LotteryDraw {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: LotteryDraw is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *LotteryDraw) String() string {
	var builder strings.Builder
	builder.WriteString("LotteryDraw(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("campaign_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CampaignID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("won=")
	builder.WriteString(fmt.Sprintf("%v", _m.Won))
	builder.WriteString(", ")
	if v := _m.LotteryCodeID; v != nil {
		builder.WriteString("lottery_code_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SiteMessageID; v != nil {
		builder.WriteString("site_message_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("result_label=")
	builder.WriteString(_m.ResultLabel)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// LotteryDraws is a parsable slice of LotteryDraw.
type LotteryDraws []*LotteryDraw
