// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/lotterycampaign"
)

// LotteryCampaignCreate is the builder for creating a LotteryCampaign entity.
type LotteryCampaignCreate struct {
	config
	mutation *LotteryCampaignMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *LotteryCampaignCreate) SetName(v string) *LotteryCampaignCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetSubtitle sets the "subtitle" field.
func (_c *LotteryCampaignCreate) SetSubtitle(v string) *LotteryCampaignCreate {
	_c.mutation.SetSubtitle(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *LotteryCampaignCreate) SetStatus(v string) *LotteryCampaignCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *LotteryCampaignCreate) SetNillableStatus(v *string) *LotteryCampaignCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetPrizeCount sets the "prize_count" field.
func (_c *LotteryCampaignCreate) SetPrizeCount(v int) *LotteryCampaignCreate {
	_c.mutation.SetPrizeCount(v)
	return _c
}

// SetMaxParticipants sets the "max_participants" field.
func (_c *LotteryCampaignCreate) SetMaxParticipants(v int) *LotteryCampaignCreate {
	_c.mutation.SetMaxParticipants(v)
	return _c
}

// SetJoinedCount sets the "joined_count" field.
func (_c *LotteryCampaignCreate) SetJoinedCount(v int) *LotteryCampaignCreate {
	_c.mutation.SetJoinedCount(v)
	return _c
}

// SetNillableJoinedCount sets the "joined_count" field if the given value is not nil.
func (_c *LotteryCampaignCreate) SetNillableJoinedCount(v *int) *LotteryCampaignCreate {
	if v != nil {
		_c.SetJoinedCount(*v)
	}
	return _c
}

// SetWinnerCount sets the "winner_count" field.
func (_c *LotteryCampaignCreate) SetWinnerCount(v int) *LotteryCampaignCreate {
	_c.mutation.SetWinnerCount(v)
	return _c
}

// SetNillableWinnerCount sets the "winner_count" field if the given value is not nil.
func (_c *LotteryCampaignCreate) SetNillableWinnerCount(v *int) *LotteryCampaignCreate {
	if v != nil {
		_c.SetWinnerCount(*v)
	}
	return _c
}

// SetEarlyBoostParticipantPercent sets the "early_boost_participant_percent" field.
func (_c *LotteryCampaignCreate) SetEarlyBoostParticipantPercent(v int) *LotteryCampaignCreate {
	_c.mutation.SetEarlyBoostParticipantPercent(v)
	return _c
}

// SetNillableEarlyBoostParticipantPercent sets the "early_boost_participant_percent" field if the given value is not nil.
func (_c *LotteryCampaignCreate) SetNillableEarlyBoostParticipantPercent(v *int) *LotteryCampaignCreate {
	if v != nil {
		_c.SetEarlyBoostParticipantPercent(*v)
	}
	return _c
}

// SetRechargeBoostCapPercent sets the "recharge_boost_cap_percent" field.
func (_c *LotteryCampaignCreate) SetRechargeBoostCapPercent(v int) *LotteryCampaignCreate {
	_c.mutation.SetRechargeBoostCapPercent(v)
	return _c
}

// SetNillableRechargeBoostCapPercent sets the "recharge_boost_cap_percent" field if the given value is not nil.
func (_c *LotteryCampaignCreate) SetNillableRechargeBoostCapPercent(v *int) *LotteryCampaignCreate {
	if v != nil {
		_c.SetRechargeBoostCapPercent(*v)
	}
	return _c
}

// SetPromoText sets the "promo_text" field.
func (_c *LotteryCampaignCreate) SetPromoText(v string) *LotteryCampaignCreate {
	_c.mutation.SetPromoText(v)
	return _c
}

// SetNillablePromoText sets the "promo_text" field if the given value is not nil.
func (_c *LotteryCampaignCreate) SetNillablePromoText(v *string) *LotteryCampaignCreate {
	if v != nil {
		_c.SetPromoText(*v)
	}
	return _c
}

// SetPromoImageURL sets the "promo_image_url" field.
func (_c *LotteryCampaignCreate) SetPromoImageURL(v string) *LotteryCampaignCreate {
	_c.mutation.SetPromoImageURL(v)
	return _c
}

// SetNillablePromoImageURL sets the "promo_image_url" field if the given value is not nil.
func (_c *LotteryCampaignCreate) SetNillablePromoImageURL(v *string) *LotteryCampaignCreate {
	if v != nil {
		_c.SetPromoImageURL(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *LotteryCampaignCreate) SetCreatedBy(v int64) *LotteryCampaignCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *LotteryCampaignCreate) SetCreatedAt(v time.Time) *LotteryCampaignCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LotteryCampaignCreate) SetNillableCreatedAt(v *time.Time) *LotteryCampaignCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *LotteryCampaignCreate) SetUpdatedAt(v time.Time) *LotteryCampaignCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *LotteryCampaignCreate) SetNillableUpdatedAt(v *time.Time) *LotteryCampaignCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetFinishedAt sets the "finished_at" field.
func (_c *LotteryCampaignCreate) SetFinishedAt(v time.Time) *LotteryCampaignCreate {
	_c.mutation.SetFinishedAt(v)
	return _c
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_c *LotteryCampaignCreate) SetNillableFinishedAt(v *time.Time) *LotteryCampaignCreate {
	if v != nil {
		_c.SetFinishedAt(*v)
	}
	return _c
}

// Mutation returns the LotteryCampaignMutation object of the builder.
func (_c *LotteryCampaignCreate) Mutation() *LotteryCampaignMutation {
	return _c.mutation
}

// Save creates the LotteryCampaign in the database.
func (_c *LotteryCampaignCreate) Save(ctx context.Context) (*LotteryCampaign, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LotteryCampaignCreate) SaveX(ctx context.Context) *LotteryCampaign {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LotteryCampaignCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LotteryCampaignCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LotteryCampaignCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := lotterycampaign.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.JoinedCount(); !ok {
		v := lotterycampaign.DefaultJoinedCount
		_c.mutation.SetJoinedCount(v)
	}
	if _, ok := _c.mutation.WinnerCount(); !ok {
		v := lotterycampaign.DefaultWinnerCount
		_c.mutation.SetWinnerCount(v)
	}
	if _, ok := _c.mutation.EarlyBoostParticipantPercent(); !ok {
		v := lotterycampaign.DefaultEarlyBoostParticipantPercent
		_c.mutation.SetEarlyBoostParticipantPercent(v)
	}
	if _, ok := _c.mutation.RechargeBoostCapPercent(); !ok {
		v := lotterycampaign.DefaultRechargeBoostCapPercent
		_c.mutation.SetRechargeBoostCapPercent(v)
	}
	if _, ok := _c.mutation.PromoText(); !ok {
		v := lotterycampaign.DefaultPromoText
		_c.mutation.SetPromoText(v)
	}
	if _, ok := _c.mutation.PromoImageURL(); !ok {
		v := lotterycampaign.DefaultPromoImageURL
		_c.mutation.SetPromoImageURL(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := lotterycampaign.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := lotterycampaign.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LotteryCampaignCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "LotteryCampaign.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := lotterycampaign.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "LotteryCampaign.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Subtitle(); !ok {
		return &ValidationError{Name: "subtitle", err: errors.New(`ent: missing required field "LotteryCampaign.subtitle"`)}
	}
	if v, ok := _c.mutation.Subtitle(); ok {
		if err := lotterycampaign.SubtitleValidator(v); err != nil {
			return &ValidationError{Name: "subtitle", err: fmt.Errorf(`ent: validator failed for field "LotteryCampaign.subtitle": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "LotteryCampaign.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := lotterycampaign.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "LotteryCampaign.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PrizeCount(); !ok {
		return &ValidationError{Name: "prize_count", err: errors.New(`ent: missing required field "LotteryCampaign.prize_count"`)}
	}
	if v, ok := _c.mutation.PrizeCount(); ok {
		if err := lotterycampaign.PrizeCountValidator(v); err != nil {
			return &ValidationError{Name: "prize_count", err: fmt.Errorf(`ent: validator failed for field "LotteryCampaign.prize_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MaxParticipants(); !ok {
		return &ValidationError{Name: "max_participants", err: errors.New(`ent: missing required field "LotteryCampaign.max_participants"`)}
	}
	if v, ok := _c.mutation.MaxParticipants(); ok {
		if err := lotterycampaign.MaxParticipantsValidator(v); err != nil {
			return &ValidationError{Name: "max_participants", err: fmt.Errorf(`ent: validator failed for field "LotteryCampaign.max_participants": %w`, err)}
		}
	}
	if _, ok := _c.mutation.JoinedCount(); !ok {
		return &ValidationError{Name: "joined_count", err: errors.New(`ent: missing required field "LotteryCampaign.joined_count"`)}
	}
	if v, ok := _c.mutation.JoinedCount(); ok {
		if err := lotterycampaign.JoinedCountValidator(v); err != nil {
			return &ValidationError{Name: "joined_count", err: fmt.Errorf(`ent: validator failed for field "LotteryCampaign.joined_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.WinnerCount(); !ok {
		return &ValidationError{Name: "winner_count", err: errors.New(`ent: missing required field "LotteryCampaign.winner_count"`)}
	}
	if v, ok := _c.mutation.WinnerCount(); ok {
		if err := lotterycampaign.WinnerCountValidator(v); err != nil {
			return &ValidationError{Name: "winner_count", err: fmt.Errorf(`ent: validator failed for field "LotteryCampaign.winner_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EarlyBoostParticipantPercent(); !ok {
		return &ValidationError{Name: "early_boost_participant_percent", err: errors.New(`ent: missing required field "LotteryCampaign.early_boost_participant_percent"`)}
	}
	if v, ok := _c.mutation.EarlyBoostParticipantPercent(); ok {
		if err := lotterycampaign.EarlyBoostParticipantPercentValidator(v); err != nil {
			return &ValidationError{Name: "early_boost_participant_percent", err: fmt.Errorf(`ent: validator failed for field "LotteryCampaign.early_boost_participant_percent": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RechargeBoostCapPercent(); !ok {
		return &ValidationError{Name: "recharge_boost_cap_percent", err: errors.New(`ent: missing required field "LotteryCampaign.recharge_boost_cap_percent"`)}
	}
	if v, ok := _c.mutation.RechargeBoostCapPercent(); ok {
		if err := lotterycampaign.RechargeBoostCapPercentValidator(v); err != nil {
			return &ValidationError{Name: "recharge_boost_cap_percent", err: fmt.Errorf(`ent: validator failed for field "LotteryCampaign.recharge_boost_cap_percent": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PromoText(); !ok {
		return &ValidationError{Name: "promo_text", err: errors.New(`ent: missing required field "LotteryCampaign.promo_text"`)}
	}
	if v, ok := _c.mutation.PromoText(); ok {
		if err := lotterycampaign.PromoTextValidator(v); err != nil {
			return &ValidationError{Name: "promo_text", err: fmt.Errorf(`ent: validator failed for field "LotteryCampaign.promo_text": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PromoImageURL(); !ok {
		return &ValidationError{Name: "promo_image_url", err: errors.New(`ent: missing required field "LotteryCampaign.promo_image_url"`)}
	}
	if v, ok := _c.mutation.PromoImageURL(); ok {
		if err := lotterycampaign.PromoImageURLValidator(v); err != nil {
			return &ValidationError{Name: "promo_image_url", err: fmt.Errorf(`ent: validator failed for field "LotteryCampaign.promo_image_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "LotteryCampaign.created_by"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LotteryCampaign.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "LotteryCampaign.updated_at"`)}
	}
	return nil
}

func (_c *LotteryCampaignCreate) sqlSave(ctx context.Context) (*LotteryCampaign, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LotteryCampaignCreate) createSpec() (*LotteryCampaign, *sqlgraph.CreateSpec) {
	var (
		_node = &LotteryCampaign{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(lotterycampaign.Table, sqlgraph.NewFieldSpec(lotterycampaign.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(lotterycampaign.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Subtitle(); ok {
		_spec.SetField(lotterycampaign.FieldSubtitle, field.TypeString, value)
		_node.Subtitle = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(lotterycampaign.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.PrizeCount(); ok {
		_spec.SetField(lotterycampaign.FieldPrizeCount, field.TypeInt, value)
		_node.PrizeCount = value
	}
	if value, ok := _c.mutation.MaxParticipants(); ok {
		_spec.SetField(lotterycampaign.FieldMaxParticipants, field.TypeInt, value)
		_node.MaxParticipants = value
	}
	if value, ok := _c.mutation.JoinedCount(); ok {
		_spec.SetField(lotterycampaign.FieldJoinedCount, field.TypeInt, value)
		_node.JoinedCount = value
	}
	if value, ok := _c.mutation.WinnerCount(); ok {
		_spec.SetField(lotterycampaign.FieldWinnerCount, field.TypeInt, value)
		_node.WinnerCount = value
	}
	if value, ok := _c.mutation.EarlyBoostParticipantPercent(); ok {
		_spec.SetField(lotterycampaign.FieldEarlyBoostParticipantPercent, field.TypeInt, value)
		_node.EarlyBoostParticipantPercent = value
	}
	if value, ok := _c.mutation.RechargeBoostCapPercent(); ok {
		_spec.SetField(lotterycampaign.FieldRechargeBoostCapPercent, field.TypeInt, value)
		_node.RechargeBoostCapPercent = value
	}
	if value, ok := _c.mutation.PromoText(); ok {
		_spec.SetField(lotterycampaign.FieldPromoText, field.TypeString, value)
		_node.PromoText = value
	}
	if value, ok := _c.mutation.PromoImageURL(); ok {
		_spec.SetField(lotterycampaign.FieldPromoImageURL, field.TypeString, value)
		_node.PromoImageURL = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(lotterycampaign.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(lotterycampaign.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(lotterycampaign.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.FinishedAt(); ok {
		_spec.SetField(lotterycampaign.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LotteryCampaign.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LotteryCampaignUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *LotteryCampaignCreate) OnConflict(opts ...sql.ConflictOption) *LotteryCampaignUpsertOne {
	_c.conflict = opts
	return &LotteryCampaignUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LotteryCampaign.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LotteryCampaignCreate) OnConflictColumns(columns ...string) *LotteryCampaignUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LotteryCampaignUpsertOne{
		create: _c,
	}
}

type (
	// LotteryCampaignUpsertOne is the builder for "upsert"-ing
	//  one LotteryCampaign node.
	LotteryCampaignUpsertOne struct {
		create *LotteryCampaignCreate
	}

	// LotteryCampaignUpsert is the "OnConflict" setter.
	LotteryCampaignUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *LotteryCampaignUpsert) SetName(v string) *LotteryCampaignUpsert {
	u.Set(lotterycampaign.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *LotteryCampaignUpsert) UpdateName() *LotteryCampaignUpsert {
	u.SetExcluded(lotterycampaign.FieldName)
	return u
}

// SetSubtitle sets the "subtitle" field.
func (u *LotteryCampaignUpsert) SetSubtitle(v string) *LotteryCampaignUpsert {
	u.Set(lotterycampaign.FieldSubtitle, v)
	return u
}

// UpdateSubtitle sets the "subtitle" field to the value that was provided on create.
func (u *LotteryCampaignUpsert) UpdateSubtitle() *LotteryCampaignUpsert {
	u.SetExcluded(lotterycampaign.FieldSubtitle)
	return u
}

// SetStatus sets the "status" field.
func (u *LotteryCampaignUpsert) SetStatus(v string) *LotteryCampaignUpsert {
	u.Set(lotterycampaign.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LotteryCampaignUpsert) UpdateStatus() *LotteryCampaignUpsert {
	u.SetExcluded(lotterycampaign.FieldStatus)
	return u
}

// SetPrizeCount sets the "prize_count" field.
func (u *LotteryCampaignUpsert) SetPrizeCount(v int) *LotteryCampaignUpsert {
	u.Set(lotterycampaign.FieldPrizeCount, v)
	return u
}

// UpdatePrizeCount sets the "prize_count" field to the value that was provided on create.
func (u *LotteryCampaignUpsert) UpdatePrizeCount() *LotteryCampaignUpsert {
	u.SetExcluded(lotterycampaign.FieldPrizeCount)
	return u
}

// AddPrizeCount adds v to the "prize_count" field.
func (u *LotteryCampaignUpsert) AddPrizeCount(v int) *LotteryCampaignUpsert {
	u.Add(lotterycampaign.FieldPrizeCount, v)
	return u
}

// SetMaxParticipants sets the "max_participants" field.
func (u *LotteryCampaignUpsert) SetMaxParticipants(v int) *LotteryCampaignUpsert {
	u.Set(lotterycampaign.FieldMaxParticipants, v)
	return u
}

// UpdateMaxParticipants sets the "max_participants" field to the value that was provided on create.
func (u *LotteryCampaignUpsert) UpdateMaxParticipants() *LotteryCampaignUpsert {
	u.SetExcluded(lotterycampaign.FieldMaxParticipants)
	return u
}

// AddMaxParticipants adds v to the "max_participants" field.
func (u *LotteryCampaignUpsert) AddMaxParticipants(v int) *LotteryCampaignUpsert {
	u.Add(lotterycampaign.FieldMaxParticipants, v)
	return u
}

// SetJoinedCount sets the "joined_count" field.
func (u *LotteryCampaignUpsert) SetJoinedCount(v int) *LotteryCampaignUpsert {
	u.Set(lotterycampaign.FieldJoinedCount, v)
	return u
}

// UpdateJoinedCount sets the "joined_count" field to the value that was provided on create.
func (u *LotteryCampaignUpsert) UpdateJoinedCount() *LotteryCampaignUpsert {
	u.SetExcluded(lotterycampaign.FieldJoinedCount)
	return u
}

// AddJoinedCount adds v to the "joined_count" field.
func (u *LotteryCampaignUpsert) AddJoinedCount(v int) *LotteryCampaignUpsert {
	u.Add(lotterycampaign.FieldJoinedCount, v)
	return u
}

// SetWinnerCount sets the "winner_count" field.
func (u *LotteryCampaignUpsert) SetWinnerCount(v int) *LotteryCampaignUpsert {
	u.Set(lotterycampaign.FieldWinnerCount, v)
	return u
}

// UpdateWinnerCount sets the "winner_count" field to the value that was provided on create.
func (u *LotteryCampaignUpsert) UpdateWinnerCount() *LotteryCampaignUpsert {
	u.SetExcluded(lotterycampaign.FieldWinnerCount)
	return u
}

// AddWinnerCount adds v to the "winner_count" field.
func (u *LotteryCampaignUpsert) AddWinnerCount(v int) *LotteryCampaignUpsert {
	u.Add(lotterycampaign.FieldWinnerCount, v)
	return u
}

// SetEarlyBoostParticipantPercent sets the "early_boost_participant_percent" field.
func (u *LotteryCampaignUpsert) SetEarlyBoostParticipantPercent(v int) *LotteryCampaignUpsert {
	u.Set(lotterycampaign.FieldEarlyBoostParticipantPercent, v)
	return u
}

// UpdateEarlyBoostParticipantPercent sets the "early_boost_participant_percent" field to the value that was provided on create.
func (u *LotteryCampaignUpsert) UpdateEarlyBoostParticipantPercent() *LotteryCampaignUpsert {
	u.SetExcluded(lotterycampaign.FieldEarlyBoostParticipantPercent)
	return u
}

// AddEarlyBoostParticipantPercent adds v to the "early_boost_participant_percent" field.
func (u *LotteryCampaignUpsert) AddEarlyBoostParticipantPercent(v int) *LotteryCampaignUpsert {
	u.Add(lotterycampaign.FieldEarlyBoostParticipantPercent, v)
	return u
}

// SetRechargeBoostCapPercent sets the "recharge_boost_cap_percent" field.
func (u *LotteryCampaignUpsert) SetRechargeBoostCapPercent(v int) *LotteryCampaignUpsert {
	u.Set(lotterycampaign.FieldRechargeBoostCapPercent, v)
	return u
}

// UpdateRechargeBoostCapPercent sets the "recharge_boost_cap_percent" field to the value that was provided on create.
func (u *LotteryCampaignUpsert) UpdateRechargeBoostCapPercent() *LotteryCampaignUpsert {
	u.SetExcluded(lotterycampaign.FieldRechargeBoostCapPercent)
	return u
}

// AddRechargeBoostCapPercent adds v to the "recharge_boost_cap_percent" field.
func (u *LotteryCampaignUpsert) AddRechargeBoostCapPercent(v int) *LotteryCampaignUpsert {
	u.Add(lotterycampaign.FieldRechargeBoostCapPercent, v)
	return u
}

// SetPromoText sets the "promo_text" field.
func (u *LotteryCampaignUpsert) SetPromoText(v string) *LotteryCampaignUpsert {
	u.Set(lotterycampaign.FieldPromoText, v)
	return u
}

// UpdatePromoText sets the "promo_text" field to the value that was provided on create.
func (u *LotteryCampaignUpsert) UpdatePromoText() *LotteryCampaignUpsert {
	u.SetExcluded(lotterycampaign.FieldPromoText)
	return u
}

// SetPromoImageURL sets the "promo_image_url" field.
func (u *LotteryCampaignUpsert) SetPromoImageURL(v string) *LotteryCampaignUpsert {
	u.Set(lotterycampaign.FieldPromoImageURL, v)
	return u
}

// UpdatePromoImageURL sets the "promo_image_url" field to the value that was provided on create.
func (u *LotteryCampaignUpsert) UpdatePromoImageURL() *LotteryCampaignUpsert {
	u.SetExcluded(lotterycampaign.FieldPromoImageURL)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *LotteryCampaignUpsert) SetCreatedBy(v int64) *LotteryCampaignUpsert {
	u.Set(lotterycampaign.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *LotteryCampaignUpsert) UpdateCreatedBy() *LotteryCampaignUpsert {
	u.SetExcluded(lotterycampaign.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *LotteryCampaignUpsert) AddCreatedBy(v int64) *LotteryCampaignUpsert {
	u.Add(lotterycampaign.FieldCreatedBy, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LotteryCampaignUpsert) SetUpdatedAt(v time.Time) *LotteryCampaignUpsert {
	u.Set(lotterycampaign.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LotteryCampaignUpsert) UpdateUpdatedAt() *LotteryCampaignUpsert {
	u.SetExcluded(lotterycampaign.FieldUpdatedAt)
	return u
}

// SetFinishedAt sets the "finished_at" field.
func (u *LotteryCampaignUpsert) SetFinishedAt(v time.Time) *LotteryCampaignUpsert {
	u.Set(lotterycampaign.FieldFinishedAt, v)
	return u
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *LotteryCampaignUpsert) UpdateFinishedAt() *LotteryCampaignUpsert {
	u.SetExcluded(lotterycampaign.FieldFinishedAt)
	return u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *LotteryCampaignUpsert) ClearFinishedAt() *LotteryCampaignUpsert {
	u.SetNull(lotterycampaign.FieldFinishedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.LotteryCampaign.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LotteryCampaignUpsertOne) UpdateNewValues() *LotteryCampaignUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(lotterycampaign.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LotteryCampaign.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LotteryCampaignUpsertOne) Ignore() *LotteryCampaignUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LotteryCampaignUpsertOne) DoNothing() *LotteryCampaignUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LotteryCampaignCreate.OnConflict
// documentation for more info.
func (u *LotteryCampaignUpsertOne) Update(set func(*LotteryCampaignUpsert)) *LotteryCampaignUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LotteryCampaignUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *LotteryCampaignUpsertOne) SetName(v string) *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *LotteryCampaignUpsertOne) UpdateName() *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.UpdateName()
	})
}

// SetSubtitle sets the "subtitle" field.
func (u *LotteryCampaignUpsertOne) SetSubtitle(v string) *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.SetSubtitle(v)
	})
}

// UpdateSubtitle sets the "subtitle" field to the value that was provided on create.
func (u *LotteryCampaignUpsertOne) UpdateSubtitle() *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.UpdateSubtitle()
	})
}

// SetStatus sets the "status" field.
func (u *LotteryCampaignUpsertOne) SetStatus(v string) *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LotteryCampaignUpsertOne) UpdateStatus() *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.UpdateStatus()
	})
}

// SetPrizeCount sets the "prize_count" field.
func (u *LotteryCampaignUpsertOne) SetPrizeCount(v int) *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.SetPrizeCount(v)
	})
}

// AddPrizeCount adds v to the "prize_count" field.
func (u *LotteryCampaignUpsertOne) AddPrizeCount(v int) *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.AddPrizeCount(v)
	})
}

// UpdatePrizeCount sets the "prize_count" field to the value that was provided on create.
func (u *LotteryCampaignUpsertOne) UpdatePrizeCount() *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.UpdatePrizeCount()
	})
}

// SetMaxParticipants sets the "max_participants" field.
func (u *LotteryCampaignUpsertOne) SetMaxParticipants(v int) *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.SetMaxParticipants(v)
	})
}

// AddMaxParticipants adds v to the "max_participants" field.
func (u *LotteryCampaignUpsertOne) AddMaxParticipants(v int) *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.AddMaxParticipants(v)
	})
}

// UpdateMaxParticipants sets the "max_participants" field to the value that was provided on create.
func (u *LotteryCampaignUpsertOne) UpdateMaxParticipants() *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.UpdateMaxParticipants()
	})
}

// SetJoinedCount sets the "joined_count" field.
func (u *LotteryCampaignUpsertOne) SetJoinedCount(v int) *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.SetJoinedCount(v)
	})
}

// AddJoinedCount adds v to the "joined_count" field.
func (u *LotteryCampaignUpsertOne) AddJoinedCount(v int) *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.AddJoinedCount(v)
	})
}

// UpdateJoinedCount sets the "joined_count" field to the value that was provided on create.
func (u *LotteryCampaignUpsertOne) UpdateJoinedCount() *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.UpdateJoinedCount()
	})
}

// SetWinnerCount sets the "winner_count" field.
func (u *LotteryCampaignUpsertOne) SetWinnerCount(v int) *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.SetWinnerCount(v)
	})
}

// AddWinnerCount adds v to the "winner_count" field.
func (u *LotteryCampaignUpsertOne) AddWinnerCount(v int) *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.AddWinnerCount(v)
	})
}

// UpdateWinnerCount sets the "winner_count" field to the value that was provided on create.
func (u *LotteryCampaignUpsertOne) UpdateWinnerCount() *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.UpdateWinnerCount()
	})
}

// SetEarlyBoostParticipantPercent sets the "early_boost_participant_percent" field.
func (u *LotteryCampaignUpsertOne) SetEarlyBoostParticipantPercent(v int) *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.SetEarlyBoostParticipantPercent(v)
	})
}

// AddEarlyBoostParticipantPercent adds v to the "early_boost_participant_percent" field.
func (u *LotteryCampaignUpsertOne) AddEarlyBoostParticipantPercent(v int) *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.AddEarlyBoostParticipantPercent(v)
	})
}

// UpdateEarlyBoostParticipantPercent sets the "early_boost_participant_percent" field to the value that was provided on create.
func (u *LotteryCampaignUpsertOne) UpdateEarlyBoostParticipantPercent() *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.UpdateEarlyBoostParticipantPercent()
	})
}

// SetRechargeBoostCapPercent sets the "recharge_boost_cap_percent" field.
func (u *LotteryCampaignUpsertOne) SetRechargeBoostCapPercent(v int) *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.SetRechargeBoostCapPercent(v)
	})
}

// AddRechargeBoostCapPercent adds v to the "recharge_boost_cap_percent" field.
func (u *LotteryCampaignUpsertOne) AddRechargeBoostCapPercent(v int) *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.AddRechargeBoostCapPercent(v)
	})
}

// UpdateRechargeBoostCapPercent sets the "recharge_boost_cap_percent" field to the value that was provided on create.
func (u *LotteryCampaignUpsertOne) UpdateRechargeBoostCapPercent() *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.UpdateRechargeBoostCapPercent()
	})
}

// SetPromoText sets the "promo_text" field.
func (u *LotteryCampaignUpsertOne) SetPromoText(v string) *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.SetPromoText(v)
	})
}

// UpdatePromoText sets the "promo_text" field to the value that was provided on create.
func (u *LotteryCampaignUpsertOne) UpdatePromoText() *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.UpdatePromoText()
	})
}

// SetPromoImageURL sets the "promo_image_url" field.
func (u *LotteryCampaignUpsertOne) SetPromoImageURL(v string) *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.SetPromoImageURL(v)
	})
}

// UpdatePromoImageURL sets the "promo_image_url" field to the value that was provided on create.
func (u *LotteryCampaignUpsertOne) UpdatePromoImageURL() *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.UpdatePromoImageURL()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *LotteryCampaignUpsertOne) SetCreatedBy(v int64) *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *LotteryCampaignUpsertOne) AddCreatedBy(v int64) *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *LotteryCampaignUpsertOne) UpdateCreatedBy() *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.UpdateCreatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LotteryCampaignUpsertOne) SetUpdatedAt(v time.Time) *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LotteryCampaignUpsertOne) UpdateUpdatedAt() *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *LotteryCampaignUpsertOne) SetFinishedAt(v time.Time) *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.SetFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *LotteryCampaignUpsertOne) UpdateFinishedAt() *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.UpdateFinishedAt()
	})
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *LotteryCampaignUpsertOne) ClearFinishedAt() *LotteryCampaignUpsertOne {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.ClearFinishedAt()
	})
}

// Exec executes the query.
func (u *LotteryCampaignUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LotteryCampaignCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LotteryCampaignUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LotteryCampaignUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LotteryCampaignUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LotteryCampaignCreateBulk is the builder for creating many LotteryCampaign entities in bulk.
type LotteryCampaignCreateBulk struct {
	config
	err      error
	builders []*LotteryCampaignCreate
	conflict []sql.ConflictOption
}

// Save creates the LotteryCampaign entities in the database.
func (_c *LotteryCampaignCreateBulk) Save(ctx context.Context) ([]*LotteryCampaign, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LotteryCampaign, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LotteryCampaignMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LotteryCampaignCreateBulk) SaveX(ctx context.Context) []*LotteryCampaign {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LotteryCampaignCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LotteryCampaignCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LotteryCampaign.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LotteryCampaignUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *LotteryCampaignCreateBulk) OnConflict(opts ...sql.ConflictOption) *LotteryCampaignUpsertBulk {
	_c.conflict = opts
	return &LotteryCampaignUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LotteryCampaign.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LotteryCampaignCreateBulk) OnConflictColumns(columns ...string) *LotteryCampaignUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LotteryCampaignUpsertBulk{
		create: _c,
	}
}

// LotteryCampaignUpsertBulk is the builder for "upsert"-ing
// a bulk of LotteryCampaign nodes.
type LotteryCampaignUpsertBulk struct {
	create *LotteryCampaignCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.LotteryCampaign.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LotteryCampaignUpsertBulk) UpdateNewValues() *LotteryCampaignUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(lotterycampaign.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LotteryCampaign.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LotteryCampaignUpsertBulk) Ignore() *LotteryCampaignUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LotteryCampaignUpsertBulk) DoNothing() *LotteryCampaignUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LotteryCampaignCreateBulk.OnConflict
// documentation for more info.
func (u *LotteryCampaignUpsertBulk) Update(set func(*LotteryCampaignUpsert)) *LotteryCampaignUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LotteryCampaignUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *LotteryCampaignUpsertBulk) SetName(v string) *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *LotteryCampaignUpsertBulk) UpdateName() *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.UpdateName()
	})
}

// SetSubtitle sets the "subtitle" field.
func (u *LotteryCampaignUpsertBulk) SetSubtitle(v string) *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.SetSubtitle(v)
	})
}

// UpdateSubtitle sets the "subtitle" field to the value that was provided on create.
func (u *LotteryCampaignUpsertBulk) UpdateSubtitle() *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.UpdateSubtitle()
	})
}

// SetStatus sets the "status" field.
func (u *LotteryCampaignUpsertBulk) SetStatus(v string) *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LotteryCampaignUpsertBulk) UpdateStatus() *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.UpdateStatus()
	})
}

// SetPrizeCount sets the "prize_count" field.
func (u *LotteryCampaignUpsertBulk) SetPrizeCount(v int) *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.SetPrizeCount(v)
	})
}

// AddPrizeCount adds v to the "prize_count" field.
func (u *LotteryCampaignUpsertBulk) AddPrizeCount(v int) *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.AddPrizeCount(v)
	})
}

// UpdatePrizeCount sets the "prize_count" field to the value that was provided on create.
func (u *LotteryCampaignUpsertBulk) UpdatePrizeCount() *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.UpdatePrizeCount()
	})
}

// SetMaxParticipants sets the "max_participants" field.
func (u *LotteryCampaignUpsertBulk) SetMaxParticipants(v int) *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.SetMaxParticipants(v)
	})
}

// AddMaxParticipants adds v to the "max_participants" field.
func (u *LotteryCampaignUpsertBulk) AddMaxParticipants(v int) *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.AddMaxParticipants(v)
	})
}

// UpdateMaxParticipants sets the "max_participants" field to the value that was provided on create.
func (u *LotteryCampaignUpsertBulk) UpdateMaxParticipants() *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.UpdateMaxParticipants()
	})
}

// SetJoinedCount sets the "joined_count" field.
func (u *LotteryCampaignUpsertBulk) SetJoinedCount(v int) *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.SetJoinedCount(v)
	})
}

// AddJoinedCount adds v to the "joined_count" field.
func (u *LotteryCampaignUpsertBulk) AddJoinedCount(v int) *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.AddJoinedCount(v)
	})
}

// UpdateJoinedCount sets the "joined_count" field to the value that was provided on create.
func (u *LotteryCampaignUpsertBulk) UpdateJoinedCount() *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.UpdateJoinedCount()
	})
}

// SetWinnerCount sets the "winner_count" field.
func (u *LotteryCampaignUpsertBulk) SetWinnerCount(v int) *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.SetWinnerCount(v)
	})
}

// AddWinnerCount adds v to the "winner_count" field.
func (u *LotteryCampaignUpsertBulk) AddWinnerCount(v int) *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.AddWinnerCount(v)
	})
}

// UpdateWinnerCount sets the "winner_count" field to the value that was provided on create.
func (u *LotteryCampaignUpsertBulk) UpdateWinnerCount() *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.UpdateWinnerCount()
	})
}

// SetEarlyBoostParticipantPercent sets the "early_boost_participant_percent" field.
func (u *LotteryCampaignUpsertBulk) SetEarlyBoostParticipantPercent(v int) *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.SetEarlyBoostParticipantPercent(v)
	})
}

// AddEarlyBoostParticipantPercent adds v to the "early_boost_participant_percent" field.
func (u *LotteryCampaignUpsertBulk) AddEarlyBoostParticipantPercent(v int) *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.AddEarlyBoostParticipantPercent(v)
	})
}

// UpdateEarlyBoostParticipantPercent sets the "early_boost_participant_percent" field to the value that was provided on create.
func (u *LotteryCampaignUpsertBulk) UpdateEarlyBoostParticipantPercent() *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.UpdateEarlyBoostParticipantPercent()
	})
}

// SetRechargeBoostCapPercent sets the "recharge_boost_cap_percent" field.
func (u *LotteryCampaignUpsertBulk) SetRechargeBoostCapPercent(v int) *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.SetRechargeBoostCapPercent(v)
	})
}

// AddRechargeBoostCapPercent adds v to the "recharge_boost_cap_percent" field.
func (u *LotteryCampaignUpsertBulk) AddRechargeBoostCapPercent(v int) *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.AddRechargeBoostCapPercent(v)
	})
}

// UpdateRechargeBoostCapPercent sets the "recharge_boost_cap_percent" field to the value that was provided on create.
func (u *LotteryCampaignUpsertBulk) UpdateRechargeBoostCapPercent() *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.UpdateRechargeBoostCapPercent()
	})
}

// SetPromoText sets the "promo_text" field.
func (u *LotteryCampaignUpsertBulk) SetPromoText(v string) *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.SetPromoText(v)
	})
}

// UpdatePromoText sets the "promo_text" field to the value that was provided on create.
func (u *LotteryCampaignUpsertBulk) UpdatePromoText() *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.UpdatePromoText()
	})
}

// SetPromoImageURL sets the "promo_image_url" field.
func (u *LotteryCampaignUpsertBulk) SetPromoImageURL(v string) *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.SetPromoImageURL(v)
	})
}

// UpdatePromoImageURL sets the "promo_image_url" field to the value that was provided on create.
func (u *LotteryCampaignUpsertBulk) UpdatePromoImageURL() *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.UpdatePromoImageURL()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *LotteryCampaignUpsertBulk) SetCreatedBy(v int64) *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *LotteryCampaignUpsertBulk) AddCreatedBy(v int64) *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *LotteryCampaignUpsertBulk) UpdateCreatedBy() *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.UpdateCreatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LotteryCampaignUpsertBulk) SetUpdatedAt(v time.Time) *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LotteryCampaignUpsertBulk) UpdateUpdatedAt() *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *LotteryCampaignUpsertBulk) SetFinishedAt(v time.Time) *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.SetFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *LotteryCampaignUpsertBulk) UpdateFinishedAt() *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.UpdateFinishedAt()
	})
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *LotteryCampaignUpsertBulk) ClearFinishedAt() *LotteryCampaignUpsertBulk {
	return u.Update(func(s *LotteryCampaignUpsert) {
		s.ClearFinishedAt()
	})
}

// Exec executes the query.
func (u *LotteryCampaignUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LotteryCampaignCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LotteryCampaignCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LotteryCampaignUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
