// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/sitemessage"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// SiteMessageUpdate is the builder for updating SiteMessage entities.
type SiteMessageUpdate struct {
	config
	hooks    []Hook
	mutation *SiteMessageMutation
}

// Where appends a list predicates to the SiteMessageUpdate builder.
func (_u *SiteMessageUpdate) Where(ps ...predicate.SiteMessage) *SiteMessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSenderID sets the "sender_id" field.
func (_u *SiteMessageUpdate) SetSenderID(v int64) *SiteMessageUpdate {
	_u.mutation.SetSenderID(v)
	return _u
}

// SetNillableSenderID sets the "sender_id" field if the given value is not nil.
func (_u *SiteMessageUpdate) SetNillableSenderID(v *int64) *SiteMessageUpdate {
	if v != nil {
		_u.SetSenderID(*v)
	}
	return _u
}

// SetRecipientID sets the "recipient_id" field.
func (_u *SiteMessageUpdate) SetRecipientID(v int64) *SiteMessageUpdate {
	_u.mutation.SetRecipientID(v)
	return _u
}

// SetNillableRecipientID sets the "recipient_id" field if the given value is not nil.
func (_u *SiteMessageUpdate) SetNillableRecipientID(v *int64) *SiteMessageUpdate {
	if v != nil {
		_u.SetRecipientID(*v)
	}
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *SiteMessageUpdate) SetParentID(v int64) *SiteMessageUpdate {
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *SiteMessageUpdate) SetNillableParentID(v *int64) *SiteMessageUpdate {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *SiteMessageUpdate) ClearParentID() *SiteMessageUpdate {
	_u.mutation.ClearParentID()
	return _u
}

// SetSubject sets the "subject" field.
func (_u *SiteMessageUpdate) SetSubject(v string) *SiteMessageUpdate {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *SiteMessageUpdate) SetNillableSubject(v *string) *SiteMessageUpdate {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *SiteMessageUpdate) SetContent(v string) *SiteMessageUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *SiteMessageUpdate) SetNillableContent(v *string) *SiteMessageUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetReadAt sets the "read_at" field.
func (_u *SiteMessageUpdate) SetReadAt(v time.Time) *SiteMessageUpdate {
	_u.mutation.SetReadAt(v)
	return _u
}

// SetNillableReadAt sets the "read_at" field if the given value is not nil.
func (_u *SiteMessageUpdate) SetNillableReadAt(v *time.Time) *SiteMessageUpdate {
	if v != nil {
		_u.SetReadAt(*v)
	}
	return _u
}

// ClearReadAt clears the value of the "read_at" field.
func (_u *SiteMessageUpdate) ClearReadAt() *SiteMessageUpdate {
	_u.mutation.ClearReadAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SiteMessageUpdate) SetUpdatedAt(v time.Time) *SiteMessageUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSender sets the "sender" edge to the User entity.
func (_u *SiteMessageUpdate) SetSender(v *User) *SiteMessageUpdate {
	return _u.SetSenderID(v.ID)
}

// SetRecipient sets the "recipient" edge to the User entity.
func (_u *SiteMessageUpdate) SetRecipient(v *User) *SiteMessageUpdate {
	return _u.SetRecipientID(v.ID)
}

// AddReplyIDs adds the "replies" edge to the SiteMessage entity by IDs.
func (_u *SiteMessageUpdate) AddReplyIDs(ids ...int64) *SiteMessageUpdate {
	_u.mutation.AddReplyIDs(ids...)
	return _u
}

// AddReplies adds the "replies" edges to the SiteMessage entity.
func (_u *SiteMessageUpdate) AddReplies(v ...*SiteMessage) *SiteMessageUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReplyIDs(ids...)
}

// SetParent sets the "parent" edge to the SiteMessage entity.
func (_u *SiteMessageUpdate) SetParent(v *SiteMessage) *SiteMessageUpdate {
	return _u.SetParentID(v.ID)
}

// Mutation returns the SiteMessageMutation object of the builder.
func (_u *SiteMessageUpdate) Mutation() *SiteMessageMutation {
	return _u.mutation
}

// ClearSender clears the "sender" edge to the User entity.
func (_u *SiteMessageUpdate) ClearSender() *SiteMessageUpdate {
	_u.mutation.ClearSender()
	return _u
}

// ClearRecipient clears the "recipient" edge to the User entity.
func (_u *SiteMessageUpdate) ClearRecipient() *SiteMessageUpdate {
	_u.mutation.ClearRecipient()
	return _u
}

// ClearReplies clears all "replies" edges to the SiteMessage entity.
func (_u *SiteMessageUpdate) ClearReplies() *SiteMessageUpdate {
	_u.mutation.ClearReplies()
	return _u
}

// RemoveReplyIDs removes the "replies" edge to SiteMessage entities by IDs.
func (_u *SiteMessageUpdate) RemoveReplyIDs(ids ...int64) *SiteMessageUpdate {
	_u.mutation.RemoveReplyIDs(ids...)
	return _u
}

// RemoveReplies removes "replies" edges to SiteMessage entities.
func (_u *SiteMessageUpdate) RemoveReplies(v ...*SiteMessage) *SiteMessageUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReplyIDs(ids...)
}

// ClearParent clears the "parent" edge to the SiteMessage entity.
func (_u *SiteMessageUpdate) ClearParent() *SiteMessageUpdate {
	_u.mutation.ClearParent()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SiteMessageUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SiteMessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SiteMessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SiteMessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SiteMessageUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := sitemessage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SiteMessageUpdate) check() error {
	if v, ok := _u.mutation.Subject(); ok {
		if err := sitemessage.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "SiteMessage.subject": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := sitemessage.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "SiteMessage.content": %w`, err)}
		}
	}
	if _u.mutation.SenderCleared() && len(_u.mutation.SenderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SiteMessage.sender"`)
	}
	if _u.mutation.RecipientCleared() && len(_u.mutation.RecipientIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SiteMessage.recipient"`)
	}
	return nil
}

func (_u *SiteMessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sitemessage.Table, sitemessage.Columns, sqlgraph.NewFieldSpec(sitemessage.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(sitemessage.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(sitemessage.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReadAt(); ok {
		_spec.SetField(sitemessage.FieldReadAt, field.TypeTime, value)
	}
	if _u.mutation.ReadAtCleared() {
		_spec.ClearField(sitemessage.FieldReadAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sitemessage.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.SenderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sitemessage.SenderTable,
			Columns: []string{sitemessage.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sitemessage.SenderTable,
			Columns: []string{sitemessage.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RecipientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sitemessage.RecipientTable,
			Columns: []string{sitemessage.RecipientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecipientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sitemessage.RecipientTable,
			Columns: []string{sitemessage.RecipientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RepliesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sitemessage.RepliesTable,
			Columns: []string{sitemessage.RepliesColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sitemessage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRepliesIDs(); len(nodes) > 0 && !_u.mutation.RepliesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sitemessage.RepliesTable,
			Columns: []string{sitemessage.RepliesColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sitemessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RepliesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sitemessage.RepliesTable,
			Columns: []string{sitemessage.RepliesColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sitemessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sitemessage.ParentTable,
			Columns: []string{sitemessage.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sitemessage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sitemessage.ParentTable,
			Columns: []string{sitemessage.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sitemessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sitemessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SiteMessageUpdateOne is the builder for updating a single SiteMessage entity.
type SiteMessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SiteMessageMutation
}

// SetSenderID sets the "sender_id" field.
func (_u *SiteMessageUpdateOne) SetSenderID(v int64) *SiteMessageUpdateOne {
	_u.mutation.SetSenderID(v)
	return _u
}

// SetNillableSenderID sets the "sender_id" field if the given value is not nil.
func (_u *SiteMessageUpdateOne) SetNillableSenderID(v *int64) *SiteMessageUpdateOne {
	if v != nil {
		_u.SetSenderID(*v)
	}
	return _u
}

// SetRecipientID sets the "recipient_id" field.
func (_u *SiteMessageUpdateOne) SetRecipientID(v int64) *SiteMessageUpdateOne {
	_u.mutation.SetRecipientID(v)
	return _u
}

// SetNillableRecipientID sets the "recipient_id" field if the given value is not nil.
func (_u *SiteMessageUpdateOne) SetNillableRecipientID(v *int64) *SiteMessageUpdateOne {
	if v != nil {
		_u.SetRecipientID(*v)
	}
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *SiteMessageUpdateOne) SetParentID(v int64) *SiteMessageUpdateOne {
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *SiteMessageUpdateOne) SetNillableParentID(v *int64) *SiteMessageUpdateOne {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *SiteMessageUpdateOne) ClearParentID() *SiteMessageUpdateOne {
	_u.mutation.ClearParentID()
	return _u
}

// SetSubject sets the "subject" field.
func (_u *SiteMessageUpdateOne) SetSubject(v string) *SiteMessageUpdateOne {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *SiteMessageUpdateOne) SetNillableSubject(v *string) *SiteMessageUpdateOne {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *SiteMessageUpdateOne) SetContent(v string) *SiteMessageUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *SiteMessageUpdateOne) SetNillableContent(v *string) *SiteMessageUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetReadAt sets the "read_at" field.
func (_u *SiteMessageUpdateOne) SetReadAt(v time.Time) *SiteMessageUpdateOne {
	_u.mutation.SetReadAt(v)
	return _u
}

// SetNillableReadAt sets the "read_at" field if the given value is not nil.
func (_u *SiteMessageUpdateOne) SetNillableReadAt(v *time.Time) *SiteMessageUpdateOne {
	if v != nil {
		_u.SetReadAt(*v)
	}
	return _u
}

// ClearReadAt clears the value of the "read_at" field.
func (_u *SiteMessageUpdateOne) ClearReadAt() *SiteMessageUpdateOne {
	_u.mutation.ClearReadAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SiteMessageUpdateOne) SetUpdatedAt(v time.Time) *SiteMessageUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSender sets the "sender" edge to the User entity.
func (_u *SiteMessageUpdateOne) SetSender(v *User) *SiteMessageUpdateOne {
	return _u.SetSenderID(v.ID)
}

// SetRecipient sets the "recipient" edge to the User entity.
func (_u *SiteMessageUpdateOne) SetRecipient(v *User) *SiteMessageUpdateOne {
	return _u.SetRecipientID(v.ID)
}

// AddReplyIDs adds the "replies" edge to the SiteMessage entity by IDs.
func (_u *SiteMessageUpdateOne) AddReplyIDs(ids ...int64) *SiteMessageUpdateOne {
	_u.mutation.AddReplyIDs(ids...)
	return _u
}

// AddReplies adds the "replies" edges to the SiteMessage entity.
func (_u *SiteMessageUpdateOne) AddReplies(v ...*SiteMessage) *SiteMessageUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReplyIDs(ids...)
}

// SetParent sets the "parent" edge to the SiteMessage entity.
func (_u *SiteMessageUpdateOne) SetParent(v *SiteMessage) *SiteMessageUpdateOne {
	return _u.SetParentID(v.ID)
}

// Mutation returns the SiteMessageMutation object of the builder.
func (_u *SiteMessageUpdateOne) Mutation() *SiteMessageMutation {
	return _u.mutation
}

// ClearSender clears the "sender" edge to the User entity.
func (_u *SiteMessageUpdateOne) ClearSender() *SiteMessageUpdateOne {
	_u.mutation.ClearSender()
	return _u
}

// ClearRecipient clears the "recipient" edge to the User entity.
func (_u *SiteMessageUpdateOne) ClearRecipient() *SiteMessageUpdateOne {
	_u.mutation.ClearRecipient()
	return _u
}

// ClearReplies clears all "replies" edges to the SiteMessage entity.
func (_u *SiteMessageUpdateOne) ClearReplies() *SiteMessageUpdateOne {
	_u.mutation.ClearReplies()
	return _u
}

// RemoveReplyIDs removes the "replies" edge to SiteMessage entities by IDs.
func (_u *SiteMessageUpdateOne) RemoveReplyIDs(ids ...int64) *SiteMessageUpdateOne {
	_u.mutation.RemoveReplyIDs(ids...)
	return _u
}

// RemoveReplies removes "replies" edges to SiteMessage entities.
func (_u *SiteMessageUpdateOne) RemoveReplies(v ...*SiteMessage) *SiteMessageUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReplyIDs(ids...)
}

// ClearParent clears the "parent" edge to the SiteMessage entity.
func (_u *SiteMessageUpdateOne) ClearParent() *SiteMessageUpdateOne {
	_u.mutation.ClearParent()
	return _u
}

// Where appends a list predicates to the SiteMessageUpdate builder.
func (_u *SiteMessageUpdateOne) Where(ps ...predicate.SiteMessage) *SiteMessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SiteMessageUpdateOne) Select(field string, fields ...string) *SiteMessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SiteMessage entity.
func (_u *SiteMessageUpdateOne) Save(ctx context.Context) (*SiteMessage, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SiteMessageUpdateOne) SaveX(ctx context.Context) *SiteMessage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SiteMessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SiteMessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SiteMessageUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := sitemessage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SiteMessageUpdateOne) check() error {
	if v, ok := _u.mutation.Subject(); ok {
		if err := sitemessage.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "SiteMessage.subject": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := sitemessage.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "SiteMessage.content": %w`, err)}
		}
	}
	if _u.mutation.SenderCleared() && len(_u.mutation.SenderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SiteMessage.sender"`)
	}
	if _u.mutation.RecipientCleared() && len(_u.mutation.RecipientIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SiteMessage.recipient"`)
	}
	return nil
}

func (_u *SiteMessageUpdateOne) sqlSave(ctx context.Context) (_node *SiteMessage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sitemessage.Table, sitemessage.Columns, sqlgraph.NewFieldSpec(sitemessage.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SiteMessage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sitemessage.FieldID)
		for _, f := range fields {
			if !sitemessage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sitemessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(sitemessage.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(sitemessage.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReadAt(); ok {
		_spec.SetField(sitemessage.FieldReadAt, field.TypeTime, value)
	}
	if _u.mutation.ReadAtCleared() {
		_spec.ClearField(sitemessage.FieldReadAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sitemessage.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.SenderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sitemessage.SenderTable,
			Columns: []string{sitemessage.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sitemessage.SenderTable,
			Columns: []string{sitemessage.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RecipientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sitemessage.RecipientTable,
			Columns: []string{sitemessage.RecipientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RecipientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sitemessage.RecipientTable,
			Columns: []string{sitemessage.RecipientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RepliesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sitemessage.RepliesTable,
			Columns: []string{sitemessage.RepliesColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sitemessage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRepliesIDs(); len(nodes) > 0 && !_u.mutation.RepliesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sitemessage.RepliesTable,
			Columns: []string{sitemessage.RepliesColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sitemessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RepliesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sitemessage.RepliesTable,
			Columns: []string{sitemessage.RepliesColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sitemessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sitemessage.ParentTable,
			Columns: []string{sitemessage.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sitemessage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sitemessage.ParentTable,
			Columns: []string{sitemessage.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sitemessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SiteMessage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sitemessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
