// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/sitemessage"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// SiteMessageCreate is the builder for creating a SiteMessage entity.
type SiteMessageCreate struct {
	config
	mutation *SiteMessageMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetSenderID sets the "sender_id" field.
func (_c *SiteMessageCreate) SetSenderID(v int64) *SiteMessageCreate {
	_c.mutation.SetSenderID(v)
	return _c
}

// SetRecipientID sets the "recipient_id" field.
func (_c *SiteMessageCreate) SetRecipientID(v int64) *SiteMessageCreate {
	_c.mutation.SetRecipientID(v)
	return _c
}

// SetParentID sets the "parent_id" field.
func (_c *SiteMessageCreate) SetParentID(v int64) *SiteMessageCreate {
	_c.mutation.SetParentID(v)
	return _c
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_c *SiteMessageCreate) SetNillableParentID(v *int64) *SiteMessageCreate {
	if v != nil {
		_c.SetParentID(*v)
	}
	return _c
}

// SetSubject sets the "subject" field.
func (_c *SiteMessageCreate) SetSubject(v string) *SiteMessageCreate {
	_c.mutation.SetSubject(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *SiteMessageCreate) SetContent(v string) *SiteMessageCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetReadAt sets the "read_at" field.
func (_c *SiteMessageCreate) SetReadAt(v time.Time) *SiteMessageCreate {
	_c.mutation.SetReadAt(v)
	return _c
}

// SetNillableReadAt sets the "read_at" field if the given value is not nil.
func (_c *SiteMessageCreate) SetNillableReadAt(v *time.Time) *SiteMessageCreate {
	if v != nil {
		_c.SetReadAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SiteMessageCreate) SetCreatedAt(v time.Time) *SiteMessageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SiteMessageCreate) SetNillableCreatedAt(v *time.Time) *SiteMessageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SiteMessageCreate) SetUpdatedAt(v time.Time) *SiteMessageCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SiteMessageCreate) SetNillableUpdatedAt(v *time.Time) *SiteMessageCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetSender sets the "sender" edge to the User entity.
func (_c *SiteMessageCreate) SetSender(v *User) *SiteMessageCreate {
	return _c.SetSenderID(v.ID)
}

// SetRecipient sets the "recipient" edge to the User entity.
func (_c *SiteMessageCreate) SetRecipient(v *User) *SiteMessageCreate {
	return _c.SetRecipientID(v.ID)
}

// AddReplyIDs adds the "replies" edge to the SiteMessage entity by IDs.
func (_c *SiteMessageCreate) AddReplyIDs(ids ...int64) *SiteMessageCreate {
	_c.mutation.AddReplyIDs(ids...)
	return _c
}

// AddReplies adds the "replies" edges to the SiteMessage entity.
func (_c *SiteMessageCreate) AddReplies(v ...*SiteMessage) *SiteMessageCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddReplyIDs(ids...)
}

// SetParent sets the "parent" edge to the SiteMessage entity.
func (_c *SiteMessageCreate) SetParent(v *SiteMessage) *SiteMessageCreate {
	return _c.SetParentID(v.ID)
}

// Mutation returns the SiteMessageMutation object of the builder.
func (_c *SiteMessageCreate) Mutation() *SiteMessageMutation {
	return _c.mutation
}

// Save creates the SiteMessage in the database.
func (_c *SiteMessageCreate) Save(ctx context.Context) (*SiteMessage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SiteMessageCreate) SaveX(ctx context.Context) *SiteMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SiteMessageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SiteMessageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SiteMessageCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := sitemessage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := sitemessage.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SiteMessageCreate) check() error {
	if _, ok := _c.mutation.SenderID(); !ok {
		return &ValidationError{Name: "sender_id", err: errors.New(`ent: missing required field "SiteMessage.sender_id"`)}
	}
	if _, ok := _c.mutation.RecipientID(); !ok {
		return &ValidationError{Name: "recipient_id", err: errors.New(`ent: missing required field "SiteMessage.recipient_id"`)}
	}
	if _, ok := _c.mutation.Subject(); !ok {
		return &ValidationError{Name: "subject", err: errors.New(`ent: missing required field "SiteMessage.subject"`)}
	}
	if v, ok := _c.mutation.Subject(); ok {
		if err := sitemessage.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "SiteMessage.subject": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "SiteMessage.content"`)}
	}
	if v, ok := _c.mutation.Content(); ok {
		if err := sitemessage.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "SiteMessage.content": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SiteMessage.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SiteMessage.updated_at"`)}
	}
	if len(_c.mutation.SenderIDs()) == 0 {
		return &ValidationError{Name: "sender", err: errors.New(`ent: missing required edge "SiteMessage.sender"`)}
	}
	if len(_c.mutation.RecipientIDs()) == 0 {
		return &ValidationError{Name: "recipient", err: errors.New(`ent: missing required edge "SiteMessage.recipient"`)}
	}
	return nil
}

func (_c *SiteMessageCreate) sqlSave(ctx context.Context) (*SiteMessage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SiteMessageCreate) createSpec() (*SiteMessage, *sqlgraph.CreateSpec) {
	var (
		_node = &SiteMessage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sitemessage.Table, sqlgraph.NewFieldSpec(sitemessage.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Subject(); ok {
		_spec.SetField(sitemessage.FieldSubject, field.TypeString, value)
		_node.Subject = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(sitemessage.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.ReadAt(); ok {
		_spec.SetField(sitemessage.FieldReadAt, field.TypeTime, value)
		_node.ReadAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(sitemessage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(sitemessage.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.SenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sitemessage.SenderTable,
			Columns: []string{sitemessage.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SenderID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RecipientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sitemessage.RecipientTable,
			Columns: []string{sitemessage.RecipientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RecipientID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RepliesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sitemessage.RepliesTable,
			Columns: []string{sitemessage.RepliesColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sitemessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sitemessage.ParentTable,
			Columns: []string{sitemessage.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sitemessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ParentID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SiteMessage.Create().
//		SetSenderID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SiteMessageUpsert) {
//			SetSenderID(v+v).
//		}).
//		Exec(ctx)
func (_c *SiteMessageCreate) OnConflict(opts ...sql.ConflictOption) *SiteMessageUpsertOne {
	_c.conflict = opts
	return &SiteMessageUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SiteMessage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SiteMessageCreate) OnConflictColumns(columns ...string) *SiteMessageUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SiteMessageUpsertOne{
		create: _c,
	}
}

type (
	// SiteMessageUpsertOne is the builder for "upsert"-ing
	//  one SiteMessage node.
	SiteMessageUpsertOne struct {
		create *SiteMessageCreate
	}

	// SiteMessageUpsert is the "OnConflict" setter.
	SiteMessageUpsert struct {
		*sql.UpdateSet
	}
)

// SetSenderID sets the "sender_id" field.
func (u *SiteMessageUpsert) SetSenderID(v int64) *SiteMessageUpsert {
	u.Set(sitemessage.FieldSenderID, v)
	return u
}

// UpdateSenderID sets the "sender_id" field to the value that was provided on create.
func (u *SiteMessageUpsert) UpdateSenderID() *SiteMessageUpsert {
	u.SetExcluded(sitemessage.FieldSenderID)
	return u
}

// SetRecipientID sets the "recipient_id" field.
func (u *SiteMessageUpsert) SetRecipientID(v int64) *SiteMessageUpsert {
	u.Set(sitemessage.FieldRecipientID, v)
	return u
}

// UpdateRecipientID sets the "recipient_id" field to the value that was provided on create.
func (u *SiteMessageUpsert) UpdateRecipientID() *SiteMessageUpsert {
	u.SetExcluded(sitemessage.FieldRecipientID)
	return u
}

// SetParentID sets the "parent_id" field.
func (u *SiteMessageUpsert) SetParentID(v int64) *SiteMessageUpsert {
	u.Set(sitemessage.FieldParentID, v)
	return u
}

// UpdateParentID sets the "parent_id" field to the value that was provided on create.
func (u *SiteMessageUpsert) UpdateParentID() *SiteMessageUpsert {
	u.SetExcluded(sitemessage.FieldParentID)
	return u
}

// ClearParentID clears the value of the "parent_id" field.
func (u *SiteMessageUpsert) ClearParentID() *SiteMessageUpsert {
	u.SetNull(sitemessage.FieldParentID)
	return u
}

// SetSubject sets the "subject" field.
func (u *SiteMessageUpsert) SetSubject(v string) *SiteMessageUpsert {
	u.Set(sitemessage.FieldSubject, v)
	return u
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *SiteMessageUpsert) UpdateSubject() *SiteMessageUpsert {
	u.SetExcluded(sitemessage.FieldSubject)
	return u
}

// SetContent sets the "content" field.
func (u *SiteMessageUpsert) SetContent(v string) *SiteMessageUpsert {
	u.Set(sitemessage.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *SiteMessageUpsert) UpdateContent() *SiteMessageUpsert {
	u.SetExcluded(sitemessage.FieldContent)
	return u
}

// SetReadAt sets the "read_at" field.
func (u *SiteMessageUpsert) SetReadAt(v time.Time) *SiteMessageUpsert {
	u.Set(sitemessage.FieldReadAt, v)
	return u
}

// UpdateReadAt sets the "read_at" field to the value that was provided on create.
func (u *SiteMessageUpsert) UpdateReadAt() *SiteMessageUpsert {
	u.SetExcluded(sitemessage.FieldReadAt)
	return u
}

// ClearReadAt clears the value of the "read_at" field.
func (u *SiteMessageUpsert) ClearReadAt() *SiteMessageUpsert {
	u.SetNull(sitemessage.FieldReadAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SiteMessageUpsert) SetUpdatedAt(v time.Time) *SiteMessageUpsert {
	u.Set(sitemessage.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SiteMessageUpsert) UpdateUpdatedAt() *SiteMessageUpsert {
	u.SetExcluded(sitemessage.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SiteMessage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SiteMessageUpsertOne) UpdateNewValues() *SiteMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(sitemessage.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SiteMessage.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SiteMessageUpsertOne) Ignore() *SiteMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SiteMessageUpsertOne) DoNothing() *SiteMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SiteMessageCreate.OnConflict
// documentation for more info.
func (u *SiteMessageUpsertOne) Update(set func(*SiteMessageUpsert)) *SiteMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SiteMessageUpsert{UpdateSet: update})
	}))
	return u
}

// SetSenderID sets the "sender_id" field.
func (u *SiteMessageUpsertOne) SetSenderID(v int64) *SiteMessageUpsertOne {
	return u.Update(func(s *SiteMessageUpsert) {
		s.SetSenderID(v)
	})
}

// UpdateSenderID sets the "sender_id" field to the value that was provided on create.
func (u *SiteMessageUpsertOne) UpdateSenderID() *SiteMessageUpsertOne {
	return u.Update(func(s *SiteMessageUpsert) {
		s.UpdateSenderID()
	})
}

// SetRecipientID sets the "recipient_id" field.
func (u *SiteMessageUpsertOne) SetRecipientID(v int64) *SiteMessageUpsertOne {
	return u.Update(func(s *SiteMessageUpsert) {
		s.SetRecipientID(v)
	})
}

// UpdateRecipientID sets the "recipient_id" field to the value that was provided on create.
func (u *SiteMessageUpsertOne) UpdateRecipientID() *SiteMessageUpsertOne {
	return u.Update(func(s *SiteMessageUpsert) {
		s.UpdateRecipientID()
	})
}

// SetParentID sets the "parent_id" field.
func (u *SiteMessageUpsertOne) SetParentID(v int64) *SiteMessageUpsertOne {
	return u.Update(func(s *SiteMessageUpsert) {
		s.SetParentID(v)
	})
}

// UpdateParentID sets the "parent_id" field to the value that was provided on create.
func (u *SiteMessageUpsertOne) UpdateParentID() *SiteMessageUpsertOne {
	return u.Update(func(s *SiteMessageUpsert) {
		s.UpdateParentID()
	})
}

// ClearParentID clears the value of the "parent_id" field.
func (u *SiteMessageUpsertOne) ClearParentID() *SiteMessageUpsertOne {
	return u.Update(func(s *SiteMessageUpsert) {
		s.ClearParentID()
	})
}

// SetSubject sets the "subject" field.
func (u *SiteMessageUpsertOne) SetSubject(v string) *SiteMessageUpsertOne {
	return u.Update(func(s *SiteMessageUpsert) {
		s.SetSubject(v)
	})
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *SiteMessageUpsertOne) UpdateSubject() *SiteMessageUpsertOne {
	return u.Update(func(s *SiteMessageUpsert) {
		s.UpdateSubject()
	})
}

// SetContent sets the "content" field.
func (u *SiteMessageUpsertOne) SetContent(v string) *SiteMessageUpsertOne {
	return u.Update(func(s *SiteMessageUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *SiteMessageUpsertOne) UpdateContent() *SiteMessageUpsertOne {
	return u.Update(func(s *SiteMessageUpsert) {
		s.UpdateContent()
	})
}

// SetReadAt sets the "read_at" field.
func (u *SiteMessageUpsertOne) SetReadAt(v time.Time) *SiteMessageUpsertOne {
	return u.Update(func(s *SiteMessageUpsert) {
		s.SetReadAt(v)
	})
}

// UpdateReadAt sets the "read_at" field to the value that was provided on create.
func (u *SiteMessageUpsertOne) UpdateReadAt() *SiteMessageUpsertOne {
	return u.Update(func(s *SiteMessageUpsert) {
		s.UpdateReadAt()
	})
}

// ClearReadAt clears the value of the "read_at" field.
func (u *SiteMessageUpsertOne) ClearReadAt() *SiteMessageUpsertOne {
	return u.Update(func(s *SiteMessageUpsert) {
		s.ClearReadAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SiteMessageUpsertOne) SetUpdatedAt(v time.Time) *SiteMessageUpsertOne {
	return u.Update(func(s *SiteMessageUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SiteMessageUpsertOne) UpdateUpdatedAt() *SiteMessageUpsertOne {
	return u.Update(func(s *SiteMessageUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *SiteMessageUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SiteMessageCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SiteMessageUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SiteMessageUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SiteMessageUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SiteMessageCreateBulk is the builder for creating many SiteMessage entities in bulk.
type SiteMessageCreateBulk struct {
	config
	err      error
	builders []*SiteMessageCreate
	conflict []sql.ConflictOption
}

// Save creates the SiteMessage entities in the database.
func (_c *SiteMessageCreateBulk) Save(ctx context.Context) ([]*SiteMessage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SiteMessage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SiteMessageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SiteMessageCreateBulk) SaveX(ctx context.Context) []*SiteMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SiteMessageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SiteMessageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SiteMessage.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SiteMessageUpsert) {
//			SetSenderID(v+v).
//		}).
//		Exec(ctx)
func (_c *SiteMessageCreateBulk) OnConflict(opts ...sql.ConflictOption) *SiteMessageUpsertBulk {
	_c.conflict = opts
	return &SiteMessageUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SiteMessage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SiteMessageCreateBulk) OnConflictColumns(columns ...string) *SiteMessageUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SiteMessageUpsertBulk{
		create: _c,
	}
}

// SiteMessageUpsertBulk is the builder for "upsert"-ing
// a bulk of SiteMessage nodes.
type SiteMessageUpsertBulk struct {
	create *SiteMessageCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SiteMessage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SiteMessageUpsertBulk) UpdateNewValues() *SiteMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(sitemessage.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SiteMessage.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SiteMessageUpsertBulk) Ignore() *SiteMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SiteMessageUpsertBulk) DoNothing() *SiteMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SiteMessageCreateBulk.OnConflict
// documentation for more info.
func (u *SiteMessageUpsertBulk) Update(set func(*SiteMessageUpsert)) *SiteMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SiteMessageUpsert{UpdateSet: update})
	}))
	return u
}

// SetSenderID sets the "sender_id" field.
func (u *SiteMessageUpsertBulk) SetSenderID(v int64) *SiteMessageUpsertBulk {
	return u.Update(func(s *SiteMessageUpsert) {
		s.SetSenderID(v)
	})
}

// UpdateSenderID sets the "sender_id" field to the value that was provided on create.
func (u *SiteMessageUpsertBulk) UpdateSenderID() *SiteMessageUpsertBulk {
	return u.Update(func(s *SiteMessageUpsert) {
		s.UpdateSenderID()
	})
}

// SetRecipientID sets the "recipient_id" field.
func (u *SiteMessageUpsertBulk) SetRecipientID(v int64) *SiteMessageUpsertBulk {
	return u.Update(func(s *SiteMessageUpsert) {
		s.SetRecipientID(v)
	})
}

// UpdateRecipientID sets the "recipient_id" field to the value that was provided on create.
func (u *SiteMessageUpsertBulk) UpdateRecipientID() *SiteMessageUpsertBulk {
	return u.Update(func(s *SiteMessageUpsert) {
		s.UpdateRecipientID()
	})
}

// SetParentID sets the "parent_id" field.
func (u *SiteMessageUpsertBulk) SetParentID(v int64) *SiteMessageUpsertBulk {
	return u.Update(func(s *SiteMessageUpsert) {
		s.SetParentID(v)
	})
}

// UpdateParentID sets the "parent_id" field to the value that was provided on create.
func (u *SiteMessageUpsertBulk) UpdateParentID() *SiteMessageUpsertBulk {
	return u.Update(func(s *SiteMessageUpsert) {
		s.UpdateParentID()
	})
}

// ClearParentID clears the value of the "parent_id" field.
func (u *SiteMessageUpsertBulk) ClearParentID() *SiteMessageUpsertBulk {
	return u.Update(func(s *SiteMessageUpsert) {
		s.ClearParentID()
	})
}

// SetSubject sets the "subject" field.
func (u *SiteMessageUpsertBulk) SetSubject(v string) *SiteMessageUpsertBulk {
	return u.Update(func(s *SiteMessageUpsert) {
		s.SetSubject(v)
	})
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *SiteMessageUpsertBulk) UpdateSubject() *SiteMessageUpsertBulk {
	return u.Update(func(s *SiteMessageUpsert) {
		s.UpdateSubject()
	})
}

// SetContent sets the "content" field.
func (u *SiteMessageUpsertBulk) SetContent(v string) *SiteMessageUpsertBulk {
	return u.Update(func(s *SiteMessageUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *SiteMessageUpsertBulk) UpdateContent() *SiteMessageUpsertBulk {
	return u.Update(func(s *SiteMessageUpsert) {
		s.UpdateContent()
	})
}

// SetReadAt sets the "read_at" field.
func (u *SiteMessageUpsertBulk) SetReadAt(v time.Time) *SiteMessageUpsertBulk {
	return u.Update(func(s *SiteMessageUpsert) {
		s.SetReadAt(v)
	})
}

// UpdateReadAt sets the "read_at" field to the value that was provided on create.
func (u *SiteMessageUpsertBulk) UpdateReadAt() *SiteMessageUpsertBulk {
	return u.Update(func(s *SiteMessageUpsert) {
		s.UpdateReadAt()
	})
}

// ClearReadAt clears the value of the "read_at" field.
func (u *SiteMessageUpsertBulk) ClearReadAt() *SiteMessageUpsertBulk {
	return u.Update(func(s *SiteMessageUpsert) {
		s.ClearReadAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SiteMessageUpsertBulk) SetUpdatedAt(v time.Time) *SiteMessageUpsertBulk {
	return u.Update(func(s *SiteMessageUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SiteMessageUpsertBulk) UpdateUpdatedAt() *SiteMessageUpsertBulk {
	return u.Update(func(s *SiteMessageUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *SiteMessageUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SiteMessageCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SiteMessageCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SiteMessageUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
