// Code generated by ent, DO NOT EDIT.

package lotterycode

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldLTE(FieldID, id))
}

// CampaignID applies equality check predicate on the "campaign_id" field. It's identical to CampaignIDEQ.
func CampaignID(v int64) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldEQ(FieldCampaignID, v))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldEQ(FieldCode, v))
}

// AssignedUserID applies equality check predicate on the "assigned_user_id" field. It's identical to AssignedUserIDEQ.
func AssignedUserID(v int64) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldEQ(FieldAssignedUserID, v))
}

// AssignedDrawID applies equality check predicate on the "assigned_draw_id" field. It's identical to AssignedDrawIDEQ.
func AssignedDrawID(v int64) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldEQ(FieldAssignedDrawID, v))
}

// AssignedAt applies equality check predicate on the "assigned_at" field. It's identical to AssignedAtEQ.
func AssignedAt(v time.Time) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldEQ(FieldAssignedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldEQ(FieldUpdatedAt, v))
}

// CampaignIDEQ applies the EQ predicate on the "campaign_id" field.
func CampaignIDEQ(v int64) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldEQ(FieldCampaignID, v))
}

// CampaignIDNEQ applies the NEQ predicate on the "campaign_id" field.
func CampaignIDNEQ(v int64) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldNEQ(FieldCampaignID, v))
}

// CampaignIDIn applies the In predicate on the "campaign_id" field.
func CampaignIDIn(vs ...int64) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldIn(FieldCampaignID, vs...))
}

// CampaignIDNotIn applies the NotIn predicate on the "campaign_id" field.
func CampaignIDNotIn(vs ...int64) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldNotIn(FieldCampaignID, vs...))
}

// CampaignIDGT applies the GT predicate on the "campaign_id" field.
func CampaignIDGT(v int64) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldGT(FieldCampaignID, v))
}

// CampaignIDGTE applies the GTE predicate on the "campaign_id" field.
func CampaignIDGTE(v int64) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldGTE(FieldCampaignID, v))
}

// CampaignIDLT applies the LT predicate on the "campaign_id" field.
func CampaignIDLT(v int64) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldLT(FieldCampaignID, v))
}

// CampaignIDLTE applies the LTE predicate on the "campaign_id" field.
func CampaignIDLTE(v int64) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldLTE(FieldCampaignID, v))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldHasSuffix(FieldCode, v))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldContainsFold(FieldCode, v))
}

// AssignedUserIDEQ applies the EQ predicate on the "assigned_user_id" field.
func AssignedUserIDEQ(v int64) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldEQ(FieldAssignedUserID, v))
}

// AssignedUserIDNEQ applies the NEQ predicate on the "assigned_user_id" field.
func AssignedUserIDNEQ(v int64) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldNEQ(FieldAssignedUserID, v))
}

// AssignedUserIDIn applies the In predicate on the "assigned_user_id" field.
func AssignedUserIDIn(vs ...int64) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldIn(FieldAssignedUserID, vs...))
}

// AssignedUserIDNotIn applies the NotIn predicate on the "assigned_user_id" field.
func AssignedUserIDNotIn(vs ...int64) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldNotIn(FieldAssignedUserID, vs...))
}

// AssignedUserIDGT applies the GT predicate on the "assigned_user_id" field.
func AssignedUserIDGT(v int64) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldGT(FieldAssignedUserID, v))
}

// AssignedUserIDGTE applies the GTE predicate on the "assigned_user_id" field.
func AssignedUserIDGTE(v int64) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldGTE(FieldAssignedUserID, v))
}

// AssignedUserIDLT applies the LT predicate on the "assigned_user_id" field.
func AssignedUserIDLT(v int64) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldLT(FieldAssignedUserID, v))
}

// AssignedUserIDLTE applies the LTE predicate on the "assigned_user_id" field.
func AssignedUserIDLTE(v int64) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldLTE(FieldAssignedUserID, v))
}

// AssignedUserIDIsNil applies the IsNil predicate on the "assigned_user_id" field.
func AssignedUserIDIsNil() predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldIsNull(FieldAssignedUserID))
}

// AssignedUserIDNotNil applies the NotNil predicate on the "assigned_user_id" field.
func AssignedUserIDNotNil() predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldNotNull(FieldAssignedUserID))
}

// AssignedDrawIDEQ applies the EQ predicate on the "assigned_draw_id" field.
func AssignedDrawIDEQ(v int64) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldEQ(FieldAssignedDrawID, v))
}

// AssignedDrawIDNEQ applies the NEQ predicate on the "assigned_draw_id" field.
func AssignedDrawIDNEQ(v int64) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldNEQ(FieldAssignedDrawID, v))
}

// AssignedDrawIDIn applies the In predicate on the "assigned_draw_id" field.
func AssignedDrawIDIn(vs ...int64) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldIn(FieldAssignedDrawID, vs...))
}

// AssignedDrawIDNotIn applies the NotIn predicate on the "assigned_draw_id" field.
func AssignedDrawIDNotIn(vs ...int64) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldNotIn(FieldAssignedDrawID, vs...))
}

// AssignedDrawIDGT applies the GT predicate on the "assigned_draw_id" field.
func AssignedDrawIDGT(v int64) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldGT(FieldAssignedDrawID, v))
}

// AssignedDrawIDGTE applies the GTE predicate on the "assigned_draw_id" field.
func AssignedDrawIDGTE(v int64) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldGTE(FieldAssignedDrawID, v))
}

// AssignedDrawIDLT applies the LT predicate on the "assigned_draw_id" field.
func AssignedDrawIDLT(v int64) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldLT(FieldAssignedDrawID, v))
}

// AssignedDrawIDLTE applies the LTE predicate on the "assigned_draw_id" field.
func AssignedDrawIDLTE(v int64) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldLTE(FieldAssignedDrawID, v))
}

// AssignedDrawIDIsNil applies the IsNil predicate on the "assigned_draw_id" field.
func AssignedDrawIDIsNil() predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldIsNull(FieldAssignedDrawID))
}

// AssignedDrawIDNotNil applies the NotNil predicate on the "assigned_draw_id" field.
func AssignedDrawIDNotNil() predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldNotNull(FieldAssignedDrawID))
}

// AssignedAtEQ applies the EQ predicate on the "assigned_at" field.
func AssignedAtEQ(v time.Time) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldEQ(FieldAssignedAt, v))
}

// AssignedAtNEQ applies the NEQ predicate on the "assigned_at" field.
func AssignedAtNEQ(v time.Time) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldNEQ(FieldAssignedAt, v))
}

// AssignedAtIn applies the In predicate on the "assigned_at" field.
func AssignedAtIn(vs ...time.Time) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldIn(FieldAssignedAt, vs...))
}

// AssignedAtNotIn applies the NotIn predicate on the "assigned_at" field.
func AssignedAtNotIn(vs ...time.Time) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldNotIn(FieldAssignedAt, vs...))
}

// AssignedAtGT applies the GT predicate on the "assigned_at" field.
func AssignedAtGT(v time.Time) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldGT(FieldAssignedAt, v))
}

// AssignedAtGTE applies the GTE predicate on the "assigned_at" field.
func AssignedAtGTE(v time.Time) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldGTE(FieldAssignedAt, v))
}

// AssignedAtLT applies the LT predicate on the "assigned_at" field.
func AssignedAtLT(v time.Time) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldLT(FieldAssignedAt, v))
}

// AssignedAtLTE applies the LTE predicate on the "assigned_at" field.
func AssignedAtLTE(v time.Time) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldLTE(FieldAssignedAt, v))
}

// AssignedAtIsNil applies the IsNil predicate on the "assigned_at" field.
func AssignedAtIsNil() predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldIsNull(FieldAssignedAt))
}

// AssignedAtNotNil applies the NotNil predicate on the "assigned_at" field.
func AssignedAtNotNil() predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldNotNull(FieldAssignedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.LotteryCode {
	return predicate.LotteryCode(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LotteryCode) predicate.LotteryCode {
	return predicate.LotteryCode(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LotteryCode) predicate.LotteryCode {
	return predicate.LotteryCode(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LotteryCode) predicate.LotteryCode {
	return predicate.LotteryCode(sql.NotPredicates(p))
}
