// Code generated by ent, DO NOT EDIT.

package balancecacheinvalidationoutbox

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldEQ(FieldUserID, v))
}

// Attempts applies equality check predicate on the "attempts" field. It's identical to AttemptsEQ.
func Attempts(v int) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldEQ(FieldAttempts, v))
}

// NextAttemptAt applies equality check predicate on the "next_attempt_at" field. It's identical to NextAttemptAtEQ.
func NextAttemptAt(v time.Time) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldEQ(FieldNextAttemptAt, v))
}

// ClaimedAt applies equality check predicate on the "claimed_at" field. It's identical to ClaimedAtEQ.
func ClaimedAt(v time.Time) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldEQ(FieldClaimedAt, v))
}

// ClaimToken applies equality check predicate on the "claim_token" field. It's identical to ClaimTokenEQ.
func ClaimToken(v string) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldEQ(FieldClaimToken, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldEQ(FieldLastError, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldLTE(FieldUserID, v))
}

// AttemptsEQ applies the EQ predicate on the "attempts" field.
func AttemptsEQ(v int) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldEQ(FieldAttempts, v))
}

// AttemptsNEQ applies the NEQ predicate on the "attempts" field.
func AttemptsNEQ(v int) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldNEQ(FieldAttempts, v))
}

// AttemptsIn applies the In predicate on the "attempts" field.
func AttemptsIn(vs ...int) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldIn(FieldAttempts, vs...))
}

// AttemptsNotIn applies the NotIn predicate on the "attempts" field.
func AttemptsNotIn(vs ...int) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldNotIn(FieldAttempts, vs...))
}

// AttemptsGT applies the GT predicate on the "attempts" field.
func AttemptsGT(v int) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldGT(FieldAttempts, v))
}

// AttemptsGTE applies the GTE predicate on the "attempts" field.
func AttemptsGTE(v int) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldGTE(FieldAttempts, v))
}

// AttemptsLT applies the LT predicate on the "attempts" field.
func AttemptsLT(v int) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldLT(FieldAttempts, v))
}

// AttemptsLTE applies the LTE predicate on the "attempts" field.
func AttemptsLTE(v int) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldLTE(FieldAttempts, v))
}

// NextAttemptAtEQ applies the EQ predicate on the "next_attempt_at" field.
func NextAttemptAtEQ(v time.Time) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldEQ(FieldNextAttemptAt, v))
}

// NextAttemptAtNEQ applies the NEQ predicate on the "next_attempt_at" field.
func NextAttemptAtNEQ(v time.Time) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldNEQ(FieldNextAttemptAt, v))
}

// NextAttemptAtIn applies the In predicate on the "next_attempt_at" field.
func NextAttemptAtIn(vs ...time.Time) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldIn(FieldNextAttemptAt, vs...))
}

// NextAttemptAtNotIn applies the NotIn predicate on the "next_attempt_at" field.
func NextAttemptAtNotIn(vs ...time.Time) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldNotIn(FieldNextAttemptAt, vs...))
}

// NextAttemptAtGT applies the GT predicate on the "next_attempt_at" field.
func NextAttemptAtGT(v time.Time) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldGT(FieldNextAttemptAt, v))
}

// NextAttemptAtGTE applies the GTE predicate on the "next_attempt_at" field.
func NextAttemptAtGTE(v time.Time) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldGTE(FieldNextAttemptAt, v))
}

// NextAttemptAtLT applies the LT predicate on the "next_attempt_at" field.
func NextAttemptAtLT(v time.Time) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldLT(FieldNextAttemptAt, v))
}

// NextAttemptAtLTE applies the LTE predicate on the "next_attempt_at" field.
func NextAttemptAtLTE(v time.Time) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldLTE(FieldNextAttemptAt, v))
}

// ClaimedAtEQ applies the EQ predicate on the "claimed_at" field.
func ClaimedAtEQ(v time.Time) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldEQ(FieldClaimedAt, v))
}

// ClaimedAtNEQ applies the NEQ predicate on the "claimed_at" field.
func ClaimedAtNEQ(v time.Time) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldNEQ(FieldClaimedAt, v))
}

// ClaimedAtIn applies the In predicate on the "claimed_at" field.
func ClaimedAtIn(vs ...time.Time) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldIn(FieldClaimedAt, vs...))
}

// ClaimedAtNotIn applies the NotIn predicate on the "claimed_at" field.
func ClaimedAtNotIn(vs ...time.Time) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldNotIn(FieldClaimedAt, vs...))
}

// ClaimedAtGT applies the GT predicate on the "claimed_at" field.
func ClaimedAtGT(v time.Time) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldGT(FieldClaimedAt, v))
}

// ClaimedAtGTE applies the GTE predicate on the "claimed_at" field.
func ClaimedAtGTE(v time.Time) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldGTE(FieldClaimedAt, v))
}

// ClaimedAtLT applies the LT predicate on the "claimed_at" field.
func ClaimedAtLT(v time.Time) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldLT(FieldClaimedAt, v))
}

// ClaimedAtLTE applies the LTE predicate on the "claimed_at" field.
func ClaimedAtLTE(v time.Time) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldLTE(FieldClaimedAt, v))
}

// ClaimedAtIsNil applies the IsNil predicate on the "claimed_at" field.
func ClaimedAtIsNil() predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldIsNull(FieldClaimedAt))
}

// ClaimedAtNotNil applies the NotNil predicate on the "claimed_at" field.
func ClaimedAtNotNil() predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldNotNull(FieldClaimedAt))
}

// ClaimTokenEQ applies the EQ predicate on the "claim_token" field.
func ClaimTokenEQ(v string) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldEQ(FieldClaimToken, v))
}

// ClaimTokenNEQ applies the NEQ predicate on the "claim_token" field.
func ClaimTokenNEQ(v string) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldNEQ(FieldClaimToken, v))
}

// ClaimTokenIn applies the In predicate on the "claim_token" field.
func ClaimTokenIn(vs ...string) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldIn(FieldClaimToken, vs...))
}

// ClaimTokenNotIn applies the NotIn predicate on the "claim_token" field.
func ClaimTokenNotIn(vs ...string) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldNotIn(FieldClaimToken, vs...))
}

// ClaimTokenGT applies the GT predicate on the "claim_token" field.
func ClaimTokenGT(v string) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldGT(FieldClaimToken, v))
}

// ClaimTokenGTE applies the GTE predicate on the "claim_token" field.
func ClaimTokenGTE(v string) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldGTE(FieldClaimToken, v))
}

// ClaimTokenLT applies the LT predicate on the "claim_token" field.
func ClaimTokenLT(v string) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldLT(FieldClaimToken, v))
}

// ClaimTokenLTE applies the LTE predicate on the "claim_token" field.
func ClaimTokenLTE(v string) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldLTE(FieldClaimToken, v))
}

// ClaimTokenContains applies the Contains predicate on the "claim_token" field.
func ClaimTokenContains(v string) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldContains(FieldClaimToken, v))
}

// ClaimTokenHasPrefix applies the HasPrefix predicate on the "claim_token" field.
func ClaimTokenHasPrefix(v string) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldHasPrefix(FieldClaimToken, v))
}

// ClaimTokenHasSuffix applies the HasSuffix predicate on the "claim_token" field.
func ClaimTokenHasSuffix(v string) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldHasSuffix(FieldClaimToken, v))
}

// ClaimTokenIsNil applies the IsNil predicate on the "claim_token" field.
func ClaimTokenIsNil() predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldIsNull(FieldClaimToken))
}

// ClaimTokenNotNil applies the NotNil predicate on the "claim_token" field.
func ClaimTokenNotNil() predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldNotNull(FieldClaimToken))
}

// ClaimTokenEqualFold applies the EqualFold predicate on the "claim_token" field.
func ClaimTokenEqualFold(v string) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldEqualFold(FieldClaimToken, v))
}

// ClaimTokenContainsFold applies the ContainsFold predicate on the "claim_token" field.
func ClaimTokenContainsFold(v string) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldContainsFold(FieldClaimToken, v))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.FieldContainsFold(FieldLastError, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BalanceCacheInvalidationOutbox) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BalanceCacheInvalidationOutbox) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BalanceCacheInvalidationOutbox) predicate.BalanceCacheInvalidationOutbox {
	return predicate.BalanceCacheInvalidationOutbox(sql.NotPredicates(p))
}
