<template>
  <AppLayout><div class="mx-auto max-w-6xl space-y-6">
    <header class="border-b border-gray-200 pb-5 dark:border-dark-700"><div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 class="font-serif text-2xl font-semibold text-gray-900 dark:text-white">{{ t('checkin.title') }}</h1><p class="mt-1 text-sm text-gray-500 dark:text-gray-400">{{ t('checkin.description') }}</p></div><div v-if="authStore.user" class="min-w-0 sm:text-right"><p class="truncate text-sm font-medium">{{ authStore.user.username }}</p><p class="truncate text-xs text-gray-500">{{ authStore.user.email }}</p></div></div></header>
    <div v-if="store.loading && !store.status" class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4" aria-busy="true"><div v-for="index in 4" :key="index" class="h-24 animate-pulse rounded-md bg-gray-100 dark:bg-dark-800"></div></div>
    <section v-else-if="loadError" class="rounded-md border border-red-200 bg-red-50 p-5 dark:border-red-900/60 dark:bg-red-950/30"><p class="text-sm text-red-700">{{ t('checkin.loadFailed') }}</p><button type="button" class="btn btn-secondary mt-3" @click="loadStatus">{{ t('checkin.retry') }}</button></section>
    <template v-else-if="store.status">
      <section class="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div v-for="stat in stats" :key="stat.label" class="card p-4"><p class="text-xs font-medium text-gray-500">{{ stat.label }}</p><p class="ui-mono mt-2 text-xl font-semibold">{{ stat.value }}</p></div></section>
      <section class="overflow-hidden rounded-md border border-gray-200 bg-white dark:border-dark-700 dark:bg-dark-900"><div class="grid lg:grid-cols-[minmax(0,1fr)_22rem]">
        <div class="p-5 sm:p-6"><div class="flex items-start gap-3"><div class="flex h-10 w-10 items-center justify-center rounded-md bg-primary-50 text-primary-600"><Icon name="calendar" size="lg" /></div><div><p class="text-sm font-semibold">{{ t('checkin.nextMilestone.title') }}</p><template v-if="store.status.next_milestone"><p class="mt-1 ui-mono">{{ t('checkin.nextMilestone.detail', { day: store.status.next_milestone.day, bonus: store.status.next_milestone.bonus }) }}</p><p class="mt-1 text-xs text-gray-500">{{ t('checkin.nextMilestone.remaining', { count: store.status.next_milestone.days_until }) }}</p></template><p v-else class="mt-1 text-sm text-gray-500">{{ t('checkin.nextMilestone.none') }}</p></div></div>
          <p v-if="store.status.today_record" data-test="today-result" class="mt-5 rounded-md px-3 py-2 text-sm" :class="store.status.today_record.status === 'awarded' ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700'">{{ todayMessage }}</p></div>
        <div class="flex items-center border-t border-gray-200 bg-gray-50 p-5 dark:border-dark-700 dark:bg-dark-800/60 lg:border-l lg:border-t-0"><div class="w-full"><button type="button" data-test="checkin-action" class="btn btn-primary h-12 w-full justify-center text-base" :disabled="actionDisabled" @click="performCheckin"><Icon :name="store.checkedInToday ? 'checkCircle' : 'gift'" size="md" /><span>{{ actionLabel }}</span></button><p v-if="actionError" class="mt-2 text-center text-xs text-red-600">{{ t('checkin.loadFailed') }}</p></div></div>
      </div></section>
      <section><div class="mb-3 flex items-center justify-between"><h2 class="text-base font-semibold">{{ t('checkin.history.title') }}</h2><button type="button" class="btn btn-secondary h-9 w-9 p-0" :title="t('common.refresh')" @click="loadStatus"><Icon name="refresh" size="sm" :class="store.loading ? 'animate-spin' : ''" /></button></div>
        <div v-if="!store.status.recent_records.length" class="rounded-md border border-dashed border-gray-300 py-12 text-center text-sm text-gray-500">{{ t('checkin.history.empty') }}</div>
        <div v-else class="overflow-hidden rounded-md border border-gray-200 bg-white dark:border-dark-700 dark:bg-dark-900">
          <div class="hidden overflow-x-auto md:block"><table class="w-full min-w-[760px] divide-y divide-gray-200"><thead class="bg-gray-50 text-left text-xs text-gray-500"><tr><th class="px-4 py-3">{{ t('checkin.history.time') }}</th><th class="px-4 py-3">{{ t('checkin.history.streak') }}</th><th v-for="key in ['base','milestone','actual','balance']" :key="key" class="px-4 py-3 text-right">{{ t(`checkin.history.${key}`) }}</th></tr></thead><tbody class="divide-y divide-gray-100"><tr v-for="record in store.status.recent_records" :key="record.id"><td class="whitespace-nowrap px-4 py-3 text-sm">{{ formatCheckedAt(record.checked_at) }}</td><td class="ui-mono px-4 py-3">{{ record.streak_days }} / {{ record.cycle_day }}</td><td class="ui-mono px-4 py-3 text-right">${{ record.base_reward }}</td><td class="ui-mono px-4 py-3 text-right">${{ record.milestone_bonus }}</td><td class="ui-mono px-4 py-3 text-right font-semibold">${{ record.actual_reward }}</td><td class="ui-mono px-4 py-3 text-right">${{ record.balance_after }}</td></tr></tbody></table></div>
          <div class="divide-y divide-gray-100 md:hidden"><article v-for="record in store.status.recent_records" :key="record.id" class="p-4"><div class="flex justify-between gap-3"><div><p class="text-sm font-medium">{{ formatCheckedAt(record.checked_at) }}</p><p class="ui-mono mt-1 text-xs text-gray-500">{{ record.streak_days }} / {{ record.cycle_day }}</p></div><span class="ui-mono text-sm font-semibold">+${{ record.actual_reward }}</span></div><div class="mt-3 grid grid-cols-2 gap-2 text-xs text-gray-500"><span>{{ t('checkin.history.base') }}: ${{ record.base_reward }}</span><span>{{ t('checkin.history.milestone') }}: ${{ record.milestone_bonus }}</span><span class="col-span-2">{{ t('checkin.history.balance') }}: ${{ record.balance_after }}</span></div></article></div>
        </div>
      </section>
    </template>
  </div></AppLayout>
</template>
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'; import { useI18n } from 'vue-i18n'
import AppLayout from '@/components/layout/AppLayout.vue'; import Icon from '@/components/icons/Icon.vue'; import { useAuthStore } from '@/stores/auth'; import { formatDateTimeToMinute } from '@/utils/format'; import { useCheckinStore } from './store'
const { t } = useI18n(); const store = useCheckinStore(); const authStore = useAuthStore(); const loadError = ref(false), actionError = ref(false)
const stats = computed(() => store.status ? [{ label: t('checkin.stats.balance'), value: `$${store.status.balance}` }, { label: t('checkin.stats.totalCheckins'), value: String(store.status.total_checkins) }, { label: t('checkin.stats.totalReward'), value: `$${store.status.total_reward}` }, { label: t('checkin.stats.currentStreak'), value: t('checkin.stats.days', { count: store.status.current_streak }) }] : [])
const actionDisabled = computed(() => store.submitting || !store.status?.enabled || store.status.checked_in_today)
const actionLabel = computed(() => store.submitting ? t('checkin.action.loading') : !store.status?.enabled ? t('checkin.action.disabled') : store.status.today_record?.status === 'budget_exhausted' ? t('checkin.action.exhausted') : store.status.checked_in_today ? t('checkin.action.checked') : t('checkin.action.ready'))
const todayMessage = computed(() => { const record = store.status?.today_record; return !record ? '' : store.lastResult?.already_checked_in ? t('checkin.today.replayed') : record.status === 'budget_exhausted' ? t('checkin.today.exhausted') : t('checkin.today.awarded', { amount: record.actual_reward }) })
function formatCheckedAt(value: string) { return formatDateTimeToMinute(value) || '-' }
async function loadStatus() { loadError.value = false; try { await store.fetchStatus() } catch { loadError.value = true } }
async function performCheckin() { if (actionDisabled.value) return; actionError.value = false; try { await store.checkIn() } catch { actionError.value = true } }
onMounted(() => { if (!store.status) void loadStatus() })
</script>
