//go:build embed

package web

import (
	"bytes"
	"context"
	"embed"
	"encoding/json"
	htmlpkg "html"
	"io"
	"io/fs"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/Wei-Shaw/sub2api/internal/server/middleware"
	"github.com/gin-gonic/gin"
)

const (
	// NonceHTMLPlaceholder is the placeholder for nonce in HTML script tags
	NonceHTMLPlaceholder = "__CSP_NONCE_VALUE__"
)

//go:embed all:dist
var frontendFS embed.FS

// PublicSettingsProvider is an interface to fetch public settings
type PublicSettingsProvider interface {
	GetPublicSettingsForInjection(ctx context.Context) (any, error)
}

// FrontendServer serves the embedded frontend with settings injection
type FrontendServer struct {
	distFS      fs.FS
	fileServer  http.Handler
	baseHTML    []byte
	cache       *HTMLCache
	settings    PublicSettingsProvider
	overrideDir string // local file override directory
}

// NewFrontendServer creates a new frontend server with settings injection
func NewFrontendServer(settingsProvider PublicSettingsProvider) (*FrontendServer, error) {
	distFS, err := fs.Sub(frontendFS, "dist")
	if err != nil {
		return nil, err
	}

	// Read base HTML once
	file, err := distFS.Open("index.html")
	if err != nil {
		return nil, err
	}
	defer func() { _ = file.Close() }()

	baseHTML, err := io.ReadAll(file)
	if err != nil {
		return nil, err
	}

	cache := NewHTMLCache()
	cache.SetBaseHTML(baseHTML)

	return &FrontendServer{
		distFS:      distFS,
		fileServer:  http.FileServer(http.FS(distFS)),
		baseHTML:    baseHTML,
		cache:       cache,
		settings:    settingsProvider,
		overrideDir: filepath.Join("data", "public"),
	}, nil
}

// InvalidateCache invalidates the HTML cache (call when settings change)
func (s *FrontendServer) InvalidateCache() {
	if s != nil && s.cache != nil {
		s.cache.Invalidate()
	}
}

// Middleware returns the Gin middleware handler
func (s *FrontendServer) Middleware() gin.HandlerFunc {
	return func(c *gin.Context) {
		path := c.Request.URL.Path

		if redirectLegacyHome(c, path) {
			return
		}

		// Skip API routes
		if shouldBypassEmbeddedFrontend(path) {
			c.Next()
			return
		}

		cleanPath := strings.TrimPrefix(path, "/")
		if cleanPath == "" {
			cleanPath = "index.html"
		}

		// For index.html or SPA routes, serve with injected settings
		if cleanPath == "index.html" || !s.fileExists(cleanPath) {
			s.serveIndexHTML(c)
			return
		}

		// Try local override first
		if s.tryServeOverride(c, cleanPath) {
			return
		}

		// Serve static files normally (hashed assets get long-lived cache headers)
		applyStaticAssetCacheHeaders(c.Writer.Header(), cleanPath)
		s.fileServer.ServeHTTP(c.Writer, c.Request)
		c.Abort()
	}
}

func (s *FrontendServer) fileExists(path string) bool {
	file, err := s.distFS.Open(path)
	if err != nil {
		return false
	}
	_ = file.Close()
	return true
}

// tryServeOverride checks if a local override file exists and serves it.
// Files in overrideDir take precedence over embedded files.
func (s *FrontendServer) tryServeOverride(c *gin.Context, cleanPath string) bool {
	if s.overrideDir == "" {
		return false
	}
	filePath := filepath.Join(s.overrideDir, filepath.Clean("/"+cleanPath))
	info, err := os.Stat(filePath)
	if err != nil || info.IsDir() {
		return false
	}
	c.File(filePath)
	c.Abort()
	return true
}

func (s *FrontendServer) serveIndexHTML(c *gin.Context) {
	// Get nonce from context (generated by SecurityHeaders middleware)
	nonce := middleware.GetNonceFromContext(c)

	// Check cache first
	cached := s.cache.Get()
	if cached != nil {
		// Check If-None-Match for 304 response
		if match := c.GetHeader("If-None-Match"); match == cached.ETag {
			c.Status(http.StatusNotModified)
			c.Abort()
			return
		}

		// Replace nonce placeholder with actual nonce before serving
		content := replaceNoncePlaceholder(cached.Content, nonce)

		c.Header("ETag", cached.ETag)
		c.Header("Cache-Control", "no-cache") // Must revalidate
		c.Data(http.StatusOK, "text/html; charset=utf-8", content)
		c.Abort()
		return
	}

	// Cache miss - fetch settings and render
	ctx, cancel := context.WithTimeout(c.Request.Context(), 2*time.Second)
	defer cancel()

	settings, err := s.settings.GetPublicSettingsForInjection(ctx)
	if err != nil {
		// Fallback: serve without injection
		c.Data(http.StatusOK, "text/html; charset=utf-8", s.baseHTML)
		c.Abort()
		return
	}

	settingsJSON, err := json.Marshal(settings)
	if err != nil {
		// Fallback: serve without injection
		c.Data(http.StatusOK, "text/html; charset=utf-8", s.baseHTML)
		c.Abort()
		return
	}

	rendered := s.injectSettings(settingsJSON)
	s.cache.Set(rendered, settingsJSON)

	// Replace nonce placeholder with actual nonce before serving
	content := replaceNoncePlaceholder(rendered, nonce)

	cached = s.cache.Get()
	if cached != nil {
		c.Header("ETag", cached.ETag)
	}
	c.Header("Cache-Control", "no-cache")
	c.Data(http.StatusOK, "text/html; charset=utf-8", content)
	c.Abort()
}

func (s *FrontendServer) injectSettings(settingsJSON []byte) []byte {
	// Create the script tag to inject with nonce placeholder
	// The placeholder will be replaced with actual nonce at request time
	script := []byte(`<script nonce="` + NonceHTMLPlaceholder + `">window.__APP_CONFIG__=` + string(settingsJSON) + `;</script>`)

	// Inject before </head>
	headClose := []byte("</head>")
	result := bytes.Replace(s.baseHTML, headClose, append(script, headClose...), 1)

	// Apply custom branding before the browser paints the static defaults.
	result = injectSiteTitle(result, settingsJSON)
	result = injectSiteFavicon(result, settingsJSON)
	result = injectSEOMeta(result, settingsJSON)

	return result
}

// injectSiteFavicon replaces the static favicon with a configured, browser-safe image URL.
func injectSiteFavicon(html, settingsJSON []byte) []byte {
	var cfg struct {
		SiteLogo string `json:"site_logo"`
	}
	if err := json.Unmarshal(settingsJSON, &cfg); err != nil {
		return html
	}

	logoURL := safeImageURL(cfg.SiteLogo)
	if logoURL == "" {
		return html
	}

	linkStart := bytes.Index(html, []byte(`<link rel="icon"`))
	if linkStart == -1 {
		return html
	}
	linkEndOffset := bytes.IndexByte(html[linkStart:], '>')
	if linkEndOffset == -1 {
		return html
	}
	linkEnd := linkStart + linkEndOffset + 1
	replacement := []byte(`<link rel="icon" href="` + htmlpkg.EscapeString(logoURL) + `" />`)

	var buf bytes.Buffer
	buf.Write(html[:linkStart])
	buf.Write(replacement)
	buf.Write(html[linkEnd:])
	return buf.Bytes()
}

func safeImageURL(value string) string {
	trimmed := strings.TrimSpace(value)
	if trimmed == "" {
		return ""
	}
	if strings.HasPrefix(trimmed, "/") && !strings.HasPrefix(trimmed, "//") {
		return trimmed
	}
	if strings.HasPrefix(strings.ToLower(trimmed), "data:image/") {
		return trimmed
	}

	parsed, err := url.Parse(trimmed)
	if err != nil || (parsed.Scheme != "http" && parsed.Scheme != "https") || parsed.Host == "" {
		return ""
	}
	return trimmed
}

// injectSiteTitle replaces the static <title> in HTML with the configured site name.
// This ensures the browser tab shows the correct title before JS executes.
func injectSiteTitle(html, settingsJSON []byte) []byte {
	var cfg struct {
		SiteName string `json:"site_name"`
	}
	if err := json.Unmarshal(settingsJSON, &cfg); err != nil || cfg.SiteName == "" {
		return html
	}

	// Find and replace the existing <title>...</title>
	titleStart := bytes.Index(html, []byte("<title>"))
	titleEnd := bytes.Index(html, []byte("</title>"))
	if titleStart == -1 || titleEnd == -1 || titleEnd <= titleStart {
		return html
	}

	newTitle := []byte("<title>" + htmlpkg.EscapeString(cfg.SiteName) + " · AI API 中转与管理平台</title>")
	var buf bytes.Buffer
	buf.Write(html[:titleStart])
	buf.Write(newTitle)
	buf.Write(html[titleEnd+len("</title>"):])
	return buf.Bytes()
}

const (
	seoMetaStart       = "<!--seo-meta-->"
	seoMetaEnd         = "<!--/seo-meta-->"
	seoDescriptionBody = "是 AI API 中转与管理平台,统一接入 Anthropic Claude、OpenAI GPT、Google Gemini 等主流模型,提供 API Key 管理、额度计费与用量统计。"
)

// injectSEOMeta rewrites the marked SEO block when site_name is set.
// Empty site_name leaves the static index.html defaults untouched so
// crawlers still see the baked-in description / OG / JSON-LD.
func injectSEOMeta(html, settingsJSON []byte) []byte {
	var cfg struct {
		SiteName   string `json:"site_name"`
		APIBaseURL string `json:"api_base_url"`
	}
	if err := json.Unmarshal(settingsJSON, &cfg); err != nil {
		return html
	}

	siteName := strings.TrimSpace(cfg.SiteName)
	if siteName == "" {
		return html
	}

	description := siteName + " " + seoDescriptionBody
	ogTitle := siteName + " · AI API 中转与管理平台"
	canonical := canonicalSiteURL(cfg.APIBaseURL)
	if canonical == "" {
		canonical = existingCanonicalURL(html)
	}
	email := existingJSONLDEmail(html)

	var buf bytes.Buffer
	buf.WriteString(`<meta name="description" content="` + htmlpkg.EscapeString(description) + `">`)
	if canonical != "" {
		buf.WriteString(`<link rel="canonical" href="` + htmlpkg.EscapeString(canonical) + `">`)
	}
	buf.WriteString(`<meta property="og:type" content="website">`)
	buf.WriteString(`<meta property="og:site_name" content="` + htmlpkg.EscapeString(siteName) + `">`)
	buf.WriteString(`<meta property="og:locale" content="zh_CN">`)
	buf.WriteString(`<meta property="og:title" content="` + htmlpkg.EscapeString(ogTitle) + `">`)
	buf.WriteString(`<meta property="og:description" content="` + htmlpkg.EscapeString(description) + `">`)
	if canonical != "" {
		buf.WriteString(`<meta property="og:url" content="` + htmlpkg.EscapeString(canonical) + `">`)
	}
	buf.WriteString(`<meta name="twitter:card" content="summary">`)
	buf.WriteString(`<meta name="twitter:title" content="` + htmlpkg.EscapeString(ogTitle) + `">`)
	buf.WriteString(`<meta name="twitter:description" content="` + htmlpkg.EscapeString(description) + `">`)

	org := map[string]any{
		"@type": "Organization",
		"name":  siteName,
	}
	website := map[string]any{
		"@type": "WebSite",
		"name":  siteName,
	}
	if canonical != "" {
		org["url"] = canonical
		website["url"] = canonical
	}
	if email != "" {
		org["email"] = email
	}
	ldJSON, err := json.Marshal(map[string]any{
		"@context": "https://schema.org",
		"@graph":   []any{org, website},
	})
	if err == nil {
		buf.WriteString(`<script type="application/ld+json" nonce="` + NonceHTMLPlaceholder + `">`)
		buf.Write(ldJSON)
		buf.WriteString(`</script>`)
	}

	return applySEOMetaBlock(html, buf.Bytes())
}

func applySEOMetaBlock(html, inner []byte) []byte {
	start := bytes.Index(html, []byte(seoMetaStart))
	end := bytes.Index(html, []byte(seoMetaEnd))
	if start != -1 && end != -1 && end > start {
		end += len(seoMetaEnd)
		var buf bytes.Buffer
		buf.Write(html[:start])
		buf.WriteString(seoMetaStart)
		buf.Write(inner)
		buf.WriteString(seoMetaEnd)
		buf.Write(html[end:])
		return buf.Bytes()
	}

	headClose := []byte("</head>")
	if !bytes.Contains(html, headClose) {
		return html
	}
	var buf bytes.Buffer
	buf.WriteString(seoMetaStart)
	buf.Write(inner)
	buf.WriteString(seoMetaEnd)
	return bytes.Replace(html, headClose, append(buf.Bytes(), headClose...), 1)
}

func canonicalSiteURL(value string) string {
	trimmed := safeAbsoluteHTTPURL(value)
	if trimmed == "" {
		return ""
	}
	parsed, err := url.Parse(trimmed)
	if err != nil {
		return trimmed
	}
	if parsed.Path == "" {
		parsed.Path = "/"
	}
	return parsed.String()
}

func existingCanonicalURL(html []byte) string {
	marker := []byte(`rel="canonical"`)
	pos := bytes.Index(html, marker)
	if pos == -1 {
		return ""
	}
	windowStart := pos - 64
	if windowStart < 0 {
		windowStart = 0
	}
	window := html[windowStart:]
	href := []byte(`href="`)
	hrefAt := bytes.Index(window, href)
	if hrefAt == -1 {
		return ""
	}
	valueStart := hrefAt + len(href)
	valueEnd := bytes.IndexByte(window[valueStart:], '"')
	if valueEnd == -1 {
		return ""
	}
	return htmlpkg.UnescapeString(string(window[valueStart : valueStart+valueEnd]))
}

func existingJSONLDEmail(html []byte) string {
	marker := []byte(`<script type="application/ld+json"`)
	start := bytes.Index(html, marker)
	if start == -1 {
		return ""
	}
	contentStart := bytes.Index(html[start:], []byte(">"))
	if contentStart == -1 {
		return ""
	}
	contentStart += start + 1
	end := bytes.Index(html[contentStart:], []byte("</script>"))
	if end == -1 {
		return ""
	}
	var parsed struct {
		Graph []struct {
			Type  string `json:"@type"`
			Email string `json:"email"`
		} `json:"@graph"`
	}
	if err := json.Unmarshal(html[contentStart:contentStart+end], &parsed); err != nil {
		return ""
	}
	for _, node := range parsed.Graph {
		if strings.EqualFold(node.Type, "Organization") {
			return strings.TrimSpace(node.Email)
		}
	}
	return ""
}

func safeAbsoluteHTTPURL(value string) string {
	trimmed := strings.TrimSpace(value)
	if trimmed == "" {
		return ""
	}
	parsed, err := url.Parse(trimmed)
	if err != nil || (parsed.Scheme != "http" && parsed.Scheme != "https") || parsed.Host == "" {
		return ""
	}
	return trimmed
}

// replaceNoncePlaceholder replaces the nonce placeholder with actual nonce value
func replaceNoncePlaceholder(html []byte, nonce string) []byte {
	return bytes.ReplaceAll(html, []byte(NonceHTMLPlaceholder), []byte(nonce))
}

// ServeEmbeddedFrontend returns a middleware for serving embedded frontend
// This is the legacy function for backward compatibility when no settings provider is available
func ServeEmbeddedFrontend() gin.HandlerFunc {
	distFS, err := fs.Sub(frontendFS, "dist")
	if err != nil {
		panic("failed to get dist subdirectory: " + err.Error())
	}
	fileServer := http.FileServer(http.FS(distFS))
	overrideDir := filepath.Join("data", "public")

	return func(c *gin.Context) {
		path := c.Request.URL.Path

		if redirectLegacyHome(c, path) {
			return
		}

		if shouldBypassEmbeddedFrontend(path) {
			c.Next()
			return
		}

		cleanPath := strings.TrimPrefix(path, "/")
		if cleanPath == "" {
			cleanPath = "index.html"
		}

		if file, err := distFS.Open(cleanPath); err == nil {
			_ = file.Close()
			// Try local override first
			if tryServeOverrideFile(c, overrideDir, cleanPath) {
				return
			}
			applyStaticAssetCacheHeaders(c.Writer.Header(), cleanPath)
			fileServer.ServeHTTP(c.Writer, c.Request)
			c.Abort()
			return
		}

		serveIndexHTML(c, distFS)
	}
}

func redirectLegacyHome(c *gin.Context, path string) bool {
	if path != "/home" || (c.Request.Method != http.MethodGet && c.Request.Method != http.MethodHead) {
		return false
	}
	c.Redirect(http.StatusMovedPermanently, "/")
	c.Abort()
	return true
}

// tryServeOverrideFile is a standalone version of tryServeOverride for legacy usage.
func tryServeOverrideFile(c *gin.Context, overrideDir, cleanPath string) bool {
	if overrideDir == "" {
		return false
	}
	filePath := filepath.Join(overrideDir, filepath.Clean("/"+cleanPath))
	info, err := os.Stat(filePath)
	if err != nil || info.IsDir() {
		return false
	}
	c.File(filePath)
	c.Abort()
	return true
}

func shouldBypassEmbeddedFrontend(path string) bool {
	trimmed := strings.TrimSpace(path)
	return strings.HasPrefix(trimmed, "/api/") ||
		strings.HasPrefix(trimmed, "/v1/") ||
		strings.HasPrefix(trimmed, "/v1beta/") ||
		strings.HasPrefix(trimmed, "/backend-api/") ||
		strings.HasPrefix(trimmed, "/antigravity/") ||
		strings.HasPrefix(trimmed, "/setup/") ||
		trimmed == "/health" ||
		trimmed == "/models" ||
		trimmed == "/sitemap_index.xml" ||
		trimmed == "/sitemap.txt" ||
		trimmed == "/responses" ||
		strings.HasPrefix(trimmed, "/responses/") ||
		trimmed == "/alpha/search" ||
		trimmed == "/x_search" ||
		strings.HasPrefix(trimmed, "/images/")
}

func serveIndexHTML(c *gin.Context, fsys fs.FS) {
	file, err := fsys.Open("index.html")
	if err != nil {
		c.String(http.StatusNotFound, "Frontend not found")
		c.Abort()
		return
	}
	defer func() { _ = file.Close() }()

	content, err := io.ReadAll(file)
	if err != nil {
		c.String(http.StatusInternalServerError, "Failed to read index.html")
		c.Abort()
		return
	}

	c.Data(http.StatusOK, "text/html; charset=utf-8", content)
	c.Abort()
}

func HasEmbeddedFrontend() bool {
	_, err := frontendFS.ReadFile("dist/index.html")
	return err == nil
}
