import { beforeEach, describe, expect, it, vi } from 'vitest'; import { flushPromises, mount } from '@vue/test-utils'; import { createPinia, setActivePinia } from 'pinia'; import type { CheckinStatus } from '../types'
const messages: Record<string, string> = { 'checkin.action.exhausted': "Today's reward pool is exhausted", 'checkin.today.awarded': 'Today you received ${amount}.' }
vi.mock('vue-i18n', async () => { const actual = await vi.importActual<typeof import('vue-i18n')>('vue-i18n'); return { ...actual, useI18n: () => ({ t: (key: string, params?: Record<string, unknown>) => Object.entries(params ?? {}).reduce((text, [name, value]) => text.replace(`{${name}}`, String(value)), messages[key] ?? key) }) } })
const api = vi.hoisted(() => ({ getUserStatus: vi.fn(), checkIn: vi.fn() })); vi.mock('../api', () => ({ checkinAPI: api })); import CheckinView from '../CheckinView.vue'
const record = { id: 1, user_id: 4, user_email: 'user@example.com', username: 'user', business_date: '2026-08-19', checked_at: '2026-08-19T01:00:00Z', timezone: 'Asia/Shanghai', streak_days: 3, cycle_day: 3, base_reward: '0.4000', milestone_bonus: '0.0000', actual_reward: '0.0000', status: 'budget_exhausted' as const, balance_after: '10.0000' }
const status: CheckinStatus = { enabled: true, checked_in_today: true, total_checkins: 8, total_reward: '2.0000', current_streak: 3, cycle_day: 3, next_milestone: { day: 7, bonus: '1.0000', days_until: 4 }, balance: '10.0000', today_record: record, recent_records: [] }
describe('CheckinView', () => {
  beforeEach(() => { setActivePinia(createPinia()); api.getUserStatus.mockReset(); api.checkIn.mockReset() })
  it('disables action when the pool is exhausted', async () => { api.getUserStatus.mockResolvedValue(status); const wrapper = mount(CheckinView, { global: { plugins: [createPinia()], stubs: { AppLayout: { template: '<main><slot /></main>' } } } }); await flushPromises(); const button = wrapper.get('[data-test="checkin-action"]'); expect(button.attributes('disabled')).toBeDefined(); expect(button.text()).toContain("Today's reward pool is exhausted") })
  it('renders a zero-dollar awarded record as successful', async () => { api.getUserStatus.mockResolvedValue({ ...status, today_record: { ...record, base_reward: '0.0000', status: 'awarded' } }); const wrapper = mount(CheckinView, { global: { plugins: [createPinia()], stubs: { AppLayout: { template: '<main><slot /></main>' } } } }); await flushPromises(); expect(wrapper.get('[data-test="today-result"]').text()).toContain('$0.0000') })
})
